### ISSUE TITLE
Support for tracing on AWS Lambda

### ISSUE THREAD

**Issue by lupengamzn** [open-telemetry/opentelemetry-dotnet-contrib#103]
This issue is mainly about instrumenting the SDK wrapper for tracing AWS Lambda handler.

What the wrapper needs to implement for an incoming Lambda handler span:
1. Inherit trace id `_X_AMAZON_TRACE_ID` from AWS Lambda runtime or upstream
2. Record AWS Lambda resource [attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/86aeab1e0a7e6c67be09c7f15ff25063ee6d2b5c/specification/trace/semantic_conventions/instrumentation/aws-lambda.md)

Will keep updating and submit a PR

**Comment by Kielek** [comment]
Closing per @Oberon00 comment.
