### ISSUE TITLE
Drop unsupported .NET runtime supports

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet-contrib#1031]
The main repo has a clear statement about the .NET runtimes its supports : https://github.com/open-telemetry/opentelemetry-dotnet#supported-net-versions

The contrib repo does not have any such statement, and is mostly upto the individual components to state their supported runtimes. This is okay, given the components are contributed by different individuals/companies. However, there lacks any guidance for component authors regarding which ones they should (and should not) support. 

Proposing to add the following guidance (Draft)
1. Components SHOULD  support all officially supported .NET Runtimes.
2. Components SHOULD not support out-of-support .NET runtimes (eg: .NET 452, .NET Core 2.1 etc).
3. If a component chose to support out-of-support runtimes, the CI checks in this repo is *not* going to cover them. (TODO: Decide if we are moving to ci-per-component, to allow components to add unsupported .NET version to their  CI files).
4. Clearly document which runtimes are supported in the main readme.md.
5. Whenever a .NET version goes out of support, drop support for it in the component as well. (This does not require major version bump). (TODO: Add examples on when such changes were made previously).

What to do with existing components? 
There are few components right now which currently targets out-of-support versions. Will list them here and tag the owners so that they can start removing them. 
Once all components are done with the above, we'd need to remove CI checks for them (right now CI checks are done for .NET Core 3.1, which is an unsupported version)

**Comment by cijothomas** [comment]
@vishweshbankwar has agreed to make this happen.

**Comment by CodeBlanch** [comment]
> 3. If a component chose to support out-of-support runtimes, the CI checks in this repo is not going to cover them.

Why would we allow something to ship from the repo if we're not running tests for it? Seems risky.

**Comment by cijothomas** [comment]
> > 3. If a component chose to support out-of-support runtimes, the CI checks in this repo is not going to cover them.
> 
> Why would we allow something to ship from the repo if we're not running tests for it? Seems risky.

Yes. That part needs some refinement (TODO). We could move to a system where components could have own CI files, and can chose to add any .NET versions.

Options:
1. Disallow any component from supporting out-of-support .NET
2. Allow component to support out-of-support .NET, but its the component's responsibility to add sufficient test. (This require us to move to component specific CI)
3. Same as 2, but the overall CI check should keep out-of-support versions.

My preference is 1 or 2.

**Comment by vishweshbankwar** [comment]
Apologies for being inactive on this. There only two projects that are targeting netcoreapp3.1 
1) `OpenTelemetry.Instrumentation.GrpcCore.Tests`:  [PR](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1084) needs input from owner 
2) OpenTelemetry.Contrib.Instrumentation.AWS.Tests:  @Kielek Is there a reason we cannot change this one? I see you updated for `OpenTelemetry.Instrumentation.AWSLambda.Tests`. Sorry, If I missed some update.

**Comment by Kielek** [comment]
1. Grpc.Core should be deprecated. I would consider doing the same for this package. @pcwiese, what do you think?
2. As I remember, there are two differnet group of package owners so I decided to split it into two separate PRs. I do not have enough free time to make a follow up.

**Comment by pcwiese** [comment]
I'm fine with deprecation. This was a temporary package for our team until we moved to grpc dotnet. We still have users of this package however but they can simply use current versions.Sent from my iPhoneOn Jun 19, 2023, at 22:19, Piotr Kiełkowicz ***@***.***> wrote:﻿

Grpc.Core should be deprecated. I would consider doing the same for this package. @pcwiese, what do you think?
As I remember, there are two differnet group of package owners so I decided to split it into two separate PRs. I do not have enough free time to make a follow up.

**Comment by utpilla** [comment]
As part of working on this issue, the code should be updated to get rid of preprocessor directive checks based on netcoreapp: https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-dotnet-contrib%20%23if%20NETCOREAPP&type=code
