### ISSUE TITLE
Traces are not sent to XRay

### ISSUE THREAD

**Issue by egnwd** [open-telemetry/opentelemetry-dotnet-contrib#1035]
# Bug Report

## Symptom

Using the open telemetry libraries I am unable to see additional segments and spans from traces for my Lambda function running dotnet.

**Describe the bug**

I am running dotnet6 lambdas with active tracing enabled and full Xray IAM permissions (for now).
I can see some traces coming through to XRay with very basic `Invocation` and `Overhead` segments of the trace (which I believe is coming from enabling Active tracing).
This proves to me that at least Xray is configured and my Lambda has permissions to write to XRay.
I cannot see any of the additional segments I would expect to see from having added the open telemetry config, e.g. Http tracing, custom spans from AcitivitySource.

<details>
    <summary>My collector config is as follows:</summary>

```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: eu-west-1

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,awsxray]
```
</details>

<details>
    <summary>My dotnet set up is as follows:</summary>

```csharp
        services.AddOpenTelemetry()
            .WithTracing(builder =>
            {
                const string serviceName = "test";
                builder
                    .AddXRayTraceId()
                    .SetSampler(new AlwaysOnSampler())
                    .AddSource(serviceName)
                    .AddConsoleExporter()
                    .SetResourceBuilder(ResourceBuilder
                        .CreateDefault()
                        .AddDetector(new AWSLambdaResourceDetector())
                        .AddService(serviceName))
                    .AddHttpClientInstrumentation()
                    .AddAWSInstrumentation()
                    .AddAspNetCoreInstrumentation();
            });

        Sdk.SetDefaultTextMapPropagator(new AWSXRayPropagator());
```
</details>

<details>
    <summary>Example log from the logging exporter:</summary>

```
Activity.TraceId:            63f7332c64818f7ced20d7ea3f0622c6
--
Activity.SpanId:             41dac0348116dcd5
Activity.TraceFlags:         Recorded
Activity.ParentSpanId:       0000000000000000
Activity.ActivitySourceName: OpenTelemetry.Instrumentation.AspNetCore
Activity.DisplayName:        api/v1/status
Activity.Kind:               Server
Activity.StartTime:          2023-02-23T09:34:36.2863860Z
Activity.Duration:           00:00:00.0001296
Activity.Tags:
net.host.name: xxxxxxxxxx.execute-api.eu-west-1.amazonaws.com
http.method: GET
http.scheme: https
http.target: /test/api/v1/status
http.url: https://xxxxxxxxxx.execute-api.eu-west-1.amazonaws.com/test/api/v1/status
http.user_agent: Amazon-Route53-Health-Check-Service (ref c1988c4e-3c76-4f47-8398-3c9f2a810b1a; report http://amzn.to/1vsZADi)
http.route: api/v1/status
http.status_code: 204
Resource associated with Activity:
service.name: test
service.instance.id: 3887804f-08d4-421e-b7b1-3ae2462bd78c
cloud.provider: aws
cloud.platform: aws_lambda
cloud.region: eu-west-1
faas.name: test
faas.version: $LATEST
```
</details>

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/2790386/220872258-f1561b48-dc8b-4873-bff0-0e2c616a9e7e.png)

Screenshot of the two segments in the Trace.
Top: AWS::Lambda
Bottom 3: AWS::Lambda::Function, Invocation, Overhead

**Runtime environment (please complete the following information):**

- OpenTelemetry Automatic Instrumentation version: [e.g. 1.0.0]
- OS: AWS Linux 2
- .NET version: dotnet 6

**Additional context**

## Reproduce

1. Create default dotnet6 lambda with ASPNetCore set up with basic controller endpoint
2. Add collector config above
3. Add startup config above
4. Add Xray IAM permissions and active tracing
5. call the endpoint (if using API gateway or mock it using lambda input for apigateway proxy requests)

**Comment by Kielek** [comment]
Moving issue from auto-instrumentation to contrib repository.
Based on description not related to instrumentation.

@srprash, @Oberon00 could you please check?

**Comment by Oberon00** [comment]
> I cannot see any of the additional segments I would expect to see from having added the open telemetry config, e.g. Http tracing, custom spans from AcitivitySource.

I see two issues:
* Are you using the AWS Lambda instrumentation? If not, are you calling ForceFlush manually? Otherwise, it can happen that the export is still running when the Lambda is suspended after the request.
* You seem to only call `.AddConsoleExporter()`. Then you only get console export. If you want to export to your collector (which you have posted a config file of), configure an appropriate exporter (e.g. OTLP). There does not seem to be a direct XRay exporter available for .NET

**Comment by egnwd** [comment]
> There does not seem to be a direct XRay exporter available for .NET

My mistake, I misunderstood the role of the `Sdk.SetDefaultTextMapPropagator(new AWSXRayPropagator());`

I'll try this out

> AWS Lambda instrumentation

Is this a different library? I added the detector, `.AddDetector(new AWSLambdaResourceDetector())`. I will look into the ForceFlush thank you.

**Comment by egnwd** [comment]
Ah excellent - adding the OLTP exporter seems to be enough.

However that gives me a brand new trace, rather than connecting it to the Lambda's trace. @Oberon00 Is this intentional default behaviour or would there be additional configuration in order to link the two?

**Comment by Oberon00** [comment]
You would need to extract the X-Ray parent from the incoming lambda request. This is something that the Trace/TraceAsync method of the AWS Lambda instrumentation can do for you. Note that this instrumentation library is only semi-automatic, you need to call wrapper functions yourself, see the README: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.AWSLambda

**Comment by egnwd** [comment]
Perfect - thanks for the response. I'll close this issue as my issue is resolved.... and I'll go read the manual 😀
