### ISSUE TITLE
Publish new version of OpenTelemetry.Extensions

### ISSUE THREAD

**Issue by trejjam** [open-telemetry/opentelemetry-dotnet-contrib#1045]
# Issue with OpenTelemetry.Extensions

Hello, is it possible to publish a new version of `OpenTelemetry.Extensions`? Compatible with 1.4.0?
Thank you

**Comment by Kielek** [comment]
@trejjam, see https://github.com/open-telemetry/opentelemetry-dotnet-contrib/releases/tag/Extensions-1.0.0-beta.4
