### ISSUE TITLE
Consider removing `net452` target from the package

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/opentelemetry-dotnet-contrib#1078]
# Issue with OpenTelemetry.Contrib.Instrumentation.AWS
The package currently targets `net452` which is a non-supported version. Consider updating it to latest supported version i.e. `net462`.

## Additional Context
This issue is opened as part of #1031 effort

**Comment by vishweshbankwar** [comment]
@srprash - Could you please take a look?

**Comment by srprash** [comment]
@vishweshbankwar I am okay with bumping up the supported framework to net462, but I think it should be done as a new major version since it is a breaking change. 

Maybe we should cut a new branch to maintain the current major version and track the new major version in the `main` branch?

@utpilla @Kielek Any suggested strategy for moving a project to a new major version in this repo?

**Comment by vishweshbankwar** [comment]
@srprash Removing Un-supported versions does not need major version bump. OTel Sdk has done that in the past https://github.com/open-telemetry/opentelemetry-dotnet/pull/3191

**Comment by srprash** [comment]
I see. I need some clarity though. Suppose a net452 application user has pinned this package as 
```
<PackageReference Include="OpenTelemetry.Contrib.Instrumentation.AWS" Version="[1.0.1,2.0.0)" />
```

Wouldn't dropping net452 in a non-major version break their application when they try to build it?

**Comment by cijothomas** [comment]
> I see. I need some clarity though. Suppose a net452 application user has pinned this package as
> 
> ```
> <PackageReference Include="OpenTelemetry.Contrib.Instrumentation.AWS" Version="[1.0.1,2.0.0)" />
> ```
> 
> Wouldn't dropping net452 in a non-major version break their application when they try to build it?

Not necessarily. It was done many times in the core Otel packages: (https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/CHANGELOG.md#120-alpha1) where it was generally agreed that dropping a target runtime (that is already out-of-support) can be done *without* major version bump.

**Comment by Kielek** [comment]
It should be safe together with renaming package. Removing Contrib infix. No chance to accidentally reference thus version.
