### ISSUE TITLE
Missing opentelemetry.contrib nupkg's on nuget.org that support OTEL 1.x

### ISSUE THREAD

**Issue by bravecobra** [open-telemetry/opentelemetry-dotnet-contrib#109]
Seems we are still missing 3 published contrib packages on nuget.org that support OTEL 1.x

- EntityFrameworkCore
- Masstransit
- Stackdriver

I know the publish step is a manual step, so can someone please publish them, provided they are in working order of course?

**Comment by bravecobra** [comment]
@cijothomas Am I correct in assuming that you're in charge of publishing the packages to nuget.org?

**Comment by cijothomas** [comment]
Both EF and MT **require** 1.1 of the core packages. So there won't be a version of these packages built with core 1.0. I'll be doing pre-releases of them this week.

**Comment by cijothomas** [comment]
MT is released to nuget.

**Comment by bravecobra** [comment]
> I'll be doing pre-releases of them this week.
I don't mind using beta packages for short while, once they are available. That way they get tested by a larger audience as well. What's missing to get the publishing automated, based on either branching or tagging?

**Comment by ElectricVampire** [comment]
@cijothomas Can you also release EF nuget as well.
I think EF Opentelemetry nuget should be part of main repo as mostly all user who is adopting OpenTelemetry .net nuget are going to use this one if they have DB other than MS-SQL

**Comment by cijothomas** [comment]
@ElectricVampire EF instrumentation requires another change before release. I attempted it here( https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/107/files), will continue it. The main goal is to have EF instrumentation depend only on the API, and not on the SDK.

All instrumentations would eventually be in the contrib repo only. (the current ones in main were added before contrib repo was created) Main repo will only host mostly spec-mandated things (so SDK and spec required exporters) and anything else which are deemed necessary.

**Comment by maneskul** [comment]
Hey guys, any predictions for Stackdriver package be updated on nugets?

**Comment by cijothomas** [comment]
> Hey guys, any predictions for Stackdriver package be updated on nuget?

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Contrib.Exporter.Stackdriver#traces I am unsure if the Stackdriver code is ready to be released. Please open a separate issue to discuss the status of StackDriver

All other packages are released, so closing this issue.
