### ISSUE TITLE
Breaking change in 1.4: TableNameMapping doesn't allow table name to start with lowercase character

### ISSUE THREAD

**Issue by dpk83** [open-telemetry/opentelemetry-dotnet-contrib#1105]
# Issue with OpenTelemetry.Exporter.Geneva

OpenTelemetry.Exporter.Geneva 1.4.0

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x ] Bug

**What is the expected behavior?**
Geneva supports table names that starts with lowercase characters, so a table name that starts with lowercase character should work.

What do you expect to see?
When I pass a table name that starts with lowercase characters in TableNameMapping i.e. `myTable`, then it should work.

**What is the actual behavior?**
Exporter throws when table name provided in TableNameMapping starts with lowercase character.

This is a breaking change because the logs can not be sent to existing tables which were being used prior to 1.4 release. Moving logs to new table breaks the user experience

options.TableNameMapping = new Dictionary<string, string>
{
     ["Example.DefaultService"] = "myTableName"
};

This doesn't work and throws. Was working with 1.3 release.

## Additional Context

Add any other context about the feature request here.

**Comment by cijothomas** [comment]
@utpilla Please take a look. Thanks.

**Comment by CodeBlanch** [comment]
@dpk83 FYI [GenevaExporter v1.4.1 available on NuGet now with a fix for this](https://www.nuget.org/packages/OpenTelemetry.Exporter.Geneva/1.4.1).

**Comment by dpk83** [comment]
Great. Thanks!
