### ISSUE TITLE
EFCore nuget package seems to not be up to date

### ISSUE THREAD

**Issue by magnayn** [open-telemetry/opentelemetry-dotnet-contrib#111]
I get
```[CS7069] Reference to type 'TracerProviderBuilder' claims it is defined in 'OpenTelemetry', but it could not be found```

(OpenTelemetry 1.1.0-beta2 as that's required for aspnetcore lib).

**Comment by xyq175com** [comment]
I want to help with this, but really not sure what the issue  it is as i checked in my local when typed the 'TraceProviderBuilder', there is no error found

**Comment by Kielek** [comment]
Closing. The latest release is working fine with OTel 1.5.0.
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md#100-beta7
