### ISSUE TITLE
[Instrumentation.Cassandra] Document produced metrics

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-contrib#1125]
# Issue with OpenTelemetry.Instrumentation.Cassandra

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

* OpenTelemetry.Instrumentation.Cassandra 1.0.0-beta.1 (and current main),

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

* N/A

**Is this a feature request or a bug?**

* [x] Feature Request
* [ ] Bug

**What is the expected behavior?**

Extend documentation with list of supported metrics. Similar to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/57adc16022cf23ee34e52586e4ae3ec0836bf6e8/src/OpenTelemetry.Instrumentation.AspNet#list-of-metrics-produced

**Comment by Kielek** [comment]
@xsoheilalizadeh, FYI

**Comment by Kielek** [comment]
@xsoheilalizadeh any chance that you create PR to cover this?

**Comment by xsoheilalizadeh** [comment]
@Kielek Sorry for delay, I'll take care of it until next week.
