### ISSUE TITLE
Deprecate OpenTelemetry.Extensions.Docker on NuGet

### ISSUE THREAD

**Issue by iskiselev** [open-telemetry/opentelemetry-dotnet-contrib#1137]
As OpenTelemetry.Extensions.Docker has been renamed to OpenTelemetry.ResourceDetectors.Container, somebody with proper rights should deprecate old package and update new package as alternative, to guide users with migration path.
The process is described at https://learn.microsoft.com/en-us/nuget/nuget-org/deprecate-packages

**Comment by iskiselev** [comment]
@Kielek , do you know who can help with old package deprecation?

**Comment by Kielek** [comment]
I do not have this priviliges yet, probably @utpilla or @cijothomas can handle this topic.

Related issue: #1100

**Comment by utpilla** [comment]
I have deprecated the ` OpenTelemetry.Extensions.Docker` packages.
