### ISSUE TITLE
Span Reported as error in Dynatrace

### ISSUE THREAD

**Issue by srinivasmalla** [open-telemetry/opentelemetry-dotnet-contrib#1147]
# Issue with OpenTelemetry.Instrumentation.AspNetCore 

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

* TBD

Runtime version (`netcoreapp3.1'):

* TBD

**Is this a feature request or a bug?**

* [ ] Bug

**What is the expected behavior?** 
The Span should be reported in the Dynatrace traces logs

What do you expect to see? 
The Span should be reported in the Dynatrace traces logs

**What is the actual behavior?** 
In the Trace it is showing as "Span Reported as Error in Dynatrace"

What did you see instead? If you are reporting a bug, create a self-contained
project using the template of your choice and apply the minimum required code to
result in the issue you're observing. We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

The below code is placed in Startup.cs class in ConfigureServices method

services.AddOpenTelemetryTracing((builder) => builder
                .SetSampler(new AlwaysOnSampler())
                .AddSource(activitySource)
                .SetResourceBuilder(ResourceBuilder.CreateEmpty().AddAttributes(dt_metadata).AddService("dotnet-Dynatracetest")) 
                .AddAspNetCoreInstrumentation()
                .AddOtlpExporter(otlpOptions =>
                {
                    
                    otlpOptions.Endpoint = new Uri("https://testserver.live.dynatrace.com/api/v2/otlp/v1/traces");

                    otlpOptions.Protocol = OtlpExportProtocol.HttpProtobuf;
                    otlpOptions.Headers = "Authorization=Api-Token MyToken";

                })) ;
				
The below code is placed one of the Controller 
 //Defines the OpenTelemetry Instrumentation Scope.
        private const string activitySource = "MyCompany.MyProduct.MyLibrary";
 //Provides the API for starting/stopping activities.
        private static readonly ActivitySource MyActivitySource = new ActivitySource(activitySource);
	using var activity = MyActivitySource.StartActivity("my-span", ActivityKind.Consumer, parentContext.ActivityContext);

Add any other context about the feature request here.

**Comment by pellared** [comment]
1. Can you please cleanup the description? Or close the issue?
2. Is this a bug of `OpenTelemetry.Instrumentation.AspNetCore`? I do not see any repro steps that would create an error span created by the instrumentation library.
3. `OpenTelemetry.Instrumentation.AspNetCore` lives in https://github.com/open-telemetry/opentelemetry-dotnet

**Comment by Kielek** [comment]
@srinivasmalla, we are not able to help you with data provided in the description. If you still need help, please provide data described in @pellared comment.
