### ISSUE TITLE
Leaving 'SuppressDownstreamInstrumentation' as 'true' (default) breaks request telemetry

### ISSUE THREAD

**Issue by julealgon** [open-telemetry/opentelemetry-dotnet-contrib#1153]
# Issue with OpenTelemetry.Instrumentation.Wcf

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

OpenTelemetry.Exporter.OpenTelemetryProtocol  v1.4.0
OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs  v1.4.0-rc.4
OpenTelemetry.Extensions.Hosting v1.4.0
OpenTelemetry.Instrumentation.AspNetCore v1.0.0-rc9.14
OpenTelemetry.Instrumentation.Runtime v1.0.0
OpenTelemetry.Instrumentation.Wcf v1.0.0-rc.9

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

NET6.0

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

I expected to see all my traces and logs associated with the request.

**What is the actual behavior?**

As soon as the first request is made using the instrumented WCF client, all other child scopes and logs are not propagated, and only the initiating scope is finished. 

Traces and logs without overriding `SuppressDownstreamInstrumentation` (true):

![image](https://user-images.githubusercontent.com/461579/233142282-fab6e086-4856-4b47-b866-0717077a87be.png)

Traces and logs with explicit `.AddWcfInstrumentation(c => c.SuppressDownstreamInstrumentation = false)`:

![image](https://user-images.githubusercontent.com/461579/233142531-8b968c0f-b021-4158-b6f0-349a764539f0.png)

I don't currently have a shareable repro project for this but the behavior is clearly linked to the instrumentation suppression logic. 

## Additional Context

I realized something was deeply wrong when I noticed even my logs were not being propagated after the first SOAP call. I could see that removing the WCF instrumentation would immediately change it and logs were working fine, then enabling WCF would only send whatever happened before the first SOAP call.

It then occurred to me to try disabling the suppression and it just worked... suddenly, everything was there again: all the missing logs, as well as all the other SOAP calls (we do several SOAP calls on the same request.

Additionally, all SOAP calls are `async`. The reason I mention that is because I saw there is an issue open that appears to be related to the fact that the calls are async:
- https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/812

**Comment by Kielek** [comment]
@CodeBlanch, FYI, as you are component owner.
