### ISSUE TITLE
[Instrumentation.MySqlData] is not working with MySQL.Data 8.0.33

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-contrib#1157]
# Issue with OpenTelemetry.Instrumentation.MySqlData

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

* OpenTelemetry.Instrumentation.MySqlData 1.0.0-beta.6 also current main (eccfe8a6c1b4a5cb5710680bbe721914a2ee145e)

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

* net7.0, net6.0, probably also other

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

Activities/Spans created as for 8.0.32.1 version

**What is the actual behavior?**

No Activities/Span.

Just execute application test from https://github.com/Kielek/opentelemetry-dotnet-instrumentation/commit/95c191b5d68bf1b591f50fe3041f6178c92e6239 with mysql avaialbe for port 3306.
It can be used to test also with older versions by modyfying csproj.

## Additional Context

Found by https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2478

**Comment by Kielek** [comment]
@moonheart, could you please check?

**Comment by moonheart** [comment]
I'll check this now.

**Comment by moonheart** [comment]
`Activity.Current` uses `AsyncLocal` to store current activity.

Before this commit, command executes on one thread:
``` csharp
        public Task<int> ExecuteQueryAsync()
        {
            OpenQuery();
            var r = Execute();
            CloseQuery();
            return Task.FromResult(r);
        }

        public void OpenQuery()
        {
            // Activity created here
        }
        public int Execute()
        {
            return 1;
        }

        public void CloseQuery()
        {
            // Activity can be retrieved from here
        }
```
Activity can be retrieved because it's synchronous, no context switch happened.

After this commit, the code is asynchronous all the way:
``` csharp
        public async Task<int> ExecuteQueryAsync()
        {
            await OpenQueryAsync();
            var r = await ExecuteAsync();
            await CloseQueryAsync();
            return r;
        }

        public async Task OpenQueryAsync()
        {
            // Activity created here
        }
        public async Task<int> ExecuteAsync()
        {
            return 1;
        }

        public async Task CloseQueryAsync()
        {
            // Activity can not be retrieved from here 
        }

```
Activity can not be retrieved because when it leaved `OpenQuery` method, `ExecutionContext `was restored to default, and the Activity was lost.

I haven't get a good idea to get around this yet, maybe someone can help. Or the problem does not exist and my usage is wrong.

**Comment by t03apt** [comment]
MySql Instrumentation stopped working at MySql.Data@8.0.31.
I created a related issue in opentelemetry-dotnet repository: [OpenTelemetry.Instrumentation.MySqlData stopped working at MySql.Data@8.0.31 #4643](https://github.com/open-telemetry/opentelemetry-dotnet/issues/4643)
I created a small sample app that I used to reproduce the issue: https://github.com/t03apt/MySqlDataInstrumentationIssues
I noticed that MySqlDataInstrumentation.TraceEvent is not getting fired with MySql.Data@8.0.31 or newer packages.

**Comment by moonheart** [comment]
Hello @t03apt, I'm sorry for the delayed responses. Have you managed to resolve the issue you mentioned? I couldn't find the repository you posted. Instrumentation should be functional prior to version 8.0.33. Regarding the current issue in version 8.0.33, I have submitted a feature request in the MySQL bug tracker, but it appears that there hasn't been any activity on it yet.

**Comment by t03apt** [comment]
Hi @moonheart,
Thanks for looking at it! Sorry, my repository was private by mistake. I changed it to public. I hope you can see it now.
Instrumentation doesn’t work with 8.0.31 either.
Could you share the MySQL feature request?

**Comment by moonheart** [comment]
@t03apt Hi, I've reviewed your repository and noticed that the generated connection string, `Server=127.0.0.1;Port=32773;Database=mysql;Uid=mysql;Pwd=mysql`, doesn't match the requirements mentioned in the [document](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.MySqlData/README.md).
> Note If you are using Mysql.Data 8.0.31 or later, please add option Logging=true in your connection string to enable tracing. See issue #691 for details.

After adding this option, the instrumentation is working as expected.

**Comment by t03apt** [comment]
@moonheart Wow. I missed that. Thanks!

**Comment by Kielek** [comment]
Closing issue per last comment.
