### ISSUE TITLE
[Geneva] DateTime in env_properties are not serialized properly

### ISSUE THREAD

**Issue by vidommet** [open-telemetry/opentelemetry-dotnet-contrib#1162]
# Issue with OpenTelemetry.Exporter.Geneva

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

    <PackageReference Include="OpenTelemetry.Exporter.Geneva" Version="1.4.1" />

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

	net6.0

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

Proper serialization of DateTime if not in custom fields. (part of env_properties)

**What is the actual behavior?**

Output is `EXT(type:-1,size:12)`

## Additional Context

DateTime serialization works as expected if using custom columns but doesn't work if using env_properties.

Consider `logger.LogInformation("Test {body}", DateTime.UtcNow);`

This works if using 

    lo.AddGenevaLogExporter(c =>
    {
        c.ConnectionString = "EtwSession=OpenTelemetry";
    });

But doesn't if using

    lo.AddGenevaLogExporter(c =>
    {
        c.CustomFields = Array.Empty<string>();
        c.ConnectionString = "EtwSession=OpenTelemetry";
    });

**Comment by chenxinyanc** [comment]
I'm observing similar issue and found this thread gets closed. Is there any suggestion except from explicitly setting the `CustomFields`? We don't want to expand our custom dimensions into a lot of columns in Geneva, so we'd prefer leveraging `env_properties` to collect them together into 1 column. However, We found that `DateTime` could not be serialized properly in the same fashion as this issue has described.

**Comment by zhongyehong** [comment]
Hey @utpilla @chenxinyanc , would like to know any update on this? We are facing the same issues, can we configure to avoid this? Thank you so much

**Comment by utpilla** [comment]
> Is there any suggestion except from explicitly setting the CustomFields?

@chenxinyanc @zhongyehong You could call [`.ToString()`](https://learn.microsoft.com/dotnet/api/system.datetime.tostring?view=net-9.0) on the `DateTime` field while logging.
