### ISSUE TITLE
Measurement dropped error.  Suggested action: 'Contact SDK owners.'

### ISSUE THREAD

**Issue by rohitkumar07** [open-telemetry/opentelemetry-dotnet-contrib#1165]
# Issue that does not fit into other categories

**What are you trying to achieve?**
Understand the root cause of this error message from `EventWrittenEventArgs`

```
info: OpenTelemetry
      Measurement dropped from Instrument Name/Metric Stream Name '***'. Reason: 'SDK internal error occurred.
'. Suggested action: 'Contact SDK owners.'
```

What do you expect to see?
Expect a resolution on how to make these measurement dropped errors not occur.

**Additional context.**

App version: net7.0
Instrument Type: Counter<int>
Error message coming from the EventListener callback: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlistener?view=net-7.0 , captured from OpenTelemetry SDK: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Internal/OpenTelemetrySdkEventSource.cs#L233

Add any other context about the problem here. If you followed an existing
documentation, please share the link to it.
The error might be coming from here - https://github.com/open-telemetry/opentelemetry-dotnet/blob/3884bee5f244aec4da6aa5b961b0495583f7831d/src/OpenTelemetry/Metrics/AggregatorStore.cs#L353

**Comment by rohitkumar07** [comment]
The issue occurs sporadically, few times a day and it's difficult to reproduce. We only see this in a fraction of applications/situations. 

The MeterProvider is setup as part of the application startup process.

```
            var builder = Sdk.CreateMeterProviderBuilder()
                .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService(
                    serviceName: _applicationContext.ApplicationName,
                    serviceVersion: _applicationContext.ApplicationVersion,
                    serviceInstanceId: _applicationContext.ApplicationInstance))
                .AddMeter("regex of supported meters")
                .SetMaxMetricPointsPerMetricStream(2000)
                .SetMaxMetricStreams(1000);

       _meterProvider = builder.Build();
```

The counter metric is being emitted as 

```
public static readonly Meter Meter = new Meter("<meter-name>", Assembly.GetExecutingAssembly().GetName().Version.ToString());

private static readonly Counter<int> XYZCounter = Meter.CreateCounter<int>("<Counter-name>", "Count");

XYZCounter .Add(countABC, new KeyValuePair<string, object>("tag1", val1), new KeyValuePair<string, object>("tag2", val2));

```

**Comment by cijothomas** [comment]
Can you share the .NET runtime version and the pacakges list+version as well?

**Comment by rohitkumar07** [comment]
.NET runtime version of the app emitting the counter is net7.0

packages list/versions: (an internal nuget package with targetframework `netstandard2.0` is used for otel exports in the apps)
```

		<PackageReference Include="OpenTelemetry" Version="[1.3.1, 2)" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="[1.3.1, 2)" />
```

**Comment by cijothomas** [comment]
Have seen something like this for .NET Core 3.1, but since you are in .NET 7.0, that can be ruled out.
The next best thing I can think of is to move to 1.4.0 from 1.3.1. ( can't remember if we had any issues, but want to rule out as much as possible, given we dont have an easy repro!)

**Comment by rohitkumar07** [comment]
Thanks, will upgrade the OTel SDK version and see how it goes. 

Is it possible to add more visibility into the exception by providing more context here - https://github.com/open-telemetry/opentelemetry-dotnet/blob/3884bee5f244aec4da6aa5b961b0495583f7831d/src/OpenTelemetry/Metrics/AggregatorStore.cs#L353

**Comment by Kielek** [comment]
@rohitkumar07, do you have any updates? Is the issue occurs after upgrade to 1.4.0 (or even better 1.5.1)?

**Comment by rohitkumar07** [comment]
Thanks for the update on 1.5.1 - we haven't got a chance to update it yet will update this thread as soon as we do.

**Comment by Kielek** [comment]
@rohitkumar07, do you have any updates?

**Comment by Kielek** [comment]
@rohitkumar07, I am closing as there is no response from your side.
