### ISSUE TITLE
The documentation is not updated and it points to two different packages.

### ISSUE THREAD

**Issue by Rishabh-V** [open-telemetry/opentelemetry-dotnet-contrib#1167]
# Issue with OpenTelemetry.Exporter.Stackdriver documentation
**Is this a feature request or a bug?**

* Bug

**What is the expected behavior?**
The documentation should point to `OpenTelemetry.Exporter.Stackdriver` package only

**What is the actual behavior?**
While the steps at the top of the page point to the `Stackdriver` package which seems to match the source code for `OpenTelemetry.Exporter.Stackdriver`, the Installation section mentions a package with different name, that has incompatibilities with most of the latest Google cloud libraries, which results in confusion and it appears that this exporter is broken.

```
dotnet add package OpenTelemetry.Contrib.Instrumentation.Stackdriver --prerelease
```
Additional question, given that Stackdriver is an old name, do we plan to change this to GoogleCloudTrace or something similar?

**Comment by Kielek** [comment]
Documentation will be fixed in #1168.

The package is still before stable release we can technically do this. If you would like to contribute, please create dedicated issue and ask @SergeyKanzhelev - component owner - for the opinion.

Thanks for reporting it!
