### ISSUE TITLE
Nuget Missing

### ISSUE THREAD

**Issue by vasicvuk** [open-telemetry/opentelemetry-dotnet-contrib#1173]
# Issue with OpenTelemetry.Extensions.Enrichment

**What type of request is this?**

* [ ] Feature Request
* [X] Bug
* [ ] Question

## Request Details

There is no NuGet on NuGet.org

**What is the expected behavior?**

To have Nuget

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Extensions.Enrichment/CHANGELOG.md is work in progress. 

Once the owners deem it ready for a release, it can be done with the process here : https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md#how-to-request-for-release-of-package
