### ISSUE TITLE
My 'name' field override by geneva exporter

### ISSUE THREAD

**Issue by chinazhangchao** [open-telemetry/opentelemetry-dotnet-contrib#1186]
# Issue with OpenTelemetry.Exporter.Geneva

OpenTelemetry.Exporter.Geneva(1.4.0)

**Is this a feature request or a bug?**

* [ ] Feature Request
* [X] Bug

**What is the expected behavior?**
My old tables have a field whose name is 'name', and when I used OpenTelemetry.Exporter.Geneva package, I noticed the sdk write a filed also named 'name'. This led to my 'name' field was override. And I haven't found any solution to disable sdk writing the field. Could you please provide some options to control whether to write the field?
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/9e3fe44908af7af867fecbf42cb543fc4893c440/src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackLogExporter.cs#L257

**What do you expect to see?**
My 'name' field wasn't override.

**What is the actual behavior?**
My 'name' field was override.

**Comment by utpilla** [comment]
This is By-Design. `name` field is reserved for serializing `LogRecord.CategoryName` by GenevaLogExporter.

**Comment by jdom** [comment]
I'm also hitting this same issue. We are transitioning from a legacy infrastructure to OpenTelemetry with the Geneva exporter, and we must maintain backwards compatibility (as we have a 200+ partner teams ecosystem, as well as a lot of alerting already set up). This field being overwritten is our only blocker to complete that migration.
