### ISSUE TITLE
Support for Multiple GenevaMetricExporter Instances in the Same Application Process

### ISSUE THREAD

**Issue by semiprogarlic** [open-telemetry/opentelemetry-dotnet-contrib#1192]
ArgumentException: An instance of EventSource with Guid edc24920-e004-40f6-a8e1-0e6e48f39d84 already exists.

`ArgumentException callstack:
[2023-05-15 03:31:11.270][2955870712706238] at System.Diagnostics.Tracing.EventSource.EnsureDescriptorsInitialized()
[2023-05-15 03:31:11.270][2955870712706238] at System.Diagnostics.Tracing.EventSource.DoCommand(EventCommandEventArgs commandArgs)
[2023-05-15 03:31:11.270][2955870712706238] at System.Diagnostics.Tracing.EventSource.Initialize(Guid eventSourceGuid, String eventSourceName, String[] traits)
[2023-05-15 03:31:11.270][2955870712706238] at System.Diagnostics.Tracing.EventSource..ctor(EventSourceSettings settings, String[] traits)
[2023-05-15 03:31:11.270][2955870712706238] at OpenTelemetry.Exporter.Geneva.GenevaMetricExporter..ctor(GenevaMetricExporterOptions options)
[2023-05-15 03:31:11.270][2955870712706238] at OpenTelemetry.Exporter.Geneva.GenevaMetricExporterExtensions.AddGenevaMetricExporter(MeterProviderBuilder builder, GenevaMetricExporterOptions options, Action`1 configure)`

Description:
I would like to request support for having multiple GenevaMetricExporter instances within the same application process in order to enhance the flexibility and scalability of monitoring and exporting metrics using the Geneva Metrics library.

Currently, the GenevaMetrics library allows for a single GenevaMetricExporter instance per application process. This limitation restricts the ability to monitor and export metrics from different components or subsystems independently, especially in complex applications with multiple modules or microservices.

Having the ability to create and manage multiple GenevaMetricExporter instances would enable finer-grained control over metric collection and export, facilitating the following use cases:

Independent metric monitoring: Different components or subsystems within an application may have distinct monitoring requirements. By supporting multiple GenevaMetricExporter instances, developers can define separate exporters for each component and monitor metrics independently, tailoring the configuration, filters, and destinations for each exporter.

Customized export destinations: Different exporters may require exporting metrics to distinct destinations, such as different monitoring systems or data storage solutions. With support for multiple GenevaMetricExporter instances, developers can configure each exporter to export metrics to the appropriate destination, providing flexibility and integration options.

Scalability and performance: In scenarios where an application requires high throughput or handles a large number of metrics, having multiple GenevaMetricExporter instances can help distribute the load across different exporters, improving performance and ensuring efficient resource utilization.

By implementing support for multiple GenevaMetricExporter instances, developers will be able to design more modular and flexible monitoring solutions, adapting to the specific requirements of their applications.

I believe that enabling this functionality would greatly enhance the Geneva Metrics library and provide developers with a powerful toolset for effective monitoring and exporting of metrics.

**Comment by utpilla** [comment]
@semiprogarlic Could you share the .NET runtime version that you're using?

**Comment by semiprogarlic** [comment]
Version:   6.0.406
 Commit:    2988897946

Runtime Environment:
 OS Version:  10.0.22621
