### ISSUE TITLE
Elasticsearch db.statement and db.url tags contain authentication details.

### ISSUE THREAD

**Issue by niemyjski** [open-telemetry/opentelemetry-dotnet-contrib#1194]
# Issue with OpenTelemetry.Instrumentation.ElasticsearchClient

`db.statement` and `db.url` contains an http link that is authenticated `https://user:pass@host/....`

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

* 1.4.0 RTM all other packages.
* OpenTelemetry.Instrumentation.ElasticsearchClient 1.0.0-beta4

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

* net6.0

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

I'd expect user and passwords to be redacted.

**What is the actual behavior?**

I see the http url contain both user name and password.

**Comment by Kielek** [comment]
@ejsmith, could you please check?

**Comment by cpunella** [comment]
good morning... any news or ETA for this fix? 

Thanks

**Comment by ejsmith** [comment]
Sorry, I haven't made this change yet. It's a pretty simple change, could you add a PR for it?

**Comment by Kielek** [comment]
Alternative approach is to use opentelemetry collector and redact this tags.

**Comment by ejsmith** [comment]
@Kielek not sure what that means. I think you are saying that if you are using the latest Elasticsearch .NET client (8.0) then you don't need this library.

**Comment by Kielek** [comment]
@ejsmith, I mean this https://opentelemetry.io/docs/collector/transforming-telemetry/

If you have sensitive data in any attribute you can modify your data almost locally before sending it to final store.
