### ISSUE TITLE
Component owners - OpenTelemetry membership status

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-contrib#1201]
From https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md

> The owner should at least be an [OpenTelemetry Member](https://github.com/open-telemetry/community/blob/main/community-membership.md#member) to be eligible to assigned as component owner. This is required to ensure that reviews can be automatically requested from the owners.

For now, our auto-assign PR job is usually not working because of lack of OTel membership.

If you are mentioned below, please consider to create requests https://github.com/open-telemetry/community/issues/new?assignees=&labels=area%2Fgithub-membership&projects=&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E.

I will be happy to support you as a OTel member.

| name              | GH link                              | OTel Member |
|-------------------|--------------------------------------|-------------|
| ~~@atshaw43~~          | https://github.com/atshaw43          | No - temporarry removed from component owner files         |
| cijothomas        | https://github.com/cijothomas        | Yes         |
| codeblanch        | https://github.com/codeblanch        | Yes         |
| ejsmith           | https://github.com/ejsmith           | ~~No~~ Yes          |
| fred2u            | https://github.com/fred2u            | ~~No~~ Yes          |
| hananiel          | https://github.com/hananiel          | Yes         |
| havret            | https://github.com/havret            | ~~No~~ Yes          |
| iskiselev         | https://github.com/iskiselev         | ~~No~~ Yes        |
| maldago           | https://github.com/maldago           | ~~No~~ Yes          |
| mic-max           | https://github.com/mic-max           | Yes         |
| moonheart         | https://github.com/moonheart         | ~~No~~ Yes          |
| Oberon00          | https://github.com/Oberon00          | Yes         |
| pcwiese           | https://github.com/pcwiese           | ~~No~~ Yes          |
| rajkumar-rangaraj | https://github.com/rajkumar-rangaraj | Yes         |
| reyang            | https://github.com/reyang            | Yes         |
| rypdal            | https://github.com/rypdal            | ~~No~~Yes          |
| SergeyKanzhelev   | https://github.com/SergeyKanzhelev   | Yes         |
| srprash           | https://github.com/srprash           | Yes         |
| twenzel           | https://github.com/twenzel           | ~~No~~ Yes       |
| utpilla           | https://github.com/utpilla           | Yes         |
| vishweshbankwar   | https://github.com/vishweshbankwar   | Yes         |
| xakep139          | https://github.com/xakep139          | ~~No~~ Yes          |
| xiang17           | https://github.com/xiang17           | Yes         |
| xsoheilalizadeh   | https://github.com/xsoheilalizadeh   | Yes         |
| Yun-Ting          | https://github.com/Yun-Ting          | Yes         |
| @zivaninstana      | https://github.com/zivaninstana      | ~~No~~ Yes          |

Data based on https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/35e4ca31e7b91d531cbb5bd77443bd7824d62536/.github/component_owners.yml

**Comment by Havret** [comment]
I've put in a request a few days back, but haven't had any luck getting a response yet."

 https://github.com/open-telemetry/community/issues/1498

**Comment by utpilla** [comment]
> If you are mentioned below, please consider to create requests https://github.com/open-telemetry/community/issues/new?assignees=&labels=area%2Fgithub-membership&projects=&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E.
> 
> I will be happy to support you as a OTel member.

I would be willing to support you as well.

**Comment by moonheart** [comment]
@Kielek @utpilla Could you please support me as a OTel member in https://github.com/open-telemetry/community/issues/1502?

**Comment by rypdal** [comment]
@Kielek @utpilla Could you please support me as a OTel member in https://github.com/open-telemetry/community/issues/1518?

**Comment by Kielek** [comment]
@twenzel, sure, please just fill correctly your request - Sponsor section and contribution section

**Comment by utpilla** [comment]
@twenzel I would support. Please list me as one of the sponsors in the issue.

**Comment by xakep139** [comment]
Created a request https://github.com/open-telemetry/community/issues/1527

**Comment by atshaw43** [comment]
@Kielek Please confirm your support.
https://github.com/open-telemetry/community/issues/1629

**Comment by Kielek** [comment]
Closing. All known component owners are now part of OpenTelemetry organization.
