### ISSUE TITLE
AspNet Metrics Instrumentation Enrich & Filter

### ISSUE THREAD

**Issue by ZRich97** [open-telemetry/opentelemetry-dotnet-contrib#1226]
# Issue with OpenTelemetry.Instrumentation.AspNet

Using Open Telemetry's [AspNetCore instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.AspNetCore#metrics), we can automatically generate, enrich, and filter a default `http.server.duration` metric using [AspNetCoreMetricsInstrumentationOptions](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreMetricsInstrumentationOptions.cs) in our .NET Core services. 

Through the similar [AspNet instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.AspNet#metrics) used in .NET Framework services it is possible to emit the `http.server.duration` metric, but the same filtering and enrichment options are not available. Does any mechanism currently exist to attach additional dimensions or apply filtering logic to the auto-instrumented metric in .NET Framework? 

For example, we're able to use the below logic in .NET Core and are aiming to do the same in .NET Framework.
![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/15897453/9b555e58-e246-42f5-b23f-6cb785192a58)

**Is this a feature request or a bug?**

* [x] Feature Request
* [ ] Bug

**What is the expected behavior?**

Parity between .NET Core and .NET Framework metric configuration options.

**What is the actual behavior?**

Currently, .NET Framework services do not have the same ability to enrich and filter the default metrics generated by Open Telemetry instrumentation libraries. .NET Framework services would be limited to the default dimensions and have no ability to filter based on custom logic.

## Additional Context

Pointed here by @cijothomas after initially posting in the opentelemetry-dotnet Discussions board [here](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/4567).

**Comment by Kielek** [comment]
@ZRich97, any chance that you will contribute to create this features?

**Comment by ZRich97** [comment]
> @ZRich97, any chance that you will contribute to create this features?

Originally, I was reaching out to see whether this functionality already existed for .NET Framework or was already in progress/planned. If it isn't, I may be able to look into implementing it.

**Comment by ZRich97** [comment]
@Kielek I've started work on a draft PR to enable this functionality (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1426). As this would be my first contribution to this project, let me know if you have any feedback before I publish the PR.

Also, I noticed that the AspNetCore Instrumentation project removed this functionality in a recent PR due to upcoming .NET 8 features (https://github.com/open-telemetry/opentelemetry-dotnet/pull/4981). Do the enrich and filter features still make sense for the AspNet Instrumentation package, or would they be blocked from merging?

**Comment by ZRich97** [comment]
@Kielek - the changes resolving this issue have been merged but are [unreleased](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md#unreleased). Our team is interested in using the Enrich() feature when it is made available. 

Is there a planned next release for the AspNet package, or should I create a PR requesting one (similar to [this one](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1427))?

**Comment by Kielek** [comment]
Please create the PR

**Comment by ZRich97** [comment]
> Please create the PR

Created PR here: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1505
