### ISSUE TITLE
AspNet Need to Customize Metric and Trace Naming

### ISSUE THREAD

**Issue by jcauv4** [open-telemetry/opentelemetry-dotnet-contrib#1227]
# Issue with OpenTelemetry.Instrumentation.AspNet

    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.5.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.14" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.14" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.5.0" />

Runtime version `net7.0`

**Is this a feature request or a bug?**

* [x] Feature Request
* [ ] Bug

**What is the expected behavior?**
The metrics and traces from open telemetry have a default format that includes the '.' character. For example, the http.server.duration metric has http.route, http.method etc. and in traces there are similar fields in the tags like http.target.

Is there a way to customize the naming of the default metrics and traces? The '.' character is invalid for the query language we export to.

**What do you expect to see?**

Something like this:

```chsharp
services
    .AddOpenTelemetry()
    .ConfigureResource(ConfigureResource)
    .WithMetrics(builder =>
    {
        builder
            .AddRuntimeInstrumentation()
            .AddAspNetCoreInstrumentation()
            .AddHttpClientInstrumentation()
            .SetMetricNameFormatter(new CustomMetricNameFormatter()); // Behavior like this
    });
```

**What is the actual behavior?**
I am not able to find a way to customize the naming of the default metrics and tracing tags.

**Comment by cijothomas** [comment]
There aren't ways to change the name of the attributes. There are ways to change the name of the metric (using Views).
The instrumentation libraries in OpenTelemetry follow OTel conventions (which is to have "."), so the changes must occur downstream (like a otel-collector/ or your backend). 

This could be a feature request for all the instrumentation libraries, not just asp.net!

**Comment by jcauv4** [comment]
Yes, views allows us to customize the naming of metrics, but the metrics still have default dimensions (tags) that I'm unaware of a way to customize.

Same goes for traces. While we can have a processor that changes the names, it's inefficient, as we have to remove the tag/key pair `SetTag(key, null)` and replace it with the renamed tag/key `SetTag(RenamedKey, Value)`.

**Comment by cijothomas** [comment]
I am closing this issue, as we don't plan to add such a one-off capability to asp.net instrumentation.
