### ISSUE TITLE
AddEntityFrameworkCoreInstrumentation not working without AddAspNetCoreInstrumentation

### ISSUE THREAD

**Issue by kurzenkov** [open-telemetry/opentelemetry-dotnet-contrib#1235]
# Issue with OpenTelemetry.Instrumentation.EntityFrameworkCore

OpenTelemetry.Exporter.Console 1.5.0
OpenTelemetry.Exporter.OpenTelemetryProtocol 1.5.0
OpenTelemetry.Instrumetation.AspNetCore 1.5.0
OpenTelemetry.Instrumetation.EntityFrameworkCore 1.0.0-beta.7

* TBD

net6.0

* TBD

**Is this a feature request or a bug?**

 [X] Bug

        using var tracerProvider = Sdk.CreateTracerProviderBuilder()
            .AddEntityFrameworkCoreInstrumentation()
            .AddConsoleExporter()
            .Build();
this code does not output trace information to the console

BUT

        using var tracerProvider = Sdk.CreateTracerProviderBuilder()
            .AddAspNetCoreInstrumentation()
            .AddEntityFrameworkCoreInstrumentation()
            .AddConsoleExporter()
            .Build();
work perfect

what i do wrong ?

**Comment by Kielek** [comment]
You are not doing anything wrong.

There are two important things to consider.
1. ASP.NET Core has built in functionality to generate Activities/Spans.
2. Default Sampler is [ParentBasedSampler](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Trace/ParentBasedSampler.cs) with [AlwaysOnSampler](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Trace/AlwaysOnSampler.cs). It means that if any Acitivity/Span decide to nor record then any child activity will be not recorder.

I suppose your flow looks like

 - HTTP Request
 - Handled by ASP.NET Core.
 - Internally it generates Activity marked to not recording (it is becoming your Activity.Current for further processing)
 - Some more logic
 - Call to EntityFramework Core
 - Based on your Acitivity.Current it is making decision to not record/sample EntityFramework Core.
- real call to DB.

If you will make the same call without ASP.NET Core on top, it will be working fine. You can test it with Console application.

Potential solutions:
 - add ASP.NET Core instrumentation.
 - Change sampler from ParentBaseSampler(AlwaysOnSampler) to AlwaysOnSampler (if you are fine with all other activities in you process).

**Comment by cijothomas** [comment]
see https://github.com/open-telemetry/opentelemetry-dotnet/issues/1217 as well.
