### ISSUE TITLE
WPF Open telemetry tracing Issues

### ISSUE THREAD

**Issue by muneernet** [open-telemetry/opentelemetry-dotnet-contrib#124]
Hi team ,

We have a  WPF application which  connects to Web API  and WCF on the server side . Am not able to add instrumentation to the  WPF client application where as to the WCF and Web API it is working fine. Even though  I have added  open telemetry instrumentation to the WPF application added activities too.  Could you please help me in this regard.

Thanks

**Comment by CodeBlanch** [comment]
@muneernet Would you possibly be able to provide a small repo that reproduces the issue so we can investigate?

**Comment by reyang** [comment]
Close due to lack of response/activity. @muneernet please provide more details and reopen the issue if there is a need.
