### ISSUE TITLE
Parent Activity does not propagate from ASP.NET host to WCF service

### ISSUE THREAD

**Issue by repl-uosis-levandauskas** [open-telemetry/opentelemetry-dotnet-contrib#1243]
# Issue with OpenTelemetry.Instrumentation.Wcf

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

OpenTelemetry -- 1.4.0
OpenTelemetry.Api -- 1.4.0
OpenTelemetry.Api.ProviderBuilderExtensions -- 1.4.0
OpenTelemetry.Contrib.Extensions.AWSXRay -- 1.0.1
OpenTelemetry.Contrib.Instrumentation.AWS -- 1.0.2
OpenTelemetry.Exporter.OpenTelemetryProtocol -- 1.4.0
OpenTelemetry.Instrumentation.AspNet -- 1.0.0-rc9.8
OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule -- 1.0.0-rc9.8
OpenTelemetry.Instrumentation.Http -- 1.0.0-rc9.14
OpenTelemetry.Instrumentation.Wcf -- 1.0.0-rc.9

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

net48

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

When WCF service is hosted by ASP.NET, activity created by WCF instrumentation should be a child of the activity created by ASP.NET instrumentation.

**What is the actual behavior?**

Two independent activities are created.

**Comment by Kielek** [comment]
@repl-uosis-levandauskas , could you please provide code which reproduces the issue?

**Comment by repl-uosis-levandauskas** [comment]
> @repl-uosis-levandauskas , could you please provide code which reproduces the issue?

@Kielek reproduction and a fix here: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1253
