### ISSUE TITLE
connectionMultiplexer added to redisInstrumentation not respect to StackExchangeRedisInstrumentationOptions

### ISSUE THREAD

**Issue by ryji** [open-telemetry/opentelemetry-dotnet-contrib#1252]
# Issue with OpenTelemetry.Instrumentation.StackExchangeRedis

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

```
<PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.5.0" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.5.0" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.0-beta.1" />
<PackageReference Include="OpenTelemetry.Instrumentation.ElasticsearchClient" Version="1.0.0-beta.4" />
<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.0.0-beta.7" />
<PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.0.0-rc9.10" />
<PackageReference Include="StackExchange.Redis" Version="2.6.116" />
```

Runtime version : `net6.0`

**Is this a feature request or a bug?**
[x] Bug

**What is the expected behavior?**

connectionMultiplexer added to redisInstrumentation should respect to StackExchangeRedisInstrumentationOptions.

**What is the actual behavior?**

set verbpseDatabaseStatements And EnrichActivityWithTimingEvents is useless

![image](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/assets/36433890/0f655bc2-794f-4cda-9af3-46d283e5d072)
![image](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/assets/36433890/67801d85-1b3d-45cd-93d7-a784ca441a45)

## Additional Context

Add any other context about the feature request here.
[OTelDemo.zip](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/files/11854214/OTelDemo.zip)

**Comment by lachmatt** [comment]
@ryji
When you call `AddRedisInstrumentation`, you provide callback to configure options, but provide no name to be used for options retrieval, so default name will be used (i.e `Options.DefaultName`). Later, when you add connections to instrumentation, you specify names - an attempt will be made to retrieve options with these names, there aren't any, so default options are used.

**Comment by Kielek** [comment]
@ryji, do you need any further help?
I think @lachmatt response should resolve your issue.

**Comment by Kielek** [comment]
Closing issue. Please let us know if @lachmatt is not sufficient.
