### ISSUE TITLE
Issue with CommonSchemaJsonSerializer [OpenTelemetry.Exporter.OneCollector]

### ISSUE THREAD

**Issue by GeoK** [open-telemetry/opentelemetry-dotnet-contrib#1313]
# Issue with OpenTelemetry.Exporter.OneCollector

**What type of request is this?**

* [ ] Feature Request
* [x] Bug
* [ ] Question

## Request Details

**What are the OpenTelemetry packages and versions you are using?**
 OpenTelemetry.Exporter.OneCollector 1.5.1
System.Diagnostics.DiagnosticSource 7.0.2
OpenTelemetry 1.5.1
OpenTelemetry.Api 1.5.1

**What environment are you using?**

_Please include the runtime versions (e.g. `net462`, `net48`, `net6.0`, `net7.0`
etc.), OS details (e.g.Windows, Linux, etc.), architecture (e.g. 32bit, 64bit,
etc.), and anything else important (e.g. IIS, container, etc.)._
net7.0 Windows 64bit

**What is the expected behavior?**
OneCollector endpoint should be able to parse the data.

**What is the actual behavior?**
OneCollector reject requests with: 

HTTP/1.1 400 All events rejected due to parsing failure.
Collector-Error: All events rejected due to parsing failure.
{"acc":0,"efi":{"InvalidEventFormat":"all"}}

**What are the steps to reproduce the issue?**
Common schema extension in json needs to be used for the issue to manifest.
When [this method](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/cb5b2193ef9cacc0b9ef699e085022577551bf85/src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/LogRecordCommonSchemaJsonSerializer.cs#L183) gets called, an additional nested json node gets added (ext -> dt). I'm guessing that OneCollector can't parse nested 'dt' level and throws an exception.
If I debug through the source code and skip executing [this method](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/cb5b2193ef9cacc0b9ef699e085022577551bf85/src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/LogRecordCommonSchemaJsonSerializer.cs#L183), OneCollector accepts the request.

Not sure if this is a bug or an expected behavior. If it is by-design, a switch to control whether extension data gets appended would help us workaround the issue. Thanks.

**Comment by GeoK** [comment]
Hi @CodeBlanch @Kielek - is this something you can help with?

**Comment by CodeBlanch** [comment]
Update. I checked with the OneCollector team. The issue here is ext_dt_traceFlags is not supported and blows up the parser (extensions are supported and dt is supported but only traceId & spanId).

@GeoK how urgent is this? The owner of the OneCollector logic is out until 8/28 I would like to wait for him to get back so we can discuss whether support should be added in the service (don't know how long that would take) or if SDK should just drop traceFlags (could turn that around pretty quickly).

**Comment by GeoK** [comment]
Thanks for promptly fixing this @CodeBlanch @Kielek.
What is the ETA for the next OneCollector exporter release?
