### ISSUE TITLE
Deprecate Instrumentation.MySqlData

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-contrib#1315]
# Issue with OpenTelemetry.Instrumentation.MySqlData

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

Current main branch.

**Is this a feature request or a bug?**

* ~~[ ] Feature Request~~
* ~~[ ] Bug~~
* [x] Deprecation request

**What is the expected behavior?**

Instrumentation.MySql code package, including ci and other, is removed from the repository.
Deprecation notice is added to CHANGELOG.md, README.md.
Readme on nuget org is also updated.

**What is the actual behavior?**

Current version is not working with MySql.Data 8.0.33. See #1187. There is no reasonable option to fix it.
MySql.Data 8.1.0 brings native support for trace instrumentation.

## Additional Context

It can be registered on tracer builder by 

```csharp
tracerBuilder .AddSource("connector-net"),
```
or by calling this method: https://github.com/mysql/mysql-connector-net/blob/1341887fc28fc3181e9bf65a8dc6534e82b84284/MySQL.Data.OpenTelemetry/src/TraceProviderBuilderExtension.cs

Example of deprecation for MassTransit https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/78598baf6f00d411539be599ed6a53b03bbeb70c/src/OpenTelemetry.Instrumentation.MassTransit

**Comment by Kielek** [comment]
@moonheart, what do you think?

**Comment by moonheart** [comment]
Wow, this is cool! They have finally brought native support to OpenTelemetry! I think We can deprecate Instrumentation.MySqlData now.

**Comment by Kielek** [comment]
Deptecation notice added also to https://www.nuget.org/packages/OpenTelemetry.Instrumentation.MySqlData

**Comment by Kielek** [comment]
@moonheart, thank you fo taking care of this package! You have made great job here.
I hope you will another interesting topic here or in other OpebTelemetry / opeb siource (sub)project.
