### ISSUE TITLE
AWSEBSResourceDetector not working properly if published from Visual Studio

### ISSUE THREAD

**Issue by cricaplaza-netreo** [open-telemetry/opentelemetry-dotnet-contrib#1318]
# Issue with OpenTelemetry.ResourceDetectors.AWS

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

OpenTelemetry.ResourceDetectors.AWS v1.3.0-beta.1

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

net7.0

**Is this a feature request or a bug?**

* [ ] Feature Request
* [X] Bug

**What is the expected behavior?**
It should detect Elastic Beanstalk Resources properly.

What do you expect to see?
Opentelemetry semantic properties for Elastic Beanstalk deployed apps.

**What is the actual behavior?**
No Opentelemetry semantic properties for Elastic Beanstalk deployed apps.

What did you see instead? If you are reporting a bug, create a self-contained
project using the template of your choice and apply the minimum required code to
result in the issue you're observing. We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

Create a dotnet app and instrument with Opentelemetry and deploy to AWS EBS via Visual Studio.

Error encountered:
```
Aug 22 09:23:03 ip-10-100-3-130 web: Custom Detector, error encountered 
{
    "ClassName": "System.IO.FileNotFoundException",
    "Message": "Could not find file '/var/app/current/C:\\Program Files\\Amazon\\XRay\\environment.conf'.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)\n   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)\n   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\n   at ProductCRUD.API.CustomDetector.GetStream(String filePath) in C:\\Users\\crica\\Documents\\personal solutions\\ec2-dotnet7\\src\\ProductCRUD.API\\CustomDetector.cs:line 95\n   at ProductCRUD.API.CustomDetector.DeserializeFromFile[T](String filePath) in C:\\Users\\crica\\Documents\\personal solutions\\ec2-dotnet7\\src\\ProductCRUD.API\\CustomDetector.cs:line 87\n   at ProductCRUD.API.CustomDetector.GetEBSMetadata(String filePath) in C:\\Users\\crica\\Documents\\personal solutions\\ec2-dotnet7\\src\\ProductCRUD.API\\CustomDetector.cs:line 82\n   at ProductCRUD.API.CustomDetector.Detect() in C:\\Users\\crica\\Documents\\personal solutions\\ec2-dotnet7\\src\\ProductCRUD.API\\CustomDetector.cs:line 38",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2147024894,
    "Source": "System.Private.CoreLib",
    "WatsonBuckets": null,
    "FileNotFound_FileName": "/var/app/current/C:\\Program Files\\Amazon\\XRay\\environment.conf",
    "FileNotFound_FusionLog": null
}
```
Created a custom Detector based on your existing code and there's another issue:

 ```
"ActualMessage": "The JSON value could not be converted to System.String. Path: $.deployment_id | LineNumber: 0 | BytePositionInLine: 18."
```

**Comment by Kielek** [comment]
@cricaplaza-netreo, I suppose where is the issue.

See condition, it refers to NETSTANDARD. In fact, project is targeted to net6.0.

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/6bace87f3bcd73f84b27be779c73ab9128da0c2b/src/OpenTelemetry.ResourceDetectors.AWS/AWSEBSResourceDetector.cs#L33

You can locally change `#if NETSTANDARD` to `#if NET6_0_OR_GREATER` in all places in the file.

If it help, please let us know, maybe you could create PR with the fix?

@srprash, FYI.
