### ISSUE TITLE
Add new metrics to the runtime instrumentation

### ISSUE THREAD

**Issue by liustanley** [open-telemetry/opentelemetry-dotnet-contrib#1334]
I noticed that there a number of metrics that are missing from the current runtime instrumentation, and I'd like to request for the following runtime metrics to be added:

CPU System Time - [Process.PrivilegedProcessorTime](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.privilegedprocessortime?view=net-7.0)
CPU User Time - [Process.UserProcessorTime](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.userprocessortime?view=net-7.0#system-diagnostics-process-userprocessortime)
CPU Percentage
Committed Memory - [Process.PrivateMemorySize64](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.privatememorysize64?view=net-7.0#system-diagnostics-process-privatememorysize64)
Thread Pool Workers Count - [ThreadPool.ThreadCount](https://learn.microsoft.com/en-us/dotnet/api/system.threading.threadpool.threadcount?view=net-7.0)
Thread Contention Time
GC Memory Load
GC Pause Time

ASPNetCore Total Requests - [total-requests](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters#microsoftaspnetcorehosting-counters)
ASPNetCore Requests Failed - [failed-requests](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters#microsoftaspnetcorehosting-counters)
ASPNetCore Current Requests - [current-requests](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters#microsoftaspnetcorehosting-counters)
ASPNetCore Request Queue Length - [request-queue-length](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters#microsoft-aspnetcore-server-kestrel-counters)
ASPNetCore Current Connections - [current-connections](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters#microsoft-aspnetcore-server-kestrel-counters)
ASPNetCore Total Connections - [total-connections](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters#microsoft-aspnetcore-server-kestrel-counters)
ASPNetCore Connection Queue Length - [connection-queue-length](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters#microsoft-aspnetcore-server-kestrel-counters)

**Comment by Kielek** [comment]
ASP.NET Core metrics for sure do not the runtime project.
Consider https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/README.md#list-of-metrics-produced
or fully separate package for it (most of them are probably does not have OTel-spec defitnitions).

**Comment by xiang17** [comment]
Hi, please see [Process Instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Process) for process-related metrics, like CPU time metrics and process memory.

Runtime instrumentation gives metrics about .NET runtime behavior.

* Thread Pool Workers Count: we already have [process.runtime.dotnet.thread_pool.threads.count](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Runtime#processruntimedotnetthread_poolthreadscount), which uses ThreadPool.ThreadCount API (Ctrl+F in the page for "ThreadPool.ThreadCount" for description).
* Thread Contention Time: we have a similar metrics [process.runtime.dotnet.monitor.lock_contention.count](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Runtime#processruntimedotnetmonitorlock_contentioncount). Does this meet your need?
* GC Memory Load: Can you elaborate more on this? We have a bunch of GC memory and GC heap related metrics.
* GC Pause Time: We have [gc.duration](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Runtime#processruntimedotnetgcduration). This might be what you're looking for.

For the ones which are similar but don't meet your exact needs, can you elaborate more on the use case where only they can provide the best benefits?
