### ISSUE TITLE
How to configure AttachLogsToActivityEvent behaviour

### ISSUE THREAD

**Issue by dgarciarubio** [open-telemetry/opentelemetry-dotnet-contrib#134]
I'm trying to use the preview feature **AttachLogsToActivityEvent** mentioned in the corresponding [readme](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Contrib.Preview).

I have checked the examples left by @CodeBlanch in PR #114 and managed to get the logging working in an ASP.Net Core project.
However I don't know how to configure it so that the message, state or scope information is logged. This is my configuration:

Program.cs:
```
Host.CreateDefaultBuilder(args)
    .ConfigureLogging(builder =>
    {
        builder.AddOpenTelemetry(options => options.AttachLogsToActivityEvent(options => {
            options.ScopeConverter = (tags, depth, scope) =>
            {
                //Breakpoints won't get hit here
            };
            options.StateConverter = (tags, state) =>
            {
                //Breakpoints won't get hit here
            };
        }));
    })
    .ConfigureWebHostDefaults(builder => builder.UseStartup<Startup>());
```

Startup.cs:
```
services.AddOpenTelemetryTracing(builder =>
{
    builder
        .AddAspNetCoreInstrumentation()
        .AddConsoleExporter();
});
```

This is what is logged from a controller:
```
    log [06/10/2021 14:51:57 +00:00]
        CategoryName: Controller
        LogLevel: Information
```

Any idea about how to configure the state/scope/message logging? It would be useful to document it somewhere (if its already documented, maybe we could reference it from the [readme](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Contrib.Preview) file).

**Comment by CodeBlanch** [comment]
There are a few flags on [OpenTelemetryLoggerOptions](https://github.com/open-telemetry/opentelemetry-dotnet/blob/f987ac856d14bc0fb95f154c7f1aa72cd8aa4f2b/src/OpenTelemetry/Logs/OpenTelemetryLoggerOptions.cs#L24) that you need to set:

```csharp
builder.AddOpenTelemetry(options =>
{
   options.IncludeScopes = true;
   options.ParseStateValues = true;
   options.IncludeFormattedMessage = true;
   options.AddActivityEventAttachingLogProcessor();
});
```

**Comment by dgarciarubio** [comment]
Yeah, this definitely solves the issue. I thought this would be custom parameters for this feature, so I wouldn't think of searching for them in that options object. Thanks for the help, I'll close the issue.

**Comment by sanjaydebnath** [comment]
@CodeBlanch @dgarciarubio This seems not working in .net7 minimal APIs. Any tip you have to fix this below issue?

https://github.com/open-telemetry/opentelemetry-dotnet/issues/4052
