### ISSUE TITLE
Exporter.Geneva support for exponential histograms

### ISSUE THREAD

**Issue by specialforest** [open-telemetry/opentelemetry-dotnet-contrib#1378]
# Issue with OpenTelemetry.Exporter.Geneva

**Is this a feature request or a bug?**

* [x] Feature Request
* [ ] Bug

**What is the expected behavior?**
Exporter.Geneva works with exponential histograms.

**What is the actual behavior?**
Exporter.Geneva ignores exponential histograms.

**Comment by vishweshbankwar** [comment]
@specialforest This feature is currently in the pipeline; however, there is no ETA at the moment. Will share the updates once there is progress.

**Comment by vishweshbankwar** [comment]
FYI - this feature depends on https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1585.

**Comment by vishweshbankwar** [comment]
Re-opening this to track support as part of #1585
