### ISSUE TITLE
Using OpenTelemetry.Instrumentation.AWS in production apps

### ISSUE THREAD

**Issue by ssathasivanACR** [open-telemetry/opentelemetry-dotnet-contrib#1379]
# Issue with OpenTelemetry.Instrumentation.AWS

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

OpenTelemetry.Instrumentation.AWS version 1.1.0-beta.1+

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

* net6.0

**Is this a feature request or a bug?**
* [ ] Feature request
* [ ] Bug

**What is the expected behavior?**

What do you expect to see?

**What is the actual behavior?**

## Additional Context

We are trying to use Dynatrace for observability of our .NET Lambdas. Dynatrace uses OpenTelemetry.Instrumentation.AWSLambda version 1.2.0-beta.1+ and  OpenTelemetry.Instrumentation.AWS version 1.1.0-beta.1+ to monitor AWS Lambda invocations.  Since these libraries are in pre-release, is it safe to use them for production apps.

**Comment by DanielLaberge** [comment]
We're also interested in using the 1.1x release.

**Comment by birojnayak** [comment]
@DanielLaberge @ssathasivanACR These libraries are stable, so should be safe to use.

I am working with semantic-convention team to ensure if there are any major changes from cloud providers.. if there are I am going to work with my internal team to fix those and bring to OTEl*.AWS.* packages and we will have a GA afterwards. 

Presently this is my top-priority.

**Comment by martinjt** [comment]
This is all due to Semantic conventions (the naming of the attributes and what must be included). There will be stable releases when those relevant semantic conventions are stable.
