### ISSUE TITLE
Add support for multiple namespaces

### ISSUE THREAD

**Issue by minkom-ms** [open-telemetry/opentelemetry-dotnet-contrib#1380]
# Issue with OpenTelemetry.Exporter.Geneva

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

R9 1.33.0

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

net7.0

**Is this a feature request or a bug?**

* [x] Feature Request
* [ ] Bug

**What is the expected behavior?**

API should allow routing metrics to different namespaces.

**What is the actual behavior?**

At the moment all metrics are exported to the default namespace.

## Additional Context

N/A

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md#150-alpha2 This is supported from 1.5.*. Please check the changelog, which has link to PR showing example code. Thanks!
