### ISSUE TITLE
OpenTelemetry Client instrumentation is not working with .NET Framework 4.6.2 and OWIN

### ISSUE THREAD

**Issue by trivikso** [open-telemetry/opentelemetry-dotnet-contrib#1410]
# Issue with OpenTelemetry.Instrumentation.Owin

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

"OpenTelemetry.Instrumentation.Owin" Version="1.0.0-rc.3"
"OpenTelemetry" Version="1.6.0" 
"OpenTelemetry.Api" Version="1.6.0" 
"OpenTelemetry.Exporter.Geneva" Version="1.6.0"
"OpenTelemetry.Exporter.Console" Version="1.6.0"
"OpenTelemetry.Instrumentation.Owin" Version="1.0.0-rc.3" 
"OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.14"

* TBD

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

net462

* TBD

**Is this a feature request or a bug?**

* [ ] Feature Request
* [*] Bug

**What is the expected behavior?**
Service with HttpClientInstrumentation enabled should have Client response headers with TraceId and SpanId
What do you expect to see?
Client response headers have TraceId and SpanId

**What is the actual behavior?**
Client response headers doesnt have TraceId and SpanId

What did you see instead? Setting ParentTraceId in the request, i can see they are going to Service but response doesnt have any TraceId or SpanId. 

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

We have followed these steps to enable OTel with OWIN [opentelemetry-dotnet-contrib/examples/owin/Program.cs at main · open-telemetry/opentelemetry-dotnet-contrib · GitHub](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/examples/owin/Program.cs) 
 
            httpConfiguration.MessageHandlers.Add(new ActivityDisplayNameRouteEnrichingHandler());
            tracerProvider = Sdk.CreateTracerProviderBuilder()
            .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("Owin-Example"))
            .AddOwinInstrumentation()
            .AddHttpClientInstrumentation()
            .AddAspNetCoreInstrumentation()
            .Build();
 
              app.UseOpenTelemetry();
 
To test OTel, we are testing using PowerShell and i can see the TraceId and SpanId going to Service but done see it in response. Below is the PowerShell snippet we are using
 
$traceId = [System.Guid]::NewGuid().ToString("N")
$spanId = [System.Guid]::NewGuid().ToString("N").Substring(0, 16)
$traceparent = "00-$traceId-$spanId-01"
$response = Invoke-WebRequest -Uri http://localhost:$portNumber/logCollectionjobhistory/$d -Method Get  -ContentType 'application/json' -UseDefaultCredentials -UseBasicParsing -Headers @{"traceparent" = $traceparent}
 
PS C:\WINDOWS\system32> $response.Headers
 
Key                         Value
---                         -----
x-ms-correlation-request-id 6b1061dc-2429-4375-a817-6547c0d8cbcf
Content-Length              7895
Content-Type                application/json; charset=utf-8
Date                        Tue, 24 Oct 2023 19:12:57 GMT
Server                      Microsoft-HTTPAPI/2.0
WWW-Authenticate            oRswGaADCgEAoxIEEAEAAADT4uMs9mBJWQAAAAA=
 
Could you please check if i am missing anything? Thanks.

**Comment by Kielek** [comment]
@trivikso, propagation should work from the client to the server not the opposite.

So if your client (powershell) is calling server (owin) you should see your client traceid as parent for server traces.

Specification for propagating (instrumenting) clients is still under discussion: https://github.com/open-telemetry/opentelemetry-specification/issues/2734

**Comment by trivikso** [comment]
Thanks @Kielek. So in C# Client, we need to set the TraceId/SpanId explicitly in the headers or does it take automatically?

**Comment by Kielek** [comment]
I am not sure if I understand you question.
If you want to propagate from client (python in your case) to server (OWIN) you have to set traceparent header. You can do it manually (like you desceibed) or by [Python OTel](https://github.com/open-telemetry/opentelemetry-python/blob/d054dff47d2da663a39b9656d106c3d15f344269/opentelemetry-api/src/opentelemetry/trace/propagation/tracecontext.py).

Reading header response and checking tracestate (or any other header) is currently not a OTel standard so it will be your custom solutions, probably not compatible with OTel ecosystem.

**Comment by Kielek** [comment]
@trivikso, I am closing the issue. Do not see anything to fix.
