### ISSUE TITLE
WCF TelemetryEndpointBehavior does not implement IServiceBehavior

### ISSUE THREAD

**Issue by pmario71** [open-telemetry/opentelemetry-dotnet-contrib#142]
Tried to configure TelemetryEndpointBehavior by default by referencing it in my machine.config's <commonBehaviors> section.

This fails because TelemetryEndpointBehavior does not implement IServiceBehavior interface.

Implementing it is pretty straight forward and did not create any side effects so far. 
Could create a pull request if there are no concerns that I missed.

**Comment by Jaans** [comment]
+1 We too need this. 
Our framework configures WCF services at the service implementation class level. This is a .NET Framework only use case.
Will submit a PR shortly.
