### ISSUE TITLE
What is the ETA to release Stable versions of Libraries?

### ISSUE THREAD

**Issue by vaibhavjainTM** [open-telemetry/opentelemetry-dotnet-contrib#1428]
Some of the OTel libraries are still in beta version.

OpenTelemetry.Instrumentation.AspNet
OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule
OpenTelemetry.Instrumentation.AspNetCore
OpenTelemetry.Instrumentation.Http
OpenTelemetry.Instrumentation.Process
OpenTelemetry.Instrumentation.SqlClient
OpenTelemetry.PersistentStorage.Abstractions
OpenTelemetry.PersistentStorage.FileSystem
All above libraries are beta only. When you are planning to release stable versions of these libraries?

**Comment by Kielek** [comment]
4 days ago semantic convention for HTTP was released: https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.23.0
It allows us to start working on stabilization for
OpenTelemetry.Instrumentation.AspNet
OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule
OpenTelemetry.Instrumentation.AspNetCore
OpenTelemetry.Instrumentation.Http

As I know sem-conv for other instrumentation is still unstable, so we cannot release it as GA.

There is no ETA for release GA for these packages. We are open for the contribution to adjust current state to the stable version of sem-conv.
