### ISSUE TITLE
Stackdriver Exporter Out of Date

### ISSUE THREAD

**Issue by sailorgallifrey** [open-telemetry/opentelemetry-dotnet-contrib#144]
The version available in Nuget for Stackdriver Exporter is out of date `0.6.0-beta` It does appear that it has been updated to `1.1.0-beta4` in the master branch. Could this be deployed to Nuget?

This is resulting in the following error when trying to build with newer versions of OpenTelemetry .net
[CS7069] Reference to type 'TracerProviderBuilder' claims it is defined in 'OpenTelemetry', but it could not be found

**Comment by sailorgallifrey** [comment]
Are there any plans to set up CI for this?

**Comment by sailorgallifrey** [comment]
I just looked at actions. Looks like you're already on it. :)
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/.github/workflows/package-Exporter.Stackdriver.yml

**Comment by SebastianStehle** [comment]
Hi,
any update on this. Can I help with something?

**Comment by sailorgallifrey** [comment]
Any update on getting the updated version of the Stackdriver exporter deployed to Nuget?

**Comment by sailorgallifrey** [comment]
@vishweshbankwar @cijothomas 
It looks like you guys have been pretty active lately. This has been setting for a while and I was wondering if it would be something you could help with or direct me to someone who can? Thank you!

**Comment by cijothomas** [comment]
https://www.nuget.org/packages/OpenTelemetry.Contrib.Exporter.Stackdriver/0.6.0-beta -- is this the package that needs an updated release?

**Comment by sailorgallifrey** [comment]
@cijothomas correct. It appears code has been merged into master that update the Stackdriver exporter to support `1.1.0-beta` the action just hasn't run to deploy it to nuget yet.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Contrib.Exporter.Stackdriver/CHANGELOG.md could you send a PR to update changelog from "Unreleased" to "1.0.0-beta1".

**Comment by sailorgallifrey** [comment]
@cijothomas Thanks I'll do that. I wasn't sure how the releases were controlled.
Just to confirm should it be `1.0.0-beta1` or `1.1.0-beta1` in the notes for the update it indicates it is updated to support `1.1.0-beta1`

```
* Updated OTel SDK package version to 1.1.0-beta1
  ([#100](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/100))
  ```

**Comment by sailorgallifrey** [comment]
@cijothomas now that it's merged will the pipeline run automatically?

**Comment by cijothomas** [comment]
> @cijothomas now that it's merged will the pipeline run automatically?

No. One of the maintainers has to kick-off the pipeline by pushing git tags. I'll be doing it today for this and another one @vishweshbankwar asked for. (There is no established process for -contrib repo, so if you have spare cycles, we could use help formalizing them.. @vishweshbankwar also offered some help here... )

**Comment by sailorgallifrey** [comment]
@cijothomas Ok that sounds good. I'll go ahead and close this issue.

I wouldn't mind helping out with stuff in the contrib repo and have some spare time to do so.

**Comment by cijothomas** [comment]
https://www.nuget.org/packages/OpenTelemetry.Contrib.Exporter.Stackdriver/1.0.0-beta1 - Please check and validate.

**Comment by cijothomas** [comment]
> @cijothomas Ok that sounds good. I'll go ahead and close this issue.
> 
> I wouldn't mind helping out with stuff in the contrib repo and have some spare time to do so.

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md Update this doc to ask new contributors to list themselves in the https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CODEOWNERS file. 

Also borrow from https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.github/workflows/component-owners.yml and https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.github/workflows/component-owners.yml to ensure the owners get notified. (currently they don't as they are not an approver/maintainer for this repo)
