### ISSUE TITLE
OpenTelemetry.Instrumentation.Runtime: start up error method not found ObservableUpDownCounter

### ISSUE THREAD

**Issue by Abdulsamirkhan** [open-telemetry/opentelemetry-dotnet-contrib#1445]
on startup function started getting below error without any changes to code just after new build with existing code(was working fine before the new build)
Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. OpenTelemetry.Instrumentation.Runtime: The type initializer for 'OpenTelemetry.Instrumentation.Runtime.RuntimeMetrics' threw an exception. OpenTelemetry.Instrumentation.Runtime: Method not found: 'System.Diagnostics.Metrics.ObservableUpDownCounter`1<!!0> System.Diagnostics.Metrics.Meter.CreateObservableUpDownCounter(System.String, System.Func`1<!!0>, System.String, System.String)'.

- OpenTelemetry Automatic Instrumentation version: 1.5.1
- Azure function runtime 4
-  .NET version: 6.0

Detailed error : 

Microsoft.Azure.WebJobs.Script.ExternalStartupException : Error configuring services in an external startup class. ---> System.TypeInitializationException : The type initializer for 'OpenTelemetry.Instrumentation.Runtime.RuntimeMetrics' threw an exception. ---> System.MissingMethodException : Method not found: 'System.Diagnostics.Metrics.ObservableUpDownCounter`1<!!0> System.Diagnostics.Metrics.Meter.CreateObservableUpDownCounter(System.String, System.Func`1<!!0>, System.String, System.String)'. at OpenTelemetry.Instrumentation.Runtime.RuntimeMetrics..cctor() End of inner exception at OpenTelemetry.Metrics.MeterProviderBuilderExtensions.AddRuntimeInstrumentation(MeterProviderBuilder builder,Action`1 configure)

**Comment by Kielek** [comment]
@mada-vidyasagar, I have transferred issue to https://github.com/open-telemetry/opentelemetry-dotnet-contrib. It better fits there as you are not using auto instrumentation.

**Comment by Yun-Ting** [comment]
@mada-vidyasagar, could you try running your code outside of the Azure Function environment to see whether the issue persists?

**Comment by Kielek** [comment]
@Abdulsamirkhan, @mada-vidyasagar, do you need any further help? Were you able to solve the issue?

**Comment by Kielek** [comment]
Closing. Feel free to open/create new issue if needed.
