### ISSUE TITLE
Prefix Service name in MetricTransformerProcessor for all Metrics

### ISSUE THREAD

**Issue by TRAD-Anthony-CKO** [open-telemetry/opentelemetry-dotnet-contrib#1447]
# Issue that does not fit into other categories

**What are you trying to achieve?**
* It is common to prefix metrics names with the service name that is sending them.
* MetricTransformerProcessor supports static prefixing but didn't find any mention about attribute based support. [Readme](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor)

What do you expect to see?
* `CustomAPI` is pushing a Metric with name: "test"
* OTEL Collector exporting it as `customapi.test` 

**Additional context.**
* This change reduces the blast radius of inadvertent changes on metric properties on the providers interfaces.  

Add any other context about the problem here. If you followed an existing
documentation, please share the link to it.

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor
[Documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor)

**Comment by vishweshbankwar** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1448#issuecomment-1915724929
