### ISSUE TITLE
Remove a list of Attributes with AttributesProcessor or MetricTransformProcessor

### ISSUE THREAD

**Issue by TRAD-Anthony-CKO** [open-telemetry/opentelemetry-dotnet-contrib#1448]
# Issue that does not fit into other categories

**What are you trying to achieve?**
* For cases when Attributes are used as tags, having high cardinality attributes leads to generating tons of metrics.
* Having the option to restrict and auto-remove some tags when present from All Metrics with the OTEL collector would help mitigate that.
* Searched within MetricTransformProcessor and [AttributesProcessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor), but didn't seem to find a way do delete those attributes.

**What do you expect to see?**
* `TestApplication` exporting metrics with attribute `number` with value `1`.
* OTEL collector removing all `number` attributes and the metric without it.

**Additional context.**

Add any other context about the problem here. If you followed an existing
documentation, please share the link to it.
[AttributesProcessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor)

**Comment by vishweshbankwar** [comment]
@TRAD-Anthony-CKO Did you intent to open the issue here https://github.com/open-telemetry/opentelemetry-collector-contrib?
Not clear how is it related to dotnet. I am closing this. Please provide more details if it relates to dotnet.
