### ISSUE TITLE
Question regarding System.Runtime as an event source

### ISSUE THREAD

**Issue by agreentree-dmc** [open-telemetry/opentelemetry-dotnet-contrib#1455]
# Issue with OpenTelemetry.Instrumentation.EventCounters

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

Azure.Monitor.OpenTelemetry.AspNetCore, Version="1.0.0-beta.8"
OpenTelemetry.Exporter.Prometheus.AspNetCore, Version="1.7.0-alpha.1"
OpenTelemetry.Extensions.Hosting, Version="1.7.0-alpha.1"
OpenTelemetry.Instrumentation.EventCounters", Version="1.5.1-alpha.1"

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

net8.0

**Is this a feature request or a bug?**
* [X] Question
* [ ] Feature Request
* [ ] Bug

**What is the actual behavior?**
When trying to add 'System.Runtime' as an event source. I receive the error "Use the `OpenTelemetry.Instrumentation.Runtime` or `OpenTelemetry.Instrumentation.Process` instrumentations.".

**Question**
I understand this to be a check that is asserted in the `AddEventSources`  method of the `EventCountersInstrumentationOptions` class, but I was hoping clarity could be provided into why that is. The `OpenTelemetry.Instrumentation.Runtime` and `OpenTelemetry.Instrumentation.Process` libraries provide helpful but not identical metrics (i.e. cpu time and count vs. cpu usage). In order to export metrics in a way consistent with existing graphing capabilities we have on our application - I was interested in exporting the System.Runtime EventCounters exactly as they are which lead me to try the "System.Runtime" as an event source. I'm looking to better understand why that should not be used as an event source.
Thank you.

**Comment by cijothomas** [comment]
`OpenTelemetry.Instrumentation.EventCounters` is still a pre-release package (no one is actively working to make it stable, as far as I can tell), so expect some bumpy ride with that. The idea for this error message was that, Runtime metrics can be obtained in a much better way using other instrumentation libraries. It is possible that some of the metrics are only available in newer .NET versions... _Could you list the exact name of the metric you_ are trying to find using EventCounter approach? It maybe possible to get it using alternate mechanism...

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Process#processcputime Would this help? 
The CPU utilization is calculatable, and https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Process#step-2-enable-process-instrumentation has instructions on how to do it via Grafana.

**Comment by agreentree-dmc** [comment]
@cijothomas Thank you for the links - yes, I think we will need to calculate from CPU time and count.
