### ISSUE TITLE
Release Hangfire instrumentation with OTel v1.6.0?

### ISSUE THREAD

**Issue by gao-artur** [open-telemetry/opentelemetry-dotnet-contrib#1500]
I would like to release Hangfire instrumentation to get these changes: #1440, #1442.
Unfortunately, this repo was already updated to use OTel v1.7.0 #1486.
And OTel v1.7.0 was updated to use `Microsoft.Extensions.*` packages v8.0.0. https://github.com/open-telemetry/opentelemetry-dotnet/pull/5020 + https://github.com/open-telemetry/opentelemetry-dotnet/pull/5015

Unfortunately, we are not ready yet for .NET 8, and this dependency causes errors like this (we are using nuget CPM)

> NU1109	Detected package downgrade: Microsoft.Extensions.Hosting.Abstractions from 8.0.0 to centrally defined 7.0.0. Update the centrally managed package version to a higher version. 

Is it possible to downgrade the `OpenTelemetry.Api.ProviderBuilderExtensions` dependency in Hangfire instrumentation to 1.6.0 to create a compatible release?

And in general, this strategy of taking the latest versions of external packages sounds problematic to me. It leaves a lot of clients behind with old versions.

**Comment by Kielek** [comment]
In this case, you do not need to update .NET SDK/runtime. It should be safe to just upgrade [`Microsoft.Extensions.Hosting.Abstractions`](https://www.nuget.org/packages/Microsoft.Extensions.Hosting.Abstractions/8.0.0#supportedframeworks-body-tab) package ans still target .NET7.

IMO it should be fine to release package with older version if upgrading package will be not an option . @fred2u, what do you think?

**Comment by gao-artur** [comment]
Theoretically, you are right. Practically, it means starting the dependency hell. We are trying to keep SDK, runtime, and packages versions aligned to make sure everything is compatible and tested together. Also, it's not only `Hosting.Abstractions`. There are more, which means cascading updates of many dependencies, every one of which can bring new bugs. When updating OTel packages, I expect it to affect only OTel, but not configuration binding, for example. Lastly, when we need to add another MS package, we know exactly what version to use. Upgrading only part of the dependencies to v8.0 will make it less obvious, as any new dependency can cause additional cascade updates.

I'll open a corresponding issue in the main OTel repo to discuss this. In this issue, I only want to get the Hangfire release with a lower dependency version. I'll be happy to create a PR with a downgraded OTel version and another one to restore it.

**Comment by Kielek** [comment]
@gao-artur, please do it. I suppose that @fred2u will agree on this.

Please remember about updating/reverting changelog.

**Comment by gao-artur** [comment]
Relevant discussion in [opentelemetry-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/5191) repo.
