### ISSUE TITLE
[documentation] Describe how to use resource detectors for all signals

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-contrib#1509]
# Issue that does not fit into other categories

**What are you trying to achieve?**

> Please mention that Resource can be applied to all signals, and if feasible show them each here. Or mention that "while Resource can be applied to all signals, this particular snippet is showing how to add for tracing signal".

_Originally posted by @cijothomas in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1506#discussion_r1432922740_

This applys for all resource detector packages.

**Comment by cijothomas** [comment]
Related adjustments in the main repo : https://github.com/open-telemetry/opentelemetry-dotnet/pull/5188
