### ISSUE TITLE
[Docs] Difficult understanding how Disabling AWS Xray Context Extraction affects tracing

### ISSUE THREAD

**Issue by felipetofoli** [open-telemetry/opentelemetry-dotnet-contrib#1511]
# Issue with OpenTelemetry.Instrumentation.AWSLambda

List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

* Not Applicable

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

* Not Applicable

**Is this a feature request or a bug?**

* [ ] Feature Request
* [ ] Bug
* [x] Documentation enhancement

## Context

I had difficult to understand how disabling the AWS XRay Context Extraction affects tracing, and especially to understand that I should disable it when XRay tracing is not active in the AWS Lambda configurations.

Fortunately, I found this [comment](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/231#issuecomment-1638277476) that helped me to understand the actual behavior that would prevent the code from being traced, and how to configure it in the correct way.

I would like to propose complemeting the documentation, to prevent people from losing time around this configuration (as I did).
Also, the existence of this [thread](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/231) shows that other people already faced the same doubt around this implementation.

**Comment by felipetofoli** [comment]
I propose this following PR: #1512 

Any feedback is more than welcome! 😃 
Thank you very much!

**Comment by Kielek** [comment]
@rypdal, @Oberon00 FYI

**Comment by Kielek** [comment]
Closing per #1512
