### ISSUE TITLE
Geneva metric exporter disposes shared transport object

### ISSUE THREAD

**Issue by xakep139** [open-telemetry/opentelemetry-dotnet-contrib#1520]
# Issue with OpenTelemetry.Exporter.Geneva

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

`OpenTelemetry.Exporter.Geneva` - 1.7.0 (the same issue happens with 1.6.0)

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

`net8.0`

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

Consider this repro:
```csharp
using OpenTelemetry;
using OpenTelemetry.Exporter.Geneva;
using OpenTelemetry.Metrics;
using System.Diagnostics.Metrics;

await EmitMetrics("one");
await EmitMetrics("two");

static async Task EmitMetrics(string attempt)
{
	using var meterProvider = Sdk.CreateMeterProviderBuilder()
		.AddMeter("*")
		.AddGenevaMetricExporter(x =>
		{
			x.MetricExportIntervalMilliseconds = 1000;
			x.ConnectionString = "Account=OTelGeneva;Namespace=MeteringSample";
		})
		.Build();

	using var meter = new Meter("GenevaMetricExporterBug");

	meter.CreateCounter<long>("counter_" + attempt)
		.Add(1);

	// Give the exporter some time to send the metrics
	await Task.Delay(2000).ConfigureAwait(false);
}
```

This is expected to emit metrics in both calls.

**What is the actual behavior?**

Second time metrics aren't emitted via Geneva exporter (works just fine with Console exporter though).

What did you see instead? If you are reporting a bug, create a self-contained
project using the template of your choice and apply the minimum required code to
result in the issue you're observing. We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

Geneva metric exporter [uses](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/Exporter.Geneva-1.6.0/src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs#L90) `Shared` instance for the transport and later [disposes](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/Exporter.Geneva-1.6.0/src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs#L284) its value in `metricDataTransport` field.

If this issue isn't fixed, at least would be great to have an option to control the behavior (e.g. a flag to disable shared instance).

**Comment by xakep139** [comment]
cc @klauco @dariusclay @iliar-turdushev @omsoftdev

**Comment by xakep139** [comment]
@cijothomas @CodeBlanch FYI

**Comment by xiang17** [comment]
I could reproduce the issue. Your explanation in Additional Context is correct. I did a quick experiment to comment out the dispose code in the second link, it would work as expected.

The shared instance mechanism was introduced in #1225 to avoid creating multiple instances of ETW EventSource on the same Guid. However, in this case, if any reference of the shared object disposes the shared object, all other existing and future references will be pointing to the disposed object.

**Comment by xakep139** [comment]
Thanks for taking a look at this @xiang17. Any chance this is fixed (or at least can be controlled via the options)?

**Comment by xakep139** [comment]
Thanks @xiang17 for fixing this!
