### ISSUE TITLE
Getting rid of Newtonsoft.Json dependency in OpenTelemetry.Instrumentation.AWSLambda

### ISSUE THREAD

**Issue by birojnayak** [open-telemetry/opentelemetry-dotnet-contrib#1523]
This is not a bug but future direction for all AWS libraries those are part of Opentelemetry. We would like to make them AOT compatible

While investigating, OpenTelemetry.Instrumentation.AWSLambda takes dependency on Newtonsoft.Json. Are there any restriction on using System.Text.Json/JsonSerializer.Deserialize ? If not, let me know happy to submit PR.

```C#
                // AWSMessagingUtils , GetSnsMessage
                //snsMessage = JsonConvert.DeserializeObject<SNSEvent.SNSMessage>(body);
                snsMessage = JsonSerializer.Deserialize<SNSEvent.SNSMessage>(body);
```

**Comment by birojnayak** [comment]
@rypdal @Oberon00 ^^ thought on above

**Comment by Oberon00** [comment]
Originally we used Newtonsoft because we wanted to support older .NET versions. But I had once already prepared a PR to remove the Newtonsoft depdendency: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1270
