### ISSUE TITLE
CorrelationVector in GenevaExporter

### ISSUE THREAD

**Issue by siimonchoi** [open-telemetry/opentelemetry-dotnet-contrib#1526]
# Issue with OpenTelemetry.Exporter.Geneva

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using (e.g. `OpenTelemetry 1.3.2`):

[OpenTelemetry.Exporter.Geneva 1.7.0](https://www.nuget.org/packages/OpenTelemetry.Exporter.Geneva/1.7.0)

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

`net6.0`

**Is this a feature request or a bug?**

* [ x] Feature Request
* [ ] Bug

**What is the expected behavior?**

I'd like to see if there is a way for GenevaExporter to handle Correlation Vector as a first party citizen similar to how it handles `env_dt_traceId` and `env_dt_spanId`.

What do you expect to see?

I am not sure what would be the best way to persist the cV data through to GenevaExporter but currently we are having to add a `cV` as a custom field and add a processor to to add it to the stateValues from Activity:

``` csharp
builder.AddOpenTelemetry(loggerOptions =>
{
    loggerOptions.AddProcessor(new CorrelationVectorProcessor());

    loggerOptions.AddGenevaLogExporter(exporterOptions =>
    {
        //...
        exporterOptions.CustomFields = new List<string>() { "cV" };
        //....
    });
});
````

```csharp
public class CorrelationVectorProcessor : BaseProcessor<LogRecord>
{
    public override void OnEnd(LogRecord data)
    {
        var cvTag = Activity.Current?.GetTagItem("CV");
        if (cvTag == null) { return; }

        if (data.State != null)
        {
            data.StateValues = data.State as IReadOnlyList<KeyValuePair<string, object>>;
            data.State = null;
        }

        data.StateValues = new List<KeyValuePair<string, object>>(
            data.StateValues ?? Array.Empty<KeyValuePair<string, object>>())
            {
                new("cV", cvTag)
            };

        base.OnEnd(data);
    }
}
```

**What is the actual behavior?**

There is no support for correlation vector and needs to be added as a custom field.

## Additional Context

Add any other context about the feature request here.

**Comment by cijothomas** [comment]
Can you add Cv to ILogger scopes, and that will be automatically exported (once scopes feature is enabled)

**Comment by vishweshbankwar** [comment]
`env_dt_traceId` and `env_dt_spanId` are treated specially as they are required part A fields for spans. 
For any custom context information that you need, you would have to write your plugin to capture the information. Geneva Exporter will not handle such special cases.

**Comment by vishweshbankwar** [comment]
closing this. See details in the comment above.
