### ISSUE TITLE
Can't use Beta-1 in a ASP.NET WebForms app.

### ISSUE THREAD

**Issue by matthewDDennis** [open-telemetry/opentelemetry-dotnet-contrib#1535]
# Issue with OpenTelemetry.Instrumentation.AspNet

Version 1.7.0.-Beta.1

Runtime version `net48`, 
**Is this a feature request or a bug?**

* [ ] Feature Request
* [X ] Bug

I am attempting to use the Nuget package in an ASP.NET WebForms app.
These app use the old project file format and packages.config file.

Visual Studio 2022 can not build the project because it can't parse the line 
~~~xml
<package id="OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule" version="1.7.0-beta.1" targetFramework="net48" />
~~~
in the packages.config file.

I suspect that it is the .-Beta.1 isn't a valid suffix for the version

**Comment by Kielek** [comment]
@matthewDDennis, could you please prepare [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)? It will be much easier to proceed and try to understand where you have an issue. If you provide exact errors, it will be great.

It can be dedicated repository or all code snippets needed to compile.

**Comment by matthewDDennis** [comment]
It appears that I can't duplicate this outside of our 20+ year old solution.
Probably configured for some old tooling.
