### ISSUE TITLE
Inquiry on the new OpenTelemetry.Exporter.Stackdriver beta release

### ISSUE THREAD

**Issue by StasPerekrestov** [open-telemetry/opentelemetry-dotnet-contrib#1579]
I'm writing to request a new beta release of `OpenTelemetry.Exporter.Stackdriver` that includes the changes from issue [#1414](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1414). These changes would significantly benefit our current project.

Could you consider rolling out a beta version with these updates? The current version [1.0.0-beta.4](https://www.nuget.org/packages/OpenTelemetry.Exporter.Stackdriver/1.0.0-beta.4) was released on 12/7/2022. Happy to assist in testing or any other way needed.

Thanks for your great work on this project!

**Comment by vishweshbankwar** [comment]
@StasPerekrestov Could you send the PR for this? https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md#how-to-request-for-release-of-package
