### ISSUE TITLE
Correlate consequent spans from a request to DB

### ISSUE THREAD

**Issue by simonaTsenova** [open-telemetry/opentelemetry-dotnet-contrib#158]
I am using the OpenTelemetry.Contrib.Instrumentation.MySqlData package to get traces for the queries I make to my db and export them to Jaeger. In my .NET Core controller action I make multiple calls to the db. However, the instrumentation only correlates the first one to the current activity (in my case it is an activity for an http request) and all the other calls are traced separately. Is there a way to work around or fix this so that all the db calls' traces are shown as children of the same root activity (the http request activity)? I am also using the OpenTelemetry.Instrumentation.AspNetCore package for the Web API instrumentation.

I am attaching a screenshot from my Jaeger. It shows the trace for the http request inside which is the first db call trace but all other db call traces are shown separately.
![image](https://user-images.githubusercontent.com/13004760/134125987-ff9fc949-f069-4ffc-b083-efa2f0a381a6.png)

**Comment by grahambunce** [comment]
@simonaTsenova Did you find a workaround for this?

**Comment by Kielek** [comment]
Closing this issue as the library is deprecated.
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/75d7622d931abe5834435d01a1fc0a01c3af15a4/src/OpenTelemetry.Instrumentation.MySqlData/README.md#deprecated
