### ISSUE TITLE
Question: .NET Framework 4.6.2 Nuget Packages pre-release only?

### ISSUE THREAD

**Issue by tmulkern** [open-telemetry/opentelemetry-dotnet-contrib#1584]
Hey All,

I have noticed a trend that all the OpenTelemetry.Instrumentation.* nuget packages that are build with .NET Framework 4.6.2 support in mind are pre-release packages only even though most of them are on a major release. Is there any reason for this?

**Examples**

[OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/1.7.0-beta.2)
[OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper](https://www.nuget.org/packages/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper)
[OpenTelemetry.Instrumentation.AspNet](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNet/1.7.0-beta.2)

**Comment by Kielek** [comment]
@tmulkern, [OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper](https://www.nuget.org/packages/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper) has a stable release but the goal for this package is to be used by [OpenTelemetry.AutoInstrumentation](https://www.nuget.org/packages/OpenTelemetry.AutoInstrumentation). For now, I do not see any good reason to use it outside.

If we speaking about 

[OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/1.7.0-beta.2) and 

[OpenTelemetry.Instrumentation.AspNet](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.AspNet/1.7.0-beta.2). There is no stable release. HTTP and network semantic convention was released couple months ago. For now, there were no requests to make the stable release. If you would like to contribute it will be great. The main blocker is to adjust sem. conv. to the latests version. You can check what changes was applied for 1.5.0-1.7.1 releases in the [AspNetCore instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/CHANGELOG.md). Probably most of them should be also applied here.

@vishweshbankwar , do you see any other blockers?

**Comment by tmulkern** [comment]
Thanks for the succinct answer @Kielek! Happy to contribute and fix up those libraries. Will start looking into creating PR's. Stay tuned.....
