### ISSUE TITLE
TraceParent is not being sent in Http Request Headers in net framework 472  

### ISSUE THREAD

**Issue by sunildatla** [open-telemetry/opentelemetry-dotnet-contrib#1588]
# Issue with OpenTelemetry.Instrumentation.AspNet

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

* TBD

Runtime version net472

**Is this a feature request or a bug?**

Bug

**What is the expected behavior?**

TraceParent should flow in Http headers when using HttpClient

What do you expect to see?

Do not see traceparent in http headers

Here is the minimal repro : 
https://github.com/sunildatla/TraceParentExampleForNetFX

-In global.asax.cs added below line of code to start tracebuilder 
 Sdk.CreateTracerProviderBuilder().AddAspNetInstrumentation().AddHttpClientInstrumentation().AddSource("*").AddConsoleExporter().Build();

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/examples/AspNet Can you start with the example from this repo, and add changes to it incrementally?

**Comment by martinjt** [comment]
Stale issue as no response after 4 months.
