### ISSUE TITLE
[OpenTelemetry.Export.Stackdriver] Process crashes during export if there are duplicate tags

### ISSUE THREAD

**Issue by tlevesque-ueat** [open-telemetry/opentelemetry-dotnet-contrib#1622]
> Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: UeatCorrelationId

Using OpenTelemetry.Export.Stackdriver 1.0.0-beta.5

The error seems to happen here:

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/2f3a6949a4dd2ebbcd774ad5c9f0e5df382d2414/src/OpenTelemetry.Exporter.Stackdriver/Implementation/ActivityExtensions.cs#L74-L76

Example in GCP logs:
![image](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/assets/102250945/af7f76b3-5a5f-4810-9825-848f39e7fe78)

Not sure how we ended up with duplicate tags (probably by using `AddTag` instead of `SetTag`), but it shouldn't cause the process to crash!

**Comment by Kielek** [comment]
@tlevesque-ueat, `OpenTelemetry.Export.Stackdriver` package is rarely updated. Consider creating PR with the fix to have it fixed. We will be happy to review it.

@SergeyKanzhelev, FYI

**Comment by tlevesque-ueat** [comment]
I don't mind giving it a try, but I'm not sure what the proper fix would be.
Just take the first tag with a given key and ignore the others? Or the last?

**Comment by StasPerekrestov** [comment]
Can confirm I also observed the [issue](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Exporter.Stackdriver/Implementation/ActivityExtensions.cs#L74)

**Comment by Kielek** [comment]
I do not think that there is any recommendation. I think any solution preventing crach will be better than the current solution.

BTW do you really need to use this exporter? Any chance to swich to standard OTLP?

**Comment by StasPerekrestov** [comment]
I must review the docs and check if Google supports the standard OTLP.
However, I can see that even its [Java lib](https://search.maven.org/artifact/com.google.cloud.opentelemetry/exporter-trace/0.28.0/jar) depends on Trace API V2, just as the .NET StackDriver exporter does.

**Comment by Kielek** [comment]
I am not telling that it is deprecated, or bad or anything like this. OTLP is kind of the standard and supported by multiple vendors/tools already. I am trying to tell that it can be good, well-maintained alternative for this package.

**Comment by cijothomas** [comment]
> I am not telling that it is deprecated, or bad or anything like this. OTLP is kind of the standard and supported by multiple vendors/tools already. I am trying to tell that it can be good, well-maintained alternative for this package.

+1. This is *not* an official Google supported component: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Exporter.Stackdriver#stackdriver-exporter-for-opentelemetry-net
