### ISSUE TITLE
Add host.id for non-containerized systems 

### ISSUE THREAD

**Issue by matt-hensley** [open-telemetry/opentelemetry-dotnet-contrib#1630]
# Issue with OpenTelemetry.ResourceDetectors.Host

Package `OpenTelemetry.ResourceDetectors.Host` version 0.1.0-alpha.2

**Is this a feature request or a bug?**

* [x] Feature Request
* [ ] Bug

**What is the expected behavior?**

`host.id` is a recommended attribute, and should be populated for non-containerized systems.

[The specification has a list of required sources](https://opentelemetry.io/docs/specs/semconv/resource/host/#collecting-hostid-from-non-containerized-systems) if host.id is collected outside containers.

**What is the actual behavior?**

`host.id` attribute is not populated for non-containerized systems.

## Additional Context

I'm available to implement this feature.

**Comment by Kielek** [comment]
@matt-hensley, thanks, looking for the PR :)
