### ISSUE TITLE
Static options causes test issues in WcfInstrumentation

### ISSUE THREAD

**Issue by epaulsen** [open-telemetry/opentelemetry-dotnet-contrib#164]
I am having trouble writing unit tests for code that uses a `TracerProviderBuilder` together with WCF instrumentation.
The problem is that WCF instrumentation can only be set up once,  as it [throws an exception on second attempt to add instrumentation.](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Contrib.Instrumentation.Wcf/TracerProviderBuilderExtensions.cs#L40-L43)

This does not cause any issues in prod, but writing tests where the TracerProviderBuilder only can be wired up once is a hassle.

Is there any particular reason why it is done this way?  
I don't see any issues with it simply overwriting the existing instrumentationoptions.

**Comment by Kielek** [comment]
Newer issue tracking same problem: #1592. Closing this instance.
