### ISSUE TITLE
Can we filter out the not needed resource attributes ?

### ISSUE THREAD

**Issue by prajon84** [open-telemetry/opentelemetry-dotnet-contrib#1641]
# Issue with OpenTelemetry.ResourceDetectors.AWS

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

* TBD

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

* TBD

**Is this a feature request or a bug?**

* [x] Feature Request
* [ ] Bug

**What is the expected behavior?**

What do you expect to see?

**What is the actual behavior?**

What did you see instead? If you are reporting a bug, create a self-contained
project using the template of your choice and apply the minimum required code to
result in the issue you're observing. We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

Add any other context about the feature request here.

@Kielek

**Comment by prajon84** [comment]
For e.g. for AWSResourceDetector: If I need only `account id` and `task arn` and not others.
out of [all these](AWSECSResourceDetector: cloud provider, cloud platform, cloud resource id, account id, cloud availability zone, cloud region, container id, cluster arn, task arn, task family, task revision, launch type, container arn, log group names, log group ids, log stream names, log stream ids.
)

**Comment by Kielek** [comment]
For now, there is no such possibility.
OpenTelemetry collector can be central point where you can process all data. It includes any manipulation of resources/attributes. Is it an option for you?

**Comment by prajon84** [comment]
Oh ok. I have to consult with my team then. I am not sure if we can manipulate resource attributes at collector level.

**Comment by martinjt** [comment]
The Collector is the solution for this, take a look at the transform processor. I would suggest keeping at the resource attributes however, as these allow you to filter and graph later if they do become relevant.

I'm closing this as it's not something we would do at the SDK level.
