### ISSUE TITLE
Add a Microsoft.Extensions.Logging Exporter

### ISSUE THREAD

**Issue by almostchristian** [open-telemetry/opentelemetry-dotnet-contrib#165]
The existing exporters in the main library don't play well with other Logging providers, such as Serilog, In particular, ConsoleExporter writes directly to `System.Console`, so its logs cannot be captured by Serilog. Also, Serilog [does not play well with other logging providers](https://stackoverflow.com/a/56227367) so that in the [example shown](https://github.com/open-telemetry/opentelemetry-dotnet/blob/8029751d9248045803e09a1dacd578baea09faaf/examples/AspNetCore/Program.cs#L46) in the main library, where the OpenTelemetry logging provider was added, any logs written by this logging provider cannot be captured by any Serilog sink.

I propose an additional exporter which logs to the interfaces from the Microsoft.Extensions.Logging. This exporter replaces ConsoleExporter, since in a default aspnetcore application (or a console application using the GenericHost) includes a default logging provider, this exporter will log to Console. And since this exporter will use structured logging, logging providers such as Serilog will be able to extract the trace values and write them to a database for example.

The primary reason for wanting this library is for scenarios where you don't have a distributed tracing service such as Jaeger to export the trace logs to, and you want to use your existing logging providers as an export target.

https://github.com/open-telemetry/opentelemetry-dotnet/issues/2570

**Comment by almostchristian** [comment]
I don't believe your code will work @adamhathcock when you configure Serilog with a sink other than the console. For example, I want to configure Serilog with the sqlserver sink to write to the db. If you add a file sink to your code, you will see that the OpenTelemetry logs you see in the console will not get logged to the file

```csharp
using Serilog;
using OpenTelemetry.Logs;
using System.Reflection;
using Serilog.Events;

var builder = WebApplication.CreateBuilder(args);
builder.WebHost.UseSerilog((ctx, config) =>
{
    config
    .MinimumLevel.Information()
    .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning)
    .Enrich.FromLogContext()
    .Enrich.WithProperty("Version", Assembly.GetExecutingAssembly().GetName().Version)
    .WriteTo.File("Logs/log.log");
}, writeToProviders: true);
builder.WebHost.ConfigureLogging((ctx, builder) =>
{
    builder.ClearProviders();
    builder.AddOpenTelemetry(options =>
    {
        options.AddConsoleExporter();
    });
});

```

**Comment by adamhathcock** [comment]
@almostchristian you could be correct.  My legacy logs only to the console in a docker scenario to have an agent scrape those.  Now i've added in the open telemetry stuff and it appears to work the same.

I haven't used a file sink or any other.

**Comment by cijothomas** [comment]
A new exporter should be written to meet this requirement following the guide here : https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#exporter
Exporter gets all traces, and it can in-turn emit it to `ILogger`.

**Comment by julealgon** [comment]
Should a mention be added that new _metrics_ and _traces_ exporters should be created (but not logs)? Exporting logs, which can already leverage `ILogger`, to another `ILogger` would probably not be that useful in 99% of cases.

**Comment by CodeBlanch** [comment]
@almostchristian In your code above you are clearing the logger providers which removes Serilog's ILogger integration. Try removing that line:

```csharp
builder.WebHost.ConfigureLogging((ctx, builder) =>
{
    // builder.ClearProviders(); <- Remove this
    builder.AddOpenTelemetry(options =>
    {
        options.AddConsoleExporter();
    });
});
```

**Comment by giancarloaguilera** [comment]
@almostchristian Did you ever get this to work? I am looking for exactly what you described.

**Comment by martinjt** [comment]
Serilog has support for OTLP, and I seem to recall them adding trace exporting too.

Either way, the recommended approach for OpenTelemetry is to output using OTLP and not to the console for something else to then pick up. Therefore unless someone proposes a package for this, and wants to maintain it, I'm going to close this issue.
