### ISSUE TITLE
Request for new component: Baggage Span Processor

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-dotnet-contrib#1650]
# Issue that does not fit into other categories

The Honeycomb distro currently provides a Span processor that takes items from the baggage and adds those items as attributes onto spans. We'd like to donate this code upstream if there's an interest from the community, the code is pretty minimal:

- https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/blob/main/src/Honeycomb.OpenTelemetry/BaggageSpanProcessor.cs

**Comment by Kielek** [comment]
If you think that it can be useful for other users and you agree with https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md#contributing-a-new-project feel free to create PR.
