### ISSUE TITLE
The Owin metrics middleware creates new Meter instances for each request, causing massive lock contention 

### ISSUE THREAD

**Issue by gliljas** [open-telemetry/opentelemetry-dotnet-contrib#1654]
# Issue with OpenTelemetry.Instrumentation.Owin

* [ ] Feature Request
* [x] Bug

From src/OpenTelemetry.Instrumentation.Owin/Implementation/OwinInstrumentationMetrics.cs

```
    public static Meter Instance => new(MeterName, Assembly.GetPackageVersion());

    public static Histogram<double> HttpServerDuration => Instance.CreateHistogram<double>("http.server.request.duration", "s", "Duration of HTTP server requests.");
```
This creates a new Meter instance and a new Histogram every time OwinInstrumentationMetrics.HttpServerDuration is accessed. Creating new Meters is expensive and wrong. 

Using the metrics part of OpenTelemetry.Instrumentation.Owin is currently an impossibility due to this.

**Comment by cijothomas** [comment]
> This creates a new Meter instance and a new Histogram every time OwinInstrumentationMetrics.HttpServerDuration is accessed

They are declared as static fields, so how are they newly created every time?

**Comment by gliljas** [comment]
No, they are declared as static **properties**. 

`public static Meter Instance => new(MeterName, Assembly.GetPackageVersion());`

is the same thing as 
```
public static Meter Instance
{
    get
    {
        return new(MeterName, Assembly.GetPackageVersion());
    }
}
```

Initializing it would make it static.

`public static Meter Instance { get; } = new(MeterName, Assembly.GetPackageVersion());`

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInMetricsListener.cs#L29 Could we use this approach?

**Comment by gliljas** [comment]
Absolutely, that should work fine. The style rules will probably want you to declare the fields as internal, but since the class itself is internal, that should be fine too.
