### ISSUE TITLE
Feature Request: Reintroduce `OpenTelemetry.SemanticConventions`

### ISSUE THREAD

**Issue by joegoldman2** [open-telemetry/opentelemetry-dotnet-contrib#1657]
**What are you trying to achieve?**

https://github.com/open-telemetry/opentelemetry-dotnet/pull/5539 removed the package `OpenTelemetry.SemanticConventions`. This package served as a centralized resource for all standard attributes from the protocol, preventing repetition and duplication across projects. Is it possible to reintroduce this package in this repo rather than in the main one?

**Additional context.**

I'm ready to contribute to migrate the sources in this repo and update them (with the latest version of the spec).

**Comment by Kielek** [comment]
@martinjt, @lmolkova,
as I remember you have discussed how should look this package (namaspaces including sem. conv. version). Could you please make some summary here to make @joegoldman2 job easier?

**Comment by lmolkova** [comment]
I've started to document patterns we have across semconv generator here https://github.com/open-telemetry/semantic-conventions/pull/953, PTAL
