### ISSUE TITLE
Release Stable AWS Lambda Instrumentation

### ISSUE THREAD

**Issue by willarmiros** [open-telemetry/opentelemetry-dotnet-contrib#166]
This issue is to track the stable release of the `OpenTelemetry.Contrib.Instrumentation.AWSLambda` package as stable. Currently it is in beta: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/releases/tag/Instrumentation.AWSLambda-1.1.0-beta1

cc @srprash @lupengamzn

**Comment by Oberon00** [comment]
Do you have any particular reason for needing a non-beta release? There are still breaking changes to the emitted telemetry to be expected since this package produces spans following various different conventions and no stable semantic conventions have been released yet

**Comment by martinjt** [comment]
A stable release will happen when the Semantic conventions are stable. For now, the package is available for production use, and is used in lots of high-volume, business critical applications without issue.

Unfortunately, there is no timescale for those semantic conventions to be stablised.
