### ISSUE TITLE
BoundedContext span name

### ISSUE THREAD

**Issue by juchom** [open-telemetry/opentelemetry-dotnet-contrib#167]
I'm discovering opentelemtry so this question may not be relevant but I have this trace :

![image](https://user-images.githubusercontent.com/17902415/144565547-0bfd0c41-d772-4d14-83b3-a81dd8118669.png)

This trace is composed of 3 spans, the first one is my web app `MYSERVICE:WEB` which is fine.

The two spans after come from two different DbContext, would it be possible to have the second span named `AUTH:DB` and the second one `APP:DB` ?

**Comment by Kielek** [comment]
I think that your UI is displaying just service names in the tree.

Closing as it looks like obsolete, display issue.
