### ISSUE TITLE
[repo] Add linting of yml/yaml files in CI

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet-contrib#1688]
We ran into an issue where a typo in a yml file (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1672/commits/09cafa5c36537a7743bee9150ecb18babd6e6918) broke all code coverage upload.

I did a quick scan of GitHub marketplace, there seem to be some YML linters available. We should add linting of yml/yaml files into the CI.

High level we need to add a bucket for these files here: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/dc7be37862e4669638bb9df42db83794cbb667d7/.github/workflows/ci.yml#L20

`yml: [ '**.yml, '**.yaml' ]`

And then add a step for `yml` changes which calls some workflow to run linting. Similar to this...

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/dc7be37862e4669638bb9df42db83794cbb667d7/.github/workflows/ci.yml#L78-L83

**Comment by mowies** [comment]
Hi!
I'd like to work on this :)
Any recommendations on what YAML linter to use here? Otherwise i'll look through some other OTel repos and check out what they are using.

**Comment by CodeBlanch** [comment]
Thanks @mowies I assigned the issue to you. I have no idea what to use 🤣 Checking the other repos around OTel sounds like a great idea to me.
