### ISSUE TITLE
WCF Rest service with operation contract not containing 'Name' causes null reference error

### ISSUE THREAD

**Issue by tamilaban** [open-telemetry/opentelemetry-dotnet-contrib#169]
I am trying to integrate OpenTelemetry.Contrib.Instrumentation.Wcf to my WCF Restful service and I am getting null reference error at 
TelemetryDispatchMessageInspector. When trying to assign action to activity displayname 

`                activity.DisplayName = action;
`

**Comment by meastp** [comment]
This might be related to #202 (even if its not the same issue)

**Comment by CodeBlanch** [comment]
Fixed by #170
