### ISSUE TITLE
Provide an NLOG OTLP layout

### ISSUE THREAD

**Issue by thompson-tomo** [open-telemetry/opentelemetry-dotnet-contrib#1701]
**What are you trying to achieve?**

I want my structured logging to mirror the structure of the OTLP model. This is so that i can use an agent to upload my files to an OTLP endpoint. This will mean that we would need, a couple of layouts -> Traces, Metrics etc and able to specify that layout like we do with Elastic.CommonSchema for NLog

**Additional context.**

Logging exporter has been raised as #1700 & #1702 will be the serilog target

**Comment by martinjt** [comment]
This would need to be something that NLog builds an exporter.

The OpenTelemetry project supports the OTLP format using Protobuf as an exporter. Consider using the OpenTelemetry Collector to do the translation.
