### ISSUE TITLE
Where can I find the latest packages for 1.8.1

### ISSUE THREAD

**Issue by DR9885** [open-telemetry/opentelemetry-dotnet-contrib#1706]
# Issue that does not fit into other categories

**What are you trying to achieve?**
Want to get the latest packages of core and contrib where can I find them?

What do you expect to see?
When I look on nuget they are outdated
https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Hangfire/
https://www.nuget.org/packages/OpenTelemetry.Instrumentation.ElasticsearchClient/

**Additional context.**

**Comment by reyang** [comment]
@DR9885 I've assigned the issue to the owners according to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/.github/component_owners.yml.

**Comment by ejsmith** [comment]
As far as I know, we don't have any control over publishing packages.

**Comment by Kielek** [comment]
@ejsmith, it is not fully true. As a component owner you can request/approve/block releasing packages.

If you feel that we should have the new release, please follow this procedure https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md#how-to-request-for-release-of-package

We are trying to handle such request on a daily basis.

**Comment by Kielek** [comment]
@DR9885, current releases of these packages should work fine with OTel SDK/API 1..8.1. If it is not the case, please let us know about this.

In the queue there is some minor commits to be released. Procedure how to do this is included in my previous comment.

**Comment by mlapaglia** [comment]
How can we request a release from a component owner? [Influx](https://www.nuget.org/packages/OpenTelemetry.Exporter.InfluxDB/) only has alpha versions available on nuget and isn't targeting net8 yet. Do i ping @Havret here or raise a new issue?

**Comment by Kielek** [comment]
@mlapaglia, please check https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md#how-to-request-for-release-of-package - this is how you can request new package version. Two examples #1836 and #1834.

If we speaking specifically about InfuxDB exporter - Havret is the component owner so he should accept this kind of PR.
.NET8 should be supported. This package has libraries for .NET6. .NET8 is backward compatible (we are even executing tests for .NET8 with .NET6 libraries)

**Comment by martinjt** [comment]
@DR9885 what is it you're looking to achieve by having a 1.8.1 compatible version? There wouldn't be a stable version of these packages due to the semantic conventions being not stable yet.

The current 1.6.1-beta package is stable in all but the naming and should be able to be used with 1.8.1 of the core libraries.

**Comment by Kielek** [comment]
I am closing this issue. Feel free to create PRs requesting releases for specific packages.
