### ISSUE TITLE
Can this be used for instrumentation of Amazon Athena? 

### ISSUE THREAD

**Issue by prajon84** [open-telemetry/opentelemetry-dotnet-contrib#1709]
# Issue with OpenTelemetry.Instrumentation.AWS

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

* TBD

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

* TBD

**Is this a feature request or a bug?**

* [ ] Feature Request
* [ ] Bug

**What is the expected behavior?**

What do you expect to see?

**What is the actual behavior?**

What did you see instead? If you are reporting a bug, create a self-contained
project using the template of your choice and apply the minimum required code to
result in the issue you're observing. We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

Add any other context about the feature request here.

**Comment by ppittle** [comment]
There is no special handling or tie-in with Amazon Athena.

**Comment by Kielek** [comment]
Closing as agreed with @ppittle. Feel free to reopen if you need more assistance.
