### ISSUE TITLE
Component owners- mention component owners in PRs

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-contrib#1715]
>> https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/9021608738/job/24789303314?pr=1713#step:2:10 The workflow is broken it seems. 

>I think the problem is with definition of who is the "collaborator" by the GitHub. I didn't find a way to mark all codeowners as collaborators. I suppose we could change the assign job, to call all code-owners in the comments. It should be always working.

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1713#issuecomment-2103890830_

**Comment by reyang** [comment]
I think the gap here is that folks should first become [OpenTelemetry Member](https://github.com/open-telemetry/community/blob/main/community-membership.md#member)? Probably good to enforce it.

**Comment by Kielek** [comment]
I am not sure if it sufficient, last status only @atshaw43 and @zivaninstana are not part of this group. Ref: #1201

**Comment by reyang** [comment]
> I am not sure if it sufficient, last status only @atshaw43 and @zivaninstana are not part of this group. Ref: #1201

@Kielek do you have a concrete example that folks are already OpenTelemetry but the issue cannot be assigned to them? I might be able to help if you can provide a repro.

**Comment by Kielek** [comment]
@reyang, I am pretty sure that I saw such PRs, but I cannot find anything like this, probably one of these accounts were involved in the requests.
For now, we have two _problematic_ accounts.

@atshaw - received invitation (twice) https://github.com/open-telemetry/community/issues/1629
@zivaninstana - also received invitation https://github.com/open-telemetry/community/issues/1589

Both never accepted.

**Comment by zivaninstana** [comment]
I will accept, I just need to see where the request is sent

**Comment by zivaninstana** [comment]
Sorry, no request, invitation

**Comment by zivaninstana** [comment]
Please send it again, I will accept. I am really keen on continuing to contribute.

**Comment by reyang** [comment]
> Please send it again, I will accept. I am really keen on continuing to contribute.

I've resent the invite, sorry for the delay (I don't actively monitor the conversations in this repo unless folks explicitly tag me):

![image](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/assets/17327289/c837f080-b062-42e8-aa4d-f8ee8ebd74d0)

**Comment by Kielek** [comment]
@zivaninstana, please check all you email account associated with GitHub account. Invitation will be expired after some time, so please do not postpone this activity.

**Comment by zivaninstana** [comment]
Thank you folks. I just accepted an invitation. I really look forward to working with you.

**Comment by ppittle** [comment]
Created #1822 to (temporarily) remove @atshaw from component owners until he can fully on-board with [Open Telemetry Community](https://github.com/open-telemetry/community/issues/1629)
