### ISSUE TITLE
SqlClient instrumentation doesn't work on netfx using Microsoft.Data.SqlClient 3.0.0

### ISSUE THREAD

**Issue by mbakalov** [open-telemetry/opentelemetry-dotnet-contrib#1737]
New major release of SqlClient has changed their EventSource from this:
```csharp
[Event(BeginExecuteEventId, Keywords = Keywords.ExecutionTrace, Task = Tasks.ExecuteCommand, Opcode = EventOpcode.Start)]
internal void BeginExecute(int objectId, string dataSource, string database, string commandText)
{
	if (Log.IsExecutionTraceEnabled())
	{
		WriteEvent(BeginExecuteEventId, objectId, dataSource, database, commandText);
	}
}
```

To this ([PR open-telemetry/opentelemetry-dotnet#897](https://github.com/dotnet/SqlClient/pull/897)):
```csharp
internal void TryBeginExecuteEvent(int objectId, Guid? connectionId, string commandText, [System.Runtime.CompilerServices.CallerMemberName] string memberName = "")
{
	if (Log.IsExecutionTraceEnabled())
	{
		BeginExecute(GetFormattedMessage(SqlCommand_ClassName, memberName, EventType.INFO,
			string.Format("Object Id {0}, Client Connection Id {1}, Command Text {2}", objectId, connectionId, commandText)));
	}
}

// ...

[Event(BeginExecuteEventId, Keywords = Keywords.ExecutionTrace, Task = Tasks.ExecuteCommand, Opcode = EventOpcode.Start)]
internal void BeginExecute(string message) =>
	WriteEvent(BeginExecuteEventId, message);
```

Our `SqlEventSourceListener` expects 4 items in the payload (ObjectId, DataSource, Database, CommandText) but now gets only "Message" and doesn't log anything.

It looks like we're unable to get the server/db anymore on netfx which is unfortunate. Opening this issue here to track resolution, but probably best to ask SqlClient team to make some changes in their EventSource if they can.

**Comment by Kielek** [comment]
Cloisng. I do not think that we will invest in this bug. It is well documented in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/de38aecbabc195fbbb29a5078b0b66513638ac9c/src/OpenTelemetry.Instrumentation.SqlClient#sqlclient-instrumentation-for-opentelemetry
