### ISSUE TITLE
[SqlClient] Broken on .NET Framework?

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet-contrib#1739]
I noticed working on open-telemetry/opentelemetry-dotnet#3900 that [the .NET Framework integration test is failing](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlEventSourceTests.netfx.cs#L51).

On .NET Framework Sql instrumentation listens to `SqlEventSource` which [uses keywords](https://github.com/microsoft/referencesource/blob/dae14279dd0672adead5de00ac8f117dcf74c184/System.Data/System/Data/Common/SqlEventSource.cs#L39-L42).

When `SqlCommand`s are executing the `EventSource` code is writing this error instead of behaving normally (firing `BeginExecute` \ `EndExecute`):

> ERROR: Exception in Command Processing for EventSource Microsoft-AdoNet-SystemData: Use of undefined keyword value 0x1 for event BeginExecute.

Working with @tarekgh it seems the nested `public static class Keywords` is not present in the final code. We suspect some kind of trimming issue. Waiting to hear back from some other folks.

Not sure when this started. We don't run the .NET Framework integration tests in our CI. But as far as I can tell, instrumentation is broken on .NET Framework. Could be only certain versions or OSes are impacted. I'm running 4.8.09032 on Windows 11.

**Comment by pellared** [comment]
@CodeBlanch, I think we can close this bug.

I tested it here: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3412
