### ISSUE TITLE
OpenTelemetry .NET Tracing AspNetCore instrumentation is inefficient

### ISSUE THREAD

**Issue by dpk83** [open-telemetry/opentelemetry-dotnet-contrib#1745]
# Feature Request

It's more of an issue than a feature request. We care a lot about performance for our services and in our local benchmarking we found that AspNetCoreInstrumentation for tracing is extremely inefficient. In a simple AspNetCore application with an extremely simple rest endpoint enabling tracing reduces the service throughput by around 15% which is huge for serving telemetry. (Drops from 10K RPS to 8.6K RPS)

**Is your feature request related to a problem?**

Yes, telemetry collection should be high performance and shouldn't impact service throughput.

**Describe the solution you'd like:**

Improve the performance of OTel instrumentation so it's not impacting service throughput.

**Describe alternatives you've considered.**

A custom middleware which is only using resources for processing what's essential on top of what AspNetCore out of box tracing instrumentation already provides.

## Additional Context

The code for application used to measure the throughput and the results can be found here https://github.com/dpk83/otelperfimpactanalysis/tree/main/TelemetryPerfImpactAnalysis

**Comment by martinjt** [comment]
This is an ongoing task to optimize and therefore this isn't a tracking issue. If you have specific areas and suggestions to improve them, I'd suggest they're split out into separate issues for you to work.

**Comment by cijothomas** [comment]
Ping to https://github.com/dotnet/runtime/issues/107158 Contention is visible with https://github.com/cijothomas/lock-contention-activity-repro/blob/main/lock-contention-activity-repro/Program.cs

**Comment by cijothomas** [comment]
https://github.com/dotnet/runtime/pull/107333 Should fix the contention from runtime itself.

**Comment by cijothomas** [comment]
Closing as https://github.com/dotnet/runtime/pull/107333 is merged, and will be part of .NET 10.
