### ISSUE TITLE
[AspNetCore Instrumentation] Scrubbing of sensitive data in URLs

### ISSUE THREAD

**Issue by dpk83** [open-telemetry/opentelemetry-dotnet-contrib#1747]
# Feature Request

Make the instrumentation library more flexible to emit the URL information in a much more flexible manner to allow consumers to write a processor to scrub the sensitive information with minimal impact on performance.

**Is your feature request related to a problem?**
AspNetCore instrumentation library emits _http.path_ and _http.url_ tags containing the URL. These URLs can contains sensitive information e.g. something like, _https;//www.contoso.com/users/useralias@organization.com/chat/chat-12345_

In this example this URL contains the user's id which is sensitive information that could lead to privacy issues. Currently the only way to scrub this information is to write a processor which would need to run complex regex on these URLs to detect and scrub sensitive information which takes a significant hit at performance. 

_Note_: Similar problem exists for other instrumentation libraries and we would like to have similar support for those too.

**Describe the solution you'd like:**
I would like to propose the following
1) Utilize the _http.route_, e.g. in the above example https;//www.contoso.com/users/{userId}/chat/{chatId}, and log the parameter values as separate tags i.e. in this case _userId_ and _chatId_ goes as tags. 
2) Either remove http.path and http.url (as the full URL can be built using the http.route and the parameter tags) OR expose options for consumers to disable adding these tags.

Another point worth discussing here: While in this solution consumers of the library will write their processors and the processors can be customized to have own redaction library and redaction mechanism, it would be good to see if there is a way to standardize on the redaction mechanism somehow.

**Describe alternatives you've considered.**
- One alternative is to write a processor that runs complex regex on the URLs to detect and then scrub sensitive information. This is expensive in terms of performance so we would certainly want to avoid it.
- Another alternative to write a separate custom instrumentation library where we can also avoid the processor and have all the required scrubbing directly inside the library.

## Additional Context
Not leaking sensitive data is critical for our enterprise services so not scrubbing isn't an option.

**Comment by julealgon** [comment]
@dpk83 
> These URLs can contains sensitive information e.g. something like, _https;//www.contoso.com/users/[useralias@organization.com](mailto:useralias@organization.com)/chat/chat-12345_

If you know the data is sensitive, why would you expose it in the URL in the first place?

**Comment by martinjt** [comment]
The recommended way to redact is using the OpenTelemetry Collector. We now have redaction of the QueryString parameters.

Further, it's not recommended that sensitive data is in the path anyway since that ends up in Access logs for webservers.

I don't think there's anything more to do on this issue.

**Comment by abatishchev** [comment]
@martinjt

>We now have redaction of the QueryString parameters

Is there a way to opt out?

**Comment by abatishchev** [comment]
thanks, @CodeBlanch! I asked and then found the corresponding environment variables myself.

I asked a question about them here: https://github.com/open-telemetry/semantic-conventions/issues/860#issuecomment-2423115542
