### ISSUE TITLE
Using new stackexchange.redis connection multiplexer for each blazor component, how do I instrument them?

### ISSUE THREAD

**Issue by philipbawn** [open-telemetry/opentelemetry-dotnet-contrib#1785]
# Question

Given I have a service like this https://github.com/philipbawn/redis-blazor-experiments/blob/main/MyServices/QueueManagementService.cs which I add to my service collection as a transient service services.AddTransient<QueueManagementService>();

How should I instrument the StackExchange.Redis calls?

I don't believe I can't use a shared connection multiplexer across the entire Blazor application (singleton) like in https://github.com/open-telemetry/opentelemetry-dotnet/issues/1554 because I'd like each component to have different redis channel subscriptions as well as in the future use the access control lists (ACL)  in redis to limit what keys each component has access to.

The connection multiplexer can only be registered as a singleton.

**Comment by Kielek** [comment]
@philipbawn, I suppose that you could use 1.0.0-rv9.9 or newer to cover this. Closing the issue for now. If you need any other help please reopen/create new issue.
