### ISSUE TITLE
SqlClient instrumentation span name is not suffient

### ISSUE THREAD

**Issue by stephenjust** [open-telemetry/opentelemetry-dotnet-contrib#1792]
# Bug Report

opentelemetry.instrumentation.sqlclient\1.0.0-rc7
opentelemetry\1.1.0

Runtime: net472

## Symptom

The SqlClient instrumentation always sets the operation DisplayName value to be equal to db.name. While the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#semantic-conventions-for-database-client-calls) suggests this is OK, I would argue that it is not helpful given that db.name is already added as a tag.

In [this spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span) the span name is described as:

>The span name concisely identifies the work represented by the Span, for example, an RPC method name, a function name, or the name of a subtask or stage within a larger computation. The span name SHOULD be the most general string that identifies a (statistically) interesting class of Spans, rather than individual Span instances while still being human-readable. That is, "get_user" is a reasonable name, while "get_user/314159", where "314159" is a user ID, is not a good name due to its high cardinality. Generality SHOULD be prioritized over human-readability.

For systems that connect to many different databases, the current behavior generates a "name" value with a fairly high cardinality and no indication of what the operation being performed is.

**What is the expected behavior?**

Spans for SqlClient operations should denote the operation being performed as per the generic Trace spec. In my opinion the spec for database tracing common fields, it would make sense to do the same, and leave database name, table name, etc as Tagged fields. Even if the operation name was "SQL Execute" if no more specific operation name could be identified, that would better enable log filtering and be more understandable.

**What is the actual behavior?**

Span name == db.name

## Reproduce

See https://github.com/open-telemetry/opentelemetry-dotnet/blob/6f3f7e5766612d5f6e71389d053ab3992051811b/src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs#L85

**Comment by martinjt** [comment]
I believe this has been fixed, if that is not the case then feel free to reopen.

**Comment by perlun** [comment]
Hmm... @martinjt, if this has been fixed, what was the outcome? Can the span name be overridden somehow?

I realize that parsing the SQL query is not doable or practical, but it would it be possible to at least be able to override the operation name where the user has opted-in to doing so? Or would this be contrary to the "spirit" (or letter) of the OpenTelemetry specs?

Our use case is somewhat like this: https://github.com/dotnet/SqlClient/issues/2210#issuecomment-2437360800. Set the query name to something explicit for all (or some) `SqlCommand`s, and be able to get this into the collected telemetry data. Getting into a tag works, but it does mean that all DB queries towards a particular database will be "grouped together" which may be a bit to coarse-grained to be really useful e.g. when looking at the telemetry data in web UI.
