### ISSUE TITLE
GenevaExporter uses `Expression.Lambda` from System.Linq.Expressions - AOT size and performance concerns

### ISSUE THREAD

**Issue by eerhardt** [open-telemetry/opentelemetry-dotnet-contrib#1814]
When using the GenevaExporter in a native AOT application, it is bringing in System.Linq.Expressions, which adds size to the app, but also any Linq.Expressions are interpreted at runtime (since IL can't be generated).

See the following:

              @eerhardt GenevaExporter also uses `Expression.Lambda` from [System.Linq.Expressions](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions?view=net-8.0). Did we not have a Trim/AOT issue when using that?

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/ab7bdabacb8907b1745ecdc2ee7544a681989e6c/src/OpenTelemetry.Exporter.Geneva/Internal/ReentrantExportProcessor.cs#L18-L25

_Originally posted by @utpilla in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1666#issuecomment-2067385239_

We should decide how to fix this. Options I see are:

1. Make `Batch<T>(T item)` ctor public, and GenevaExporter can just call it.
2. Use Reflection directly when `RuntimeFeature.IsDynamicCodeCompiled` is `false`.
3. Address this comment in the code and make this class go away:

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/ab7bdabacb8907b1745ecdc2ee7544a681989e6c/src/OpenTelemetry.Exporter.Geneva/Internal/ReentrantExportProcessor.cs#L10-L15

cc @utpilla @CodeBlanch

**Comment by utpilla** [comment]
Another approach would be to use the [public ctor](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Batch.cs#L29-L36) of `Batch` which takes in an array `T[]` and a count.  We could have a thread-local array of size 1 and use that every time we need to create a `Batch`.

However, the best thing would be to just mark the `Batch<T>(T item)` ctor public.

@CodeBlanch Thoughts?

**Comment by CodeBlanch** [comment]
@eerhardt How urgent is this? If we go the route of making the ctor public in SDK it will take a bit of time to get out into a stable release so GenevaExporter can consume it.

**Comment by eerhardt** [comment]
> How urgent is this?

Not very urgent. Just something that would be good to get fixed. Doing whatever is best long-term would be great. I'm not necessarily looking for a short-cut.

> We could have a thread-local array of size 1 and use that every time we need to create a Batch.

I'm not super familiar with the code, so my concern might not be valid, but since `Batch<T>` [holds directly on to the passed in array](https://github.com/open-telemetry/opentelemetry-dotnet/blob/7dd39b08fe5aa2d0120af3d5f7d561a778122646/src/OpenTelemetry/Batch.cs#L34), we would need to ensure the `Batch<T>` insance is never passed to another thread. If it was, it could contain the wrong data.
