### ISSUE TITLE
Release experimental version for OpenTelemetry.Contrib.Extensions.PersistentStorage package

### ISSUE THREAD

**Issue by vishweshbankwar** [open-telemetry/opentelemetry-dotnet-contrib#182]
This issue is for releasing OpenTelemetry.Contrib.Extensions.PersistentStorage package as experimental.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/runs/4974697703?check_suite_focus=true The release attempt failed as tests were failing.. I could retry, but please take a look at the test

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/runs/4974902772?check_suite_focus=true Frequently failing in net461. Please address the stability issue.

**Comment by vishweshbankwar** [comment]
Not sure what is the cause - I will disable this test for now and investigate.

**Comment by cijothomas** [comment]
> Not sure what is the cause - I will disable this test for now and investigate.

Please send a PR with the test disabled as this is blocking other PRs due to CI failure.

**Comment by vishweshbankwar** [comment]
@cijothomas - Is it good to release now?

**Comment by cijothomas** [comment]
https://www.nuget.org/packages/OpenTelemetry.Contrib.Extensions.PersistentStorage/1.0.0-alpha2 . Used alpha2 as there were more commits after alpha1 tag was pushed. (you can fix changelog to match the nuget later).
