### ISSUE TITLE
Provide an operating system resource package

### ISSUE THREAD

**Issue by thompson-tomo** [open-telemetry/opentelemetry-dotnet-contrib#1844]
### Component

None

### Is your feature request related to a problem?

I want information about my os to be visible in my open Telemetry data

### What is the expected behavior?

The following properties are set unless a user opts out

- os.build_id
- os.description
- os.name
- os.type

### Which alternative solutions or features have you considered?

Manually adding them

### Additional context

https://opentelemetry.io/docs/specs/semconv/resource/os/

**Comment by cijothomas** [comment]
would you be interested in contributing and maintaining a new package for this? OpenTelemetry.Resources.Os/similar..

**Comment by thompson-tomo** [comment]
Yes I am interested in contributing and getting more involved hence the number of issues I have been logging.

**Comment by Kielek** [comment]
@thompson-tomo, if you do not started working on this I will take care at least for the scaffolding.

We have an intern who will contribute to this task.
