### ISSUE TITLE
Rename container resource package

### ISSUE THREAD

**Issue by thompson-tomo** [open-telemetry/opentelemetry-dotnet-contrib#1845]
### Component

OpenTelemetry.ResourceDetectors.Container

### Is your feature request related to a problem?
Currently there is 2 naming conventions for resource packages

### What is the expected behavior?

That all resource packages have the same base name. In this case OpenTelemetry.ResourceDetectors.Container becomes OpenTelemetry.Resources.Container with old package being deprecated on nuget + user redirected to new one.

### Which alternative solutions or features have you considered?

Accept it

**Comment by Kielek** [comment]
Tracked under #1610. Closing.
