### ISSUE TITLE
Rename AWS resource package

### ISSUE THREAD

**Issue by thompson-tomo** [open-telemetry/opentelemetry-dotnet-contrib#1846]
### Component

OpenTelemetry.ResourceDetectors.AWS

### Is your feature request related to a problem?

Currently there is 2 naming conventions for resource packages

### What is the expected behavior?

That all resource packages have the same base name. In this case OpenTelemetry.ResourceDetectors.AWS becomes OpenTelemetry.Resources.AWS with old package being deprecated on nuget + user redirected to new one.

### Which alternative solutions or features have you considered?

Accept it

**Comment by Kielek** [comment]
In progress #1839
