### ISSUE TITLE
Adding rpc.system for AWS SDK specifications as per Semantic Conventions

### ISSUE THREAD

**Issue by birojnayak** [open-telemetry/opentelemetry-dotnet-contrib#1857]
### Component

OpenTelemetry.Instrumentation.AWS

### Is your feature request related to a problem?

No, this is not a problem, but a feature request for internal service to work. This feature is available in other languages like java, python, we are bringing in .net.

### What is the expected behavior?

rpc.system should be populated based on the schema mentioned [here](https://opentelemetry.io/docs/specs/semconv/cloud-providers/aws-sdk/#common-attributes)

### Which alternative solutions or features have you considered?

n/a

### Additional context

this is required for us to give same experience to our customers across all programming languages.

**Comment by yiran29** [comment]
Will work to update span tag based on Semantic Conventions: https://opentelemetry.io/docs/specs/semconv/cloud-providers/aws-sdk/
