### ISSUE TITLE
[Resources.Azure] Rename `AddAppServiceDetector` to `AddAzureAppServiceDetector`

### ISSUE THREAD

**Issue by joegoldman2** [open-telemetry/opentelemetry-dotnet-contrib#1874]
I wonder if the method `ResourceBuilder.AddAppServiceDetector` should be renamed to `AddAzureAppServiceDetector` to follow the naming convention of other methods which begin with `AddAzure` (like `AddAzureContainerAppsDetector`).

```diff
namespace OpenTelemetry.Resources;

public static class AzureResourceBuilderExtensions
{
-    public static ResourceBuilder AddAppServiceDetector(this ResourceBuilder builder);
+    public static ResourceBuilder AddAzureAppServiceDetector(this ResourceBuilder builder);
}
```

This package is still unstable, so renaming is possible.

**Comment by vishweshbankwar** [comment]
`AddAzureAppServiceDetector` sounds good to me. @joegoldman2 - Would you like to submit the PR? cc: @rajkumar-rangaraj
