### ISSUE TITLE
Use component-owners to tag owners

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet-contrib#192]
Borrow from https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.github/workflows/component-owners.yml and https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.github/workflows/component-owners.yml to ensure the owners (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CODEOWNERS) get notified. Currently they don't as they are not an approver/maintainer for this repo and has no write-access.

**Comment by rahuldimri** [comment]
@cijothomas Is this issue still open?. Can I work on this. ?

**Comment by cijothomas** [comment]
I think this is taken care already. @utpilla could you confirm, and close this issue as appropriate.

**Comment by cijothomas** [comment]
@rahuldimri If you are looking for contributing, do you want to help with https://github.com/open-telemetry/opentelemetry-dotnet/issues/2081 ?

**Comment by rahuldimri** [comment]
@cijothomas I would love you !!

**Comment by utpilla** [comment]
This is done.
