### ISSUE TITLE
RuntimeInstrumentationOptions has no properties

### ISSUE THREAD

**Issue by mortenbock** [open-telemetry/opentelemetry-dotnet-contrib#1929]
### Component

OpenTelemetry.Instrumentation.Runtime

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| Azure.Monitor.OpenTelemetry.AspNetCore                     | 1.2.0   |
| OpenTelemetry.Instrumentation.Runtime                         | 1.8.1   |

### Runtime Version

net8.0

### Description

When I call the `.AddRuntimeInstrumentation()` extension method, there is an overload that takes an action for `RuntimeInstrumentationOptions`.

However, when I examine the options object, it has no properties.

### Steps to Reproduce

Add the following code to a dotnet 8 web api project:

```
builder.Services
    .AddOpenTelemetry()
    .UseAzureMonitor()
    .WithMetrics(providerBuilder =>
    {
        providerBuilder.AddRuntimeInstrumentation(options =>
        {
            // Try to set options
            options.
        });
    });
```

### Expected Result

Properties allowing me to configure the metrics collected

### Actual Result

No properties exist on the options object.

**Comment by xiang17** [comment]
Hi, there is no configuration options for this library yet. The option interface was kept for future developments, and indeed a little confusing now.
