### ISSUE TITLE
Missing documentation for `OTEL_DOTNET_EXPERIMENTAL_OWIN_DISABLE_URL_QUERY_REDACTION`

### ISSUE THREAD

**Issue by julealgon** [open-telemetry/opentelemetry-dotnet-contrib#1949]
### Component

OpenTelemetry.Instrumentation.Owin

### Package Version

N/A

### Runtime Version

N/A

### Description

Documentation for the `OTEL_DOTNET_EXPERIMENTAL_OWIN_DISABLE_URL_QUERY_REDACTION` flag, introduced recently (with variations for multiple packages) is not properly documented in the readme for the Owin instrumentation. It is only mentioned in the changelog.

I believe this should be documented more explicitly so people reading the main documentation are aware of it. 

### Steps to Reproduce

Check the readme for the Owin instrumentation project. Notice there are no mentions of the `OTEL_DOTNET_EXPERIMENTAL_OWIN_DISABLE_URL_QUERY_REDACTION` flag.

### Expected Result

I'd expect all public configurable elements to be properly documented in the specific project's readme, a linked wiki or linked doc.

### Actual Result

Documentation is missing.

### Additional Context

This is particularly bad for people getting to the library now as they won't be looking at changelogs. I know about the setting at all because I've been watching the repo and using these packages before the change was made, so I saw the changelog when it happened.

I _still_ missed the setting on one of our applications when I went to add the Owin instrumentation a couple weeks ago though. We have these same settings already customized for AspNet, AspNetCore and Http, but I forgot the setting existed for Owin (my mistake) because I went through the whole readme when adding the instrumentation and there was no mention there (your mistake).

**Comment by Kielek** [comment]
@julealgon, would you like to improve docs? Happy to review and merge changes,

**Comment by julealgon** [comment]
@Kielek the signed CLA requirement makes this a bit tricky for me as I work as a contractor and the approval there is a bit bureaucratic. Otherwise, I'd send the PR right away.

**Comment by Kielek** [comment]
@julealgon, I would say that it is worth make this attempt. You are creating a lot of valuable issues. It will be great to see also code changes from your side. It should be beneficial both for your company and the whole community.

**Comment by julealgon** [comment]
Appreciate the kind words @Kielek . Will look into it.

**Comment by cijothomas** [comment]
> You are creating a lot of valuable issues

I had to read this part multiple times before I got it 🤣!

+1 to what @Kielek suggested. Love getting more contributors.
