### ISSUE TITLE
[Instrumentation.StackExchangeRedis] Vunerability warning due to transitive dependency

### ISSUE THREAD

**Issue by matt-hensley** [open-telemetry/opentelemetry-dotnet-contrib#1951]
### Component

OpenTelemetry.Instrumentation.StackExchangeRedis

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry.Instrumentation.StackExchangeRedis                     | 1.0.0-rc9.15   |

### Runtime Version

net8.0

### Description

Installing the `OpenTelemetry.Instrumentation.StackExchangeRedis` package pulls in `System.Drawing.Common` as a transitive dependency. Due to the [NuGet lowest applicable version rule](https://learn.microsoft.com/en-us/nuget/concepts/dependency-resolution#lowest-applicable-version), `System.Drawing.Common` is resolving to version 4.7.0 which [contains a critical CVE]( https://github.com/advisories/GHSA-rxg9-xrhp-64gj).

[Version 2.6.80 of the `StackExchange.Redis` package](https://github.com/StackExchange/StackExchange.Redis/issues/2283#issuecomment-1292028155) dropped the dependency causing the warning.

It is also possible to resolve the warning by taking an explicit dependency on version 4.7.2 or higher of `System.Drawing.Common`.

### Steps to Reproduce

1. Clone the contrib repository and build locally
2. navigate to `src/OpenTelemetry.Instrumentation.StackExchangeRedis`
3. Run `dotnet list package --vulnerable --include-transitive` in the project directory

```
 dotnet list package --vulnerable --include-transitive

The following sources were used:
   https://api.nuget.org/v3/index.json

Project `OpenTelemetry.Instrumentation.StackExchangeRedis` has the following vulnerable packages
   [net462]: No vulnerable packages for this framework.
   [netstandard2.0]: No vulnerable packages for this framework.
   [net6.0]:
   Transitive Package           Resolved   Severity   Advisory URL
   > System.Drawing.Common      4.7.0      Critical   https://github.com/advisories/GHSA-rxg9-xrhp-64gj
```

### Expected Result

Version 4.7.2 or higher of `System.Drawing.Common` should be installed, or a version of `StackExchange.Redis` should be used that drops the dependency.

### Actual Result

Version 4.7.0 of `System.Drawing.Common` is installed

**Comment by vishweshbankwar** [comment]
@matt-hensley - Would you like to submit the PR for this?
