### ISSUE TITLE
Rename all projects to remove contrib word

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet-contrib#196]
Example: OpenTelemetry.Contrib.Instrumentation.MassTransit --> OpenTelemetry.Instrumentation.MassTransit
Changelog must be updated to indicated breaking name change, as nugets will be getting new name.

**Comment by cijothomas** [comment]
Contributing guide must be updated. Similarly, search if anything else might be broken by this and address them as well.

**Comment by reyang** [comment]
Couple things to consider:

Do we force existing packages to rename? It's probably not going to work for packages that are already marked as stable. 👀

How would the user know which package is backed by OpenTelemetry maintainers vs contrib maintainers? Are they have the same bar / recommendation?

**Comment by cijothomas** [comment]
> Do we force existing packages to rename? It's probably not going to work for packages that are already marked as stable. 👀

For non-stable packages, we can rename. For stable packages, we can leave as is. Will ask the owners to see if they want to rename and unlist old packages.

**Comment by cijothomas** [comment]
> How would the user know which package is backed by OpenTelemetry maintainers vs contrib maintainers? Do they have the same bar / recommendation?

The nuget shows the url of the repo, and user can infer which repo the package is coming from. But this topic requires a detailed discussion.

**Comment by utpilla** [comment]
We have already released two pre-release packages from the repo without the word "Contrib" in the name:

1. [OpenTelemetry.Instrumentation.Quartz](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Quartz/1.0.0-alpha.1)
2. [OpenTelemetry.Exporter.Stackdriver](https://www.nuget.org/packages/OpenTelemetry.Exporter.Stackdriver/1.0.0-beta.2)

We plan to rename and publish all the other components that have not had a stable release.

@srprash What's your take on this? Would you want to rename the AWS packages?

**Comment by cijothomas** [comment]
@srprash All packages except AWS packages are renamed. Could you comment here if there is a plan to rename AWS packages? If not, we can close this issue.

**Comment by srprash** [comment]
Hi @cijothomas Allow me to discuss this within the AWS X-Ray team and I'll get back to you.

**Comment by srprash** [comment]
Hi @cijothomas 
We will stick with the current package names until we have a major version to bump to. Feel free to close this issue.
Thanks.
