### ISSUE TITLE
`OTEL_DOTNET_EXPERIMENTAL_{component}_DISABLE_URL_QUERY_REDACTION` is not honored via `Configuration` for `Owin` and `AspNet` instrumentations

### ISSUE THREAD

**Issue by julealgon** [open-telemetry/opentelemetry-dotnet-contrib#1960]
### Component

OpenTelemetry.Instrumentation.Owin

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry.Instrumentation.Owin | 1.0.0-rc.6 |
| OpenTelemetry.Instrumentation.AspNet | 1.9.0-beta.1 |

### Runtime Version

net472

### Description

The recent `OTEL_DOTNET_EXPERIMENTAL_OWIN_DISABLE_URL_QUERY_REDACTION` and `OTEL_DOTNET_EXPERIMENTAL_ASPNET_DISABLE_URL_QUERY_REDACTION` flags are _only_ honored via environment variables and are ignored if provided via the `Configuration` subsystem.

This is contrary to how all other instrumentations work.

### Steps to Reproduce

1. Add either the Owin or AspNet instrumentations
2. Set the corresponding `OTEL_DOTNET_EXPERIMENTAL_{component}_DISABLE_URL_QUERY_REDACTION` variable via `Configuration`
3. Observe they have zero effect

### Expected Result

I would expect _all_ instrumentations to honor the `Configuration` mechanism if they are added via Hosting support even for legacy project types, as those can _still_ leverage the hosting abstraction at least partially.

### Actual Result

Redaction keeps happening even after setting `OTEL_DOTNET_EXPERIMENTAL_{component}_DISABLE_URL_QUERY_REDACTION` to `true` for either Owin or AspNet instrumentations when passing these configuration settings via `Configuration` instead of via environment variables.

### Additional Context

We have multiple `System.Web`-based applications today that either use raw frameworks (like WebForms) and use the AspNet instrumentation, or some legacy API projects which rely on the Owin abstractions and use the Owin instrumentation.

All of our projects use `Microsoft.Extensions.Hosting` abstractions to setup configuration, metrics, dependency injection and logging, and they use that to setup OpenTelemetry as well. Since we don't actually call `Run` on the built host, and thus never execute any hosted service, we manually resolve the `TraceProvider` and `MeterProvider` classes from the container and keep them as application-level fields to enable background monitoring of OpenTelemetry.

This approach has been working flawlessly for us and allows us to use `OpenTelemetry.Extensions.Hosting` on all of our projects, which provides for perfectly consistent usage/configuration.

However, when we wanted to re-enable querystring redaction after the latest security changes, we noticed that the configuration variables for those were not honored at all: after checking the implementation in the repo here, it became obvious why. Both the Owin and AspNet instrumentations don't even _have_ the same mechanism as the other instrumentations to create a configuration object and inject environment variables into them, like this:

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/7d03e00e63f9af05239069b5411d15fee1fc955f/src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreTraceInstrumentationOptions.cs#L19-L41

Instead, they just read directly from raw environment variables:
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/7d03e00e63f9af05239069b5411d15fee1fc955f/src/OpenTelemetry.Instrumentation.Owin/OwinInstrumentationOptions.cs#L19-L33

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/7d03e00e63f9af05239069b5411d15fee1fc955f/src/OpenTelemetry.Instrumentation.AspNet/AspNetTraceInstrumentationOptions.cs#L20-L34

This is a mistake and an unfortunate inconsistency IMHO. Just because someone is using one of these legacy frameworks, doesn't mean they are not using modern hosting or configuration libraries at the same time.

As a temporary workaround, I'll have to manually propagate some of our Azure AppConfig settings into local in-process environment variables for this to work properly, which increases maintenance for us unnecessarily.

We'd rather this worked out of the box, as it does with every other instrumentation package:
![image](https://github.com/user-attachments/assets/a531f103-4303-49fe-a959-87d1adffc5f7)

FYI @erricrice

**Comment by cijothomas** [comment]
question:

Is https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Extensions.Hosting expected to be used with Asp.Net app at all? [Asp.Net instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.AspNet), [examples ](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/examples/AspNet)- none of them show that pattern.

**Comment by julealgon** [comment]
> question:
> 
> Is https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Extensions.Hosting expected to be used with Asp.Net app at all? [Asp.Net instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.AspNet), [examples ](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/examples/AspNet)- none of them show that pattern.

I know this question wasn't for me, but I can suggest that this shouldn't concern the individual instrumentation packages themselves: note that the Http or Wcf or EntityFrameworkCore or any other instrumentations are agnostic of _how the are instantiated_, so they work with IConfiguration if present, and fallback to envvar if not.

I strongly believe this should be the case for _all_ instrumentations, even if they _normally_ aren't used with the Hosting package.

Again, keep in mind that people _can_ use parts of `Microsoft.Extensions.Hosting` anywhere. Either they use just DI, or they use DI + Configuration, or they use DI + Configuration + Logging, etc. This is what we are doing to modernize areas that can be modernized of our projects. We don't use the running parts of hosting however, like the hosted services mechanism, application lifetime, etc.

**Comment by cijothomas** [comment]
> but I can suggest that this shouldn't concern the individual instrumentation packages themselves: note that the Http or Wcf or EntityFrameworkCore or any other instrumentations are agnostic of how the are instantiated, so they work with IConfiguration if present, and fallback to envvar if not.
> 
> I strongly believe this should be the case for all instrumentations, even if they normally aren't used with the Hosting package.

Yes I agree with that. @CodeBlanch has designed the infra pieces (core api/sdk) with this in mind already. Don't think every instrumentation/component has fully embraced it yet.

**Comment by CodeBlanch** [comment]
So what the SDK does is make sure there is _always_ an `IConfiguration` available. In the case of `Microsoft.Extensions.Hosting` that `IConfiguration` is the host one. In the case of the "detached" build-up APIs ("Sdk.Create*" and "OpenTelemetrySdk.Create" being added in 1.10.0) the `IConfiguration` is created automatically from envvars.

Issue here seems to be Owin and AspNet aren't using the `IConfiguration`. My guess would be due to some static coupling. I'll take a quick look and see if there is a way to solve that.

**Comment by CodeBlanch** [comment]
@julealgon Here is a diff which should fix Owin: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/compare/main...CodeBlanch:owin-iconfiguration-support?expand=1

You have any bandwidth to run with that and take it to PR by chance? I'm pretty swamped at the moment.

AspNet package should be similar process just rinse and repeat 😄

**Comment by julealgon** [comment]
@CodeBlanch 
> You have any bandwidth to run with that and take it to PR by chance? I'm pretty swamped at the moment.

Not at the moment as I still need to run the CLA process through with my company. 

I figured I'd share the workaround we used though, just in case others end up running into the same issue while this gets worked on.

First, I created a simple extension method that I could easily call on 2 of our projects (one that uses Owin instrumentation, and another that uses the AspNet instrumentation):

```csharp
.ConfigureServices((context, services) =>
{
    services.AddOpenTelemetry()
        .PropagateLegacySettingsToEnvironmentVariables(context.Configuration)
        ...
        .ConfigureResource(c => c ...)
        .WithMetrics(m => m ...)
        .WithTracing(t => t ...)
        .UseOtlpExporter();
}
```

Code is fairly straightforward: just take the 2 "problematic" flags and forcibly set them as real environment variables in the process:
```csharp
public static IOpenTelemetryBuilder PropagateLegacySettingsToEnvironmentVariables(
    this IOpenTelemetryBuilder builder,
    IConfiguration configuration)
{
    ArgumentNullException.ThrowIfNull(builder);
    ArgumentNullException.ThrowIfNull(configuration);

    ReadOnlySpan<string> legacySettingNames = [
        "OTEL_DOTNET_EXPERIMENTAL_ASPNET_DISABLE_URL_QUERY_REDACTION",
        "OTEL_DOTNET_EXPERIMENTAL_OWIN_DISABLE_URL_QUERY_REDACTION",
        ];

    foreach (var settingName in legacySettingNames)
    {
        if (configuration[settingName] is string settingValue)
        {
            Environment.SetEnvironmentVariable(settingName, settingValue);
        }
    }

    return builder;
}
```

Once this is fixed, we'll drop the extension without too much impact if at all.
