### ISSUE TITLE
Does this RPO have a downloadable Nuget package?

### ISSUE THREAD

**Issue by czs1993** [open-telemetry/opentelemetry-dotnet-contrib#20]
The Instrumentation  of EF  is  merged, Does it have a downloadable Nuget package?

**Comment by eddynaka** [comment]
@czs1993 , we didn't publish any release (alpha/beta) yet. But, if you want to test, you can download the latest package from here: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/runs/928712466 (download the artifacts, there you will see the nupkg files).

**Comment by czs1993** [comment]
@eddynaka  thanks, Are there any plans to publish a release package?

**Comment by eddynaka** [comment]
@czs1993 , I think we will discuss that tomorrow on the .NET SIG. I'll keep you posted.

**Comment by czs1993** [comment]
@eddynaka the .NET SIG has any discussion result? the contrib repo will  as same as official repo  to publish a release package on Nuget ?

**Comment by eddynaka** [comment]
@czs1993 , we started the discussion but we didn't have a final answer for it. I just created a new issue where you can follow this: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1030.

**Comment by Mistic92** [comment]
Hi, is there any update? We wanted to use Stackdriver exporter but it's not available on nuget and README have wrong instruction

**Comment by eddynaka** [comment]
Hi all, we just published the packages: https://www.nuget.org/profiles/OpenTelemetry
