### ISSUE TITLE
Support for Azure Container Apps Jobs

### ISSUE THREAD

**Issue by hansmbakker** [open-telemetry/opentelemetry-dotnet-contrib#2036]
### Component

OpenTelemetry.Resources.Azure

### Is your feature request related to a problem?

In https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1565, an `AzureContainerAppsResourceDetector` for Azure Container Apps (ACA) was added.

It works well for normal ACA resources, but seems not to support [ACA **Jobs**](https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-cli).

In my application insights, the normal container app is recognized but the program running in an ACA Job is shown as `unknown_service:dotnet`.

### What is the expected behavior?

ACA Job resources are detected correctly similar to regular ACA apps, i.e. the `service.name`, `service.version`, `service.instance.id`, `cloud.provider` and `cloud.platform` properties are set.

### Which alternative solutions or features have you considered?

A temporary workaround could be - setting these properties manually.

**Comment by Kielek** [comment]
@rajkumar-rangaraj, could you pleas check?

**Comment by vRune4** [comment]
I just bumped into the same issue myself.

I used to initialize OT this way because some guy on the Internet recommended it:

```csharp
 string? roleName = Globals.Configuration.GetValue<string>("CloudRoleName");
 if (!string.IsNullOrWhiteSpace(roleName))
 {
     services.ConfigureOpenTelemetryTracerProvider((services, builder) => builder.ConfigureResource(rb => rb.AddAttributes([new("service.name", roleName)])));
}
```

But best case it was ignored, worst case an exception was thrown.

**Comment by rajkumar-rangaraj** [comment]
@hansmbakker  At the moment, there is no support for resource detection specific to Azure Container Apps (ACA) jobs within the `OpenTelemetry.Resources.Azure` component. Currently, we do not have any immediate plans to implement this functionality.

**Comment by vRune4** [comment]
I phoned a friend who suggested the following:

```csharp
string? appInsightsConnectionString = hostBuilder.Configuration.GetConnectionString("ApplicationInsights");
if (!string.IsNullOrWhiteSpace(appInsightsConnectionString))
{
    hostBuilder.Services.AddOpenTelemetry()
        .UseAzureMonitor(opt => { opt.Credential = credential; opt.ConnectionString = appInsightsConnectionString; })
        .ConfigureResource(resourceBuilder => resourceBuilder.AddAttributes(new Dictionary<string, object> {
                                                                                { "service.name", Environment.GetEnvironmentVariable("CONTAINER_APP_JOB_NAME") ?? "" },
                                                                                { "service.version", Environment.GetEnvironmentVariable("CONTAINER_APP_JOB_EXECUTION_NAME") ?? "" }
                                                                            }));
}
```

The container job has different environment variables set compared to a container app.

**Comment by hansmbakker** [comment]
I created https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/2064
@Kielek @rajkumar-rangaraj could you please pick this up further?
