### ISSUE TITLE
Provide .NET Runtime instrumentation libraries

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet-contrib#204]
# Feature Request

.NET has several runtime metrics exposed via EventCounters https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/RuntimeEventSource.cs.

In the near future it is impossible for .NET runtime to completely switch over to the Meter API since these APIs are not backported to old versions of runtime.

**Describe the solution you'd like:**

The ask here is to provide an instrumentation library which exposes runtime metrics via Meter API, so users who need these could leverage them without having to use EventCounter wrappers.

**Describe alternatives you've considered.**

Leveraging something like https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/177 or having the users implementing the Meter/Instrument by themselves.

Leveraging the EventCounter listener/adapter has lots of problems with the scheduling - EventCounters would require the user to configure the polling schedule, which makes it less efficient for pull exporters (e.g. Prometheus), and hard to manage for push exporters (e.g. if OTLP exporter is exporting every 10 seconds, what's the proper polling period for EventCounters?)

**Comment by twenzel** [comment]
I would like to contribute to this issue. I'll try to create a PR in the next days.

**Comment by steinarox** [comment]
Nice to see i am not the only one that looks for this 😎 
For UX i like the [prometheus-net instrumentation](https://github.com/djluck/prometheus-net.DotNetRuntime#start-collecting-metrics) where you can add all or some groups of "default" metrics

**Comment by omamoo** [comment]
@reyang Thanks for the sharing with this feature request, It will be useful so much to  add such kind of instrumentation.

**Comment by twenzel** [comment]
@reyang Can this be closed?

**Comment by reyang** [comment]
@twenzel it's not 100% done but I think YES we should close it and iterate on your contributions. Thank you @twenzel for leading this effort!
