### ISSUE TITLE
[repo] Ping component owners when issue is created

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-contrib#2110]
### Component

None

### Is your feature request related to a problem?

When the new issue is created the component owners are no informed.
The exception is only for release requests issue.

### What is the expected behavior?

When the new issue is created component owners (without approvers/maitainers) of the given packages should be informed (pinged by `@user` by the opentelemetrybot.

For release cases component owners are pinged also for modification of the issue.

Ref: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/2103#issuecomment-2372514092

### Which alternative solutions or features have you considered?

Currently, we manually inform component owners for important cases.

**Comment by Kielek** [comment]
@CodeBlanch, what do you think?

**Comment by CodeBlanch** [comment]
Sounds good to me! I'll work on it soon.
