### ISSUE TITLE
[sql] Update semantic conventions for stable release

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet-contrib#2207]
We need to update `OpenTelemetry.Instrumentation.SqlClient` for the [pending] stable semantic conventions.

Migration guide: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/non-normative/db-migration.md

Metrics: #2026
Traces: TBD

/cc @trask @lmolkova

**Comment by alanwest** [comment]
Closing this issue. I've begun breaking this down into other issues which I'm tracking in this [milestone](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/milestone/6).
