### ISSUE TITLE
[bug] SqlClient Instrumentation cannot get CommandText

### ISSUE THREAD

**Issue by Robert-Chan** [open-telemetry/opentelemetry-dotnet-contrib#2287]
### Component

OpenTelemetry.Instrumentation.SqlClient

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry.Api                     | 1.9.0   |
| OpenTelemetry                         | 1.9.0   |
| OpenTelemetry                         | 1.9.0-beta.1 |

### Runtime Version

net48

### Description

I hava dubuged the source code of OpenTelemetry.Instrumentation.SqlClient.
Got dasource,database, but no commandText.  We use EntityFramework6.
![image](https://github.com/user-attachments/assets/2f8a417c-6c16-40e7-b545-e467daf142e3)

### Steps to Reproduce

As description

### Expected Result

Get SQL statement and send to telemetry endpoint

### Actual Result

cannot get sql CommandText

**Comment by adamratson** [comment]
Hey, I ran into a similar issue recently - I found by using `Microsoft.Data.SqlClient` instead I got the full command text.

There is a note in the README that implies that command text is not available using `System.Data.SqlClient`

`When using the built-in System.Data.SqlClient only stored procedure command names will ever be captured. When using the Microsoft.Data.SqlClient NuGet package (v1.1+) stored procedure command names, full query text, and other command text will be captured.`

(Last note under this section https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.SqlClient/README.md)
