### ISSUE TITLE
Resources.AWS - support .NET9

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-contrib#2323]
Resources.AWS - support .NET9

_Originally posted by @Kielek in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/2313#discussion_r1842943812_

**Comment by Kielek** [comment]
@ppittle, FYI

**Comment by ppittle** [comment]
> @ppittle, FYI
Do you know what the failure(s) were?

I'm looking in #2313, but there's a lot in thre.

**Comment by Kielek** [comment]
The PR is ready to review. #2328
