### ISSUE TITLE
[Geneva exporter] Retry exporting logs upon failure

### ISSUE THREAD

**Issue by ItalyPaleAle** [open-telemetry/opentelemetry-dotnet-contrib#2352]
### Component

OpenTelemetry.Exporter.Geneva

### Is your feature request related to a problem?

If the Geneva collector is temporarily unavailable (or not ready yet), the Geneva exporter silently drops logs. This is causing issues especially during startup.

Note we are using the collector on Linux (mdsd)

### What is the expected behavior?

Two things:

1. Geneva exporter should retry sending logs to the collector if they fail. Retries should ideally be configurable (max attempts and interval)
2. Upon startup, Geneva exporter should wait if the connection isn't available

### Which alternative solutions or features have you considered?

This is especially an issue during startup, since the mdsd sidecar may come online a few seconds after the app. The naive solution is to add a delay before the app starts, but that's very frail (and causes further delay before the app is ready to serve traffic)

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/939#pullrequestreview-1276255114 As mentioned here, the long term plan for the exporter is to use OS native tracing mechanisms and won't require retry/back-pressure handling.

**Comment by ItalyPaleAle** [comment]
@cijothomas thanks, do you have an ETA for that? Or is there a workaround? This is likely causing us to lose logs at the moment

**Comment by cijothomas** [comment]
We are already there for Windows (with ETW), and moving towards there in linux (Metrics just added support for exporting via user_evengs in linux). No ETA unfortunately, as this depends a lot of Linux kernel capabilities (that are relatively new).

It is definitely possible to add retries for Linux, but given this is not aligned with the long term direction, unlikely to happen.

I don't have a concrete suggestion other than ensuring that the listening agents (Microsoft agents or OTel collector or anything else) are up & running before the apps that depend on them start up. This will be a requirement even if we move to OS native tracing mechanisms..

**Comment by ItalyPaleAle** [comment]
> I don't have a concrete suggestion other than ensuring that the listening agents (Microsoft agents or OTel collector or anything else) are up & running before the apps that depend on them start up. This will be a requirement even if we move to OS native tracing mechanisms..

The problem with this approach is that if the listening agents are deployed as sidecars (which is the only way supported in Web Apps on Linux), then we don't really have control over the lifecycle (we use the Microsoft internal agent mdsd). We worked around this issue quickly for now by just delaying the startup of the app by 3s, which seems to be sufficient in most cases, but it's not guaranteed.

Perhaps the Geneva exporter could at least add support for an initial "hold" time if the socket isn't available?

**Comment by cijothomas** [comment]
I'd suggest to follow up internally for the agent startup issue.
