### ISSUE TITLE
Naming suggestions for the Preview package

### ISSUE THREAD

**Issue by utpilla** [open-telemetry/opentelemetry-dotnet-contrib#263]
With #196, we would be removing the word "Contrib" from [OpenTelemetry.Contrib.Preview](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Contrib.Preview) package.

Do we want to publish the new package as `OpenTelemetry.Preview`? Or do we want to rename it to something else like `OpenTelemetry.Extensions.Preview`?

Please provide suggestions for a new name, if you have any.

**Comment by CodeBlanch** [comment]
I like `OpenTelemetry.Extensions.Preview`. Just randomly noticed on the java repo the other day they have "extensions" for API & SDK: https://github.com/open-telemetry/opentelemetry-java#overview

Sticking with "extensions" seems reasonable to me.

**Comment by cijothomas** [comment]
`OpenTelemetry.Extensions` is my suggestion. (version name already indicate "non stable").

**Comment by Kielek** [comment]
Rename done in #266. Closing.
