### ISSUE TITLE
Unable to see MSMQ traces in Zipkin or Jaeger

### ISSUE THREAD

**Issue by spanhotra** [open-telemetry/opentelemetry-dotnet-contrib#270]
I have implemented the following

Publisher
Service1 -> publishing message -> MSMQ

Subscriber
MSMQ -> Rabbit Listeners -> Service2

It is working great!!

But I want to see this interaction in the trace on zipkin or Jaeger, I am unable to find the AMQP queries, only Http are there.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/examples/MicroserviceExample - Please take a look at this example.

**Comment by spanhotra** [comment]
Thanks for the link.
