### ISSUE TITLE
Error 1022 when instrumenting This example

### ISSUE THREAD

**Issue by jwarfieldpwny** [open-telemetry/opentelemetry-dotnet-contrib#272]
Hello, 

I have been trying for some time to instrument a WCF application. After not getting much success I finally decided to download the example here and attempt to simply run that. An associate recommended posting here for assistance. 

In every instance I run in to the same issue, I am unable to get any spans emitted (verified with Zpages) and I receive the same error in the logs 

.NET Runtime version 4.0.30319.0 - Loading profiler failed during CoCreateInstance.  Profiler CLSID: '{B4C89B0F-9908-4F73-9F59-0D77C5A06874}'.  HRESULT: 0x80040154.  Process ID (decimal): 12024.  Message ID: [0x2504].

I have tried to identify this CLSID and been unable to find its origination point. As expected from the HRESULT there is no COM Object registered with the CLSID. 

Enviornment: 

 .NET Framework 4.6.2.
IIS Express - 10.022489.1000
Windows 10 Enterprise Edition V-21H2

Any assistance would be greatly appreciated.

**Comment by pjanotti** [comment]
@jwarfieldpwny the CLSID above is for https://github.com/signalfx/signalfx-dotnet-tracing are you trying to use it in conjunction with OpenTelemetry instrumentation?

The error 0x80040154 indicates that the expected profiler was not installed. It seems a setup error if you set COR_PROFILER_ENABLED=0 you won't see the same error but I am not sure of your scenario.

**Comment by reyang** [comment]
@jwarfieldpwny is this an issue while trying to use [auto-instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation)?

**Comment by Kielek** [comment]
@jwarfieldpwny, I am closing issue as we do not have any feedback from your side.

Please reopen/comment if we can help you.
