### ISSUE TITLE
Use file scoped namespace statements

### ISSUE THREAD

**Issue by mic-max** [open-telemetry/opentelemetry-dotnet-contrib#276]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces

**Comment by tony21921** [comment]
I am new to this project. I'd like to work on this for the [Extensions](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Extensions)
