### ISSUE TITLE
PassThru TableNameMappings using the logger category name.

### ISSUE THREAD

**Issue by Yun-Ting** [open-telemetry/opentelemetry-dotnet-contrib#289]
For large organizations, there might be multiple teams owning different components (e.g. Team A owns library X, team B owns library Y, team C owns application Z which depends on X and Y). It could help to increase the efficiency if each team can introduce new log categories without having the application owner to update the exporter configuration.

For example, if team B introduced "TeamB.NewFeature" category, currently team A has to update their code:

```csharp
exporterOptions.TableNameMappings = new Dictionary<string, string>
{
    ["Grocery.FoodCategory"] = "Food",
    ["Grocery.OperationCategory"] = "Operation",
+   ["TeamB.NewFeature"] = "TeamBNewFeature",
};
```

The ask is to implement an opt-in feature, which allows the default mapping based on category name. So Team A and B can add new logger categories - without having team C to update the exporter configuration - if team C has the exporter configured as:

```csharp
exporterOptions.TableNameMappings = new Dictionary<string, string>
{
    ["Grocery.FoodCategory"] = "Food",
    ["Grocery.OperationCategory"] = "Operation",
    ["*"] = "*",
};
```

The proposed behavior of `["*"] = "*"`:

* It is opt-in.
* It has the lowest priority - it should only take effect when other rules don't apply to a given logger category name.
* It would map the logger category to a table name that follows the Rule `event-name      = uppercase-alpha ( ALPHA / DIGIT) * ; [A-Z][A-Za-z0-9]* `, with the following additions:
  1. Any character that is not allowed will be removed.
  2. If the resulting string is longer than 50 characters, only the first 50 characters will be taken.
  3. If the first character in the resulting string is lower-case ALPHA, it will be converted to the corresponding upper-case.
  4. If the resulting string is still does not comply with Rule, the data will get dropped on the floor.

For example:
* If the logger category name is "TeamA.NewFeature", the output table name will be "TeamANewFeature".
* If the logger category name is "1.2", the data will be dropped on the floor as the exporter cannot deduce a valid table name.
* If there are two logger categories "AB.C" and "A.BC", both would map to "ABC".
* If there are two logger categories "AB.c" and "A.bC", they would map to "ABc" and "AbC", the final/end-to-end behavior will depend on the agent and backend.

**Comment by jviau** [comment]
What if Team B wants to use multiple different category names and wants all the logs grouped into the same table? And they want to be able to add new category names in the future without Team A changing their config and having the names also map to the same table?

Could we use a globbing syntax? Or a matching like log filters (although that would change current behavior, which may be a no go).

``` CSharp
exporterOptions.TableNameMappings = new Dictionary<string, string>
{
    ["Grocery.FoodCategory"] = "Food",
    ["Grocery.OperationCategory"] = "Operation",
+   ["TeamB.*"] = "TeamB",
};
```
Now any log category that is either `TeamB` exactly or starts with `TeamB.` will be mapped to the `TeamB` category.

**Comment by Yun-Ting** [comment]
Closing the issue as PR was merged: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/345.
[jviau](https://github.com/jviau), could you open a separate ask to track the above ask? Thank you.

**Comment by CodeBlanch** [comment]
@jviau FYI your use case should now be covered by #796
