### ISSUE TITLE
Bringing .NET Runtime metrics instrumentation to Stable

### ISSUE THREAD

**Issue by xiang17** [open-telemetry/opentelemetry-dotnet-contrib#335]
Opening an issue for gaining feedbacks and making improvements on .NET Runtime metric instrumentation, regarding which metrics to expose, what each metrics means exactly, and how to calculate/fetch each metrics along with clear documentation for each metrics.

The goal is to have well defined and documented metrics for .NET Runtime users to have better knowledge of a system in a user-friendly way, in order to get the Runtime metrics instrumentation library to a stable stage.

Currently the Runtime metrics already works upon finish of the issue #204, but it's still in Alpha stage. The metrics instrumentations are initiated in [`RuntimeMetrics.cs`](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs). The metrics are mostly from EventCounters: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/RuntimeEventSource.cs

# UI

The primary goal is to provide enable users to utilize user-friendly UI to gain insights in .NET Runtime behavior. Here is a simple demo for the concept. The Grafana dashboard graphs I set up in my laptop look this (see appendix on how to do it):
![Dotnet-Grafana](https://user-images.githubusercontent.com/9310587/166079695-6617614e-69ab-43d4-844f-3414d40c3556.png)

Or this:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/9310587/166079722-2ad30203-164e-45a1-9139-dccaaa60469c.png)

# Metrics

*TODO*: List of metrics grouped in CPU, Memory, Garbage Collection, Threadpool, Process, and etc.

# Documentation

Clear description on what each metric means. Given that developers and support engineers might rely on this to debug or diagnose issues, the description should reveal reasonably enough insight into internal details.

Help from Runtime team is appreciated especially for this part.

# Appendix

Instruction on how to set up the graphs:
1. Set up Prometheus and Grafana using [this guide](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/getting-started-prometheus-grafana).
2. Configure `AddRuntimeMetrics` in the Program.cs code according to the Runtime instrumentation library [readme](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Runtime).

```
using var meterProvider = Sdk.CreateMeterProviderBuilder()
    .AddMeter("MyCompany.MyProduct.MyLibrary")
    .AddRuntimeMetrics()
    .AddPrometheusExporter(options => { options.StartHttpListener = true; })
    .Build();
```

**Comment by xiang17** [comment]
Here is a doc for the description for existing metrics and a bunch of TODO items. (I'm not sure whether it's better to place it in a markdown file in the folder since it's very long, or to keep it in issue since there are lots of TODO items.)

# Runtime metrics description

Metrics name are prefixed with the `process.runtime.dotnet.` namespace, following
the general guidance for runtime metrics in the
[specs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#runtime-environment-specific-metrics---processruntimeenvironment).
Instrument Units [should follow](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md#instrument-units)
the Unified Code for Units of Measure.

## RuntimeMetricsOptions.IsGcEnabled

| Name | Description | Instrument | Unit ([UCUM](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md#instrument-units)) | ObserveValue |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| process.runtime.dotnet.**gc.heap** | GC Heap Size | ObservableGauge  | `By` | GC.GetTotalMemory(false) |
| process.runtime.dotnet.**gen_0-gc.count** | Gen 0 GC Count | ObservableGauge | Count | GC.CollectionCount(0) |
| process.runtime.dotnet.**gen_1-gc.count** | Gen 1 GC Count | ObservableGauge | Count | GC.CollectionCount(1) |
| process.runtime.dotnet.**gen_2-gc.count** | Gen 2 GC Count | ObservableGauge | Count | GC.CollectionCount(2) |

- [GC.GetTotalMemory](https://docs.microsoft.com/dotnet/api/system.gc.gettotalmemory):
The number of bytes currently thought to be allocated.
It does not wait for garbage collection to occur before returning.

- [GC.CollectionCount](https://docs.microsoft.com/dotnet/api/system.gc.collectioncount):
The number of times garbage collection has occurred for the specified generation
of objects.

### Additional GC metrics only available for NETCOREAPP3_1_OR_GREATER

| Name | Description | Instrument | Unit ([UCUM](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md#instrument-units)) | ObserveValue |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| process.runtime.dotnet.**alloc.rate** | Allocation Rate | ObservableCounter | `By` | GC.GetTotalAllocatedBytes() |
| process.runtime.dotnet.**gc.fragmentation** | GC Fragmentation | ObservableCounter (TODO: change to ObservableGauge?) | Count | *this.GetFragmentation* |

- [GC.GetTotalAllocatedBytes](https://docs.microsoft.com/dotnet/api/system.gc.gettotalallocatedbytes):
  Gets a count of the bytes allocated over the lifetime of the process. The returned
value does not include any native allocations. The value is an approximate count.

- *this.GetFragmentation*: If `GC.GetGCMemoryInfo().HeapSizeBytes != 0`,
the value is
`GC.GetGCMemoryInfo().FragmentedBytes * 100d / GC.GetGCMemoryInfo().HeapSizeBytes`,
else `0`.

  [GCMemoryInfo.FragmentedBytes](https://docs.microsoft.com/dotnet/api/system.gcmemoryinfo.fragmentedbytes?view=netcore-3.1):
  Gets the total fragmentation when the last garbage collection occurred.
  Divived by [GCMemoryInfo.HeapSizeBytes](https://docs.microsoft.com/dotnet/api/system.gcmemoryinfo.heapsizebytes?view=netcore-3.1#system-gcmemoryinfo-heapsizebytes),
  which is the total heap size when the last garbage collection occurred.

**TODO**: [Question] Why is it multiplied by `100d`?

**TODO**: [Question] Shouldn't it be `ObservableGauge` for fragmentation?
A garbage collection should reset the value, so it is not monotonically increasing
value(s) as `ObservableCounter` should be.
See [Asynchronous Counter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-counter)
vs [Asynchronous Gauge](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-gauge).

### Additional GC metrics only available for NET6_0_OR_GREATER

| Name | Description | Instrument | Unit ([UCUM](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md#instrument-units)) | ObserveValue |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| process.runtime.dotnet.**gc.committed** | GC Committed Bytes | ObservableCounter | `Mi` | `(double)(GC.GetGCMemoryInfo().TotalCommittedBytes / 1_000_000)` |

[GCMemoryInfo.TotalCommittedBytes](https://docs.microsoft.com/dotnet/api/system.gcmemoryinfo.totalcommittedbytes?view=net-6.0#system-gcmemoryinfo-totalcommittedbytes):
Gets the total committed bytes of the managed heap.

**TODO**: Use the units consistently.
According to the [Prefixes and units usedin Information Technology section](https://ucum.org/ucum.html#section-Prefixes-and-Units-Used-in-Information-Technology)
of UCUM, `Mi` is a prefix, meaning 1048576 rather than 1000000.
So here it should use `MiBy` for `mebibyte`, to be consistent with the "c/s"
(case insensitive) form used in
[JVM metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#jvm-metrics).

## RuntimeMetricsOptions.IsJitEnabled (only available for NET6_0_OR_GREATER)

| Name | Description | Instrument | Unit ([UCUM](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md#instrument-units)) | ObserveValue |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| process.runtime.dotnet.**il.bytes.jitted** | IL Bytes Jitted | ObservableCounter | `By` | System.Runtime.JitInfo.GetCompiledILBytes() |
| process.runtime.dotnet.**methods.jitted.count** | Number of Methods Jitted | ObservableCounter | Count | System.Runtime.JitInfo.GetCompiledMethodCount() |
| process.runtime.dotnet.**time.in.jit** | Time spent in JIT | ObservableGauge | `ms` | System.Runtime.JitInfo.GetCompilationTime().TotalMilliseconds |

[JitInfo.GetCompiledILBytes](https://docs.microsoft.com/dotnet/api/system.runtime.jitinfo.getcompiledilbytes?view=net-6.0#system-runtime-jitinfo-getcompiledilbytes(system-boolean)):
Gets the number of bytes of intermediate language that have been compiled.
The scope of this value is global.

[JitInfo.GetCompiledMethodCount](https://docs.microsoft.com/dotnet/api/system.runtime.jitinfo.getcompiledmethodcount?view=net-6.0#system-runtime-jitinfo-getcompiledmethodcount(system-boolean)):
Gets the number of methods that have been compiled.
The scope of this value is global.

[JitInfo.GetCompilationTime](https://docs.microsoft.com/dotnet/api/system.runtime.jitinfo.getcompilationtime?view=net-6.0#system-runtime-jitinfo-getcompilationtime(system-boolean)):
Gets the amount of time the JIT Compiler has spent compiling methods.
The scope of this value is global.

**TODO**: [Question] Why is the last one `ObservableGauge`? I think it should be `ObservableCounter`
like the other two.
See [Asynchronous Counter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-counter)
vs [Asynchronous Gauge](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-gauge).

## RuntimeMetricsOptions.IsThreadingEnabled (only available for NETCOREAPP3_1_OR_GREATER)

| Name | Description | Instrument | Unit ([UCUM](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md#instrument-units)) | ObserveValue |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| process.runtime.dotnet.**monitor.lock.contention.count** | Monitor Lock Contention Count | ObservableGauge | Count | Monitor.LockContentionCount |
| process.runtime.dotnet.**threadpool.thread.count** | ThreadPool Thread Count | ObservableCounter | Count | ThreadPool.ThreadCount |
| process.runtime.dotnet.**threadpool.completed.items.count** | ThreadPool Completed Work Item Count | ObservableGauge | Count | ThreadPool.CompletedWorkItemCount |
| process.runtime.dotnet.**threadpool.queue.length** | ThreadPool Queue Length | ObservableCounter | Count | ThreadPool.PendingWorkItemCount |
| process.runtime.dotnet.**active.timer.count** | Number of Active Timers | ObservableCounter | Count | Timer.ActiveCount |

- [Monitor.LockContentionCount](https://docs.microsoft.com/dotnet/api/system.threading.monitor.lockcontentioncount?view=netcore-3.1):
  Gets the number of times there was contention when trying to take the monitor's
  lock.
- [ThreadPool.ThreadCount](https://docs.microsoft.com/dotnet/api/system.threading.threadpool.threadcount?view=netcore-3.1):
  Gets the number of thread pool threads that currently exist.
- [ThreadPool.CompletedWorkItemCount](https://docs.microsoft.com/dotnet/api/system.threading.threadpool.completedworkitemcount?view=netcore-3.1):
  Gets the number of work items that have been processed so far.
- [ThreadPool.PendingWorkItemCount](https://docs.microsoft.com/dotnet/api/system.threading.threadpool.pendingworkitemcount?view=netcore-3.1):
  Gets the number of work items that are currently queued to be processed.
- [Timer.ActiveCount](https://docs.microsoft.com/dotnet/api/system.threading.timer.activecount?view=netcore-3.1):
  Gets the number of timers that are currently active. An active timer is registered
  to tick at some point in the future, and has not yet been canceled.

**TODO**: None of these should be ObservableCounter which is monotonically increasing.

## RuntimeMetricsOptions.IsProcessEnabled

| Name | Description | Instrument | Unit ([UCUM](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md#instrument-units)) | ObserveValue |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| process.cpu.time | Processor time of this process | ObservableCounter | `s` | *this.GetProcessorTimes* |
| process.cpu.count | The number of available logical CPUs | ObservableGauge | Count | Environment.ProcessorCount |
| process.memory.usage | The amount of physical memory in use | ObservableGauge | `By` | Process.GetCurrentProcess().WorkingSet64 |
| process.memory.virtual | The amount of committed virtual memory | ObservableGauge | `By` | Process.GetCurrentProcess().VirtualMemorySize64 |

- *this.GetProcessorTimes*: `IEnumerable<Measurement<double>>` of
Process.GetCurrentProcess().UserProcessorTime.TotalSeconds and
Process.GetCurrentProcess().PrivilegedProcessorTime.TotalSeconds.

- [Process.TotalProcessorTime](https://docs.microsoft.com/dotnet/api/system.diagnostics.process.totalprocessortime):
  Gets the total processor time for this process.
- [Process.PrivilegedProcessorTime](https://docs.microsoft.com/dotnet/api/system.diagnostics.process.privilegedprocessortime):
  Gets the privileged processor time for this process.
- [Environment.ProcessorCount](https://docs.microsoft.com/dotnet/api/system.environment.processorcount):
  Gets the number of processors available to the current process.
- [Process.GetCurrentProcess().WorkingSet64](https://docs.microsoft.com/dotnet/api/system.diagnostics.process.workingset64):
  Gets the amount of physical memory, in bytes, allocated for the currently
  active process.
- [Process.GetCurrentProcess().VirtualMemorySize64](https://docs.microsoft.com/dotnet/api/system.diagnostics.process.virtualmemorysize64):
  Gets the amount of the virtual memory, in bytes, allocated for the currently
  active process.

## RuntimeMetricsOptions.IsAssembliesEnabled

| Name | Description | Instrument | Unit ([UCUM](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md#instrument-units)) | ObserveValue |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| process.runtime.dotnet.**assembly.count** | Number of Assemblies Loaded | ObservableCounter | Count | AppDomain.CurrentDomain.GetAssemblies().Length |

- [AppDomain.GetAssemblies](https://docs.microsoft.com/dotnet/api/system.appdomain.getassemblies):
  Gets the number of the assemblies that have been loaded into the execution context
  of this application domain.

## List of the metrics in RuntimeEventSource

The [issue](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/204)
provided that
.NET has several runtime metrics exposed via EventCounters https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/RuntimeEventSource.cs

| Name | Description |  Status |
| ------------- | ------------- | ------------- |
| cpu-usage | RuntimeEventSourceHelper.GetCpuUsage() | TODO |
| working-set | ((double)Environment.WorkingSet / 1_000_000) | TODO |
| gc-heap-size | ((double)GC.GetTotalMemory(false) / 1_000_000) | Included |
| gen-0-gc-count | GC.CollectionCount(0) | Included |
| gen-1-gc-count | GC.CollectionCount(1) | Included |
| gen-2-gc-count | GC.CollectionCount(2) | Included |
| threadpool-thread-count | ThreadPool.ThreadCount | Included |
| monitor-lock-contention-count | Monitor.LockContentionCount | Included |
| threadpool-queue-length | ThreadPool.PendingWorkItemCount | Included |
| threadpool-completed-items-count | ThreadPool.CompletedWorkItemCount | Included |
| alloc-rate | GC.GetTotalAllocatedBytes() | Included |
| active-timer-count | Timer.ActiveCount | Included |
| gc-fragmentation | this.fragmentation() | Included |
| gc-committed | ((double)GC.GetGCMemoryInfo().TotalCommittedBytes / 1_000_000) | Included |
| exception-count | Exception.GetExceptionCount() | TODO |
| time-in-gc | GC.GetLastGCPercentTimeInGC() | TODO |
| gen-0-size | GC.GetGenerationSize(0) | TODO |
| gen-1-size | GC.GetGenerationSize(1) | TODO |
| gen-2-size | GC.GetGenerationSize(2) | TODO |
| loh-size | GC.GetGenerationSize(3) | TODO |
| poh-size | GC.GetGenerationSize(4) | TODO |
| assembly-count | System.Reflection.Assembly.GetAssemblyCount() | TODO |
| il-bytes-jitted | System.Runtime.JitInfo.GetCompiledILBytes() | Included |
| methods-jitted-count | System.Runtime.JitInfo.GetCompiledMethodCount() | Included |
| time-in-jit | System.Runtime.JitInfo.GetCompilationTime().TotalMilliseconds | Included |

**Comment by Kielek** [comment]
@xiang17, when you will have agreement here. It will be great to put the specification under https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#runtime-environment-specific-metrics---processruntimeenvironment

Java is already documented here.

**Comment by xiang17** [comment]
The 1.0.0 version has been released: https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Runtime

**Comment by dmitriy-shleht** [comment]
@xiang17 Please share this template

![image](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/assets/13961834/f929dca9-0502-4cd6-a78f-4fc94bfa771d)
