### ISSUE TITLE
AWS Lambda support for extraction of W3C trace headers sent over http

### ISSUE THREAD

**Issue by khpeet** [open-telemetry/opentelemetry-dotnet-contrib#343]
# Issue with OpenTelemetry.Contrib.Instrumentation.AWSLambda

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

```
    <PackageReference Include="OpenTelemetry.Contrib.Instrumentation.AWS" Version="1.0.1" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.1.0-beta1" />
    <PackageReference Include="OpenTelemetry.Contrib.Instrumentation.AWSLambda" Version="1.1.0-beta1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc8" />
```

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

`netcoreapp3.1`

**Is this a feature request or a bug?**

* [x] Feature Request
* [ ] Bug

**What is the expected behavior?**

Incoming http W3C trace headers are extracted and added to the active span created. Currently only headers from X-Ray are extracted according to the comments [in this method](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/fe42963cf05aa65d1eb58b7b32f0857245f4e50a/src/OpenTelemetry.Contrib.Instrumentation.AWSLambda/Implementation/AWSLambdaUtils.cs#L48).

**What is the actual behavior?**
I am sending `traceparent` and `tracestate` headers from a client SPA to an AWS dotnetcore3.1 Lambda using this wrapper. Currently the trace context sent via HTTP headers are not automatically extracted via this wrapper, thus I have reverted to not use this wrapper and am manually creating my own Spans/extraction of context.

**Comment by khpeet** [comment]
@srprash -- @alanwest recommended to tag you

**Comment by jmpf2019** [comment]
I'm also experiencing the same issue with a project I'm working with. Hope this can be solved soon.

**Comment by srprash** [comment]
Hi @khpeet and @jmpf2019 
Thanks for opening this feature request. Adding support for W3C in the AWS Lambda instrumentation is on our backlog, however I cannot provide and ETA for it at the moment. I will provide an update as soon as possible.

**Comment by jmpf2019** [comment]
Hi @srprash, same as previous comment ^, checking if there's any progress on this.

**Comment by Oberon00** [comment]
This should now be implemented by #408, check the release notes of 1.1.0-beta.2 here: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md

**Comment by Oberon00** [comment]
Can someone with permissions please close this issue? See my previous comment.

**Comment by Kielek** [comment]
Closing per @Oberon00 comment.
