### ISSUE TITLE
[Exporter.Geneva] Add support for ILogger scopes

### ISSUE THREAD

**Issue by utpilla** [open-telemetry/opentelemetry-dotnet-contrib#389]
Add support for exporting ILogger scopes using `GenevLogExporter`.

**Comment by yasmolya** [comment]
Can you clarify if ILogger scopes are released as stable version? What version is it? 
Is there a documentation, some best practices/examples?

**Comment by utpilla** [comment]
> Can you clarify if ILogger scopes are released as stable version? What version is it? Is there a documentation, some best practices/examples?

@yasmolya There is no stable version of GenevaExporter supporting scopes yet. We recently updated the export logic for scopes. Refer to this PR #736. This change is shipped as part of the `1.4.0-beta.4` release. At this moment, we want to allow the user to use this beta package to export scopes and provide us feedback before we finalize this and ship it as a stable package.
