### ISSUE TITLE
[Exporter.Geneva] Remove `ConvertToJson` option

### ISSUE THREAD

**Issue by utpilla** [open-telemetry/opentelemetry-dotnet-contrib#395]
Remove `ConvertToJson` from `GenevaTraceExporter` and `GenevaLogExporter`.

### Problem
We want to validate the data types for `PrepopulatedFields`. As of today, if someone passes in a value with an unsupported data type, we serialize that into a very unhelpful [string](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Exporter.Geneva/GenevaExporterOptions.cs#L98).

Here's the design for one of the possible solutions:

### Solution
The best thing to do here would be to validate the data upfront when the user actually provides the `PrepopulatedFields` option. The best place to do that would be the [setter ](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Exporter.Geneva/GenevaExporterOptions.cs#L87) of the `PrepopulatedFields`. We have a set of types that we support as a valid data type for the values. These data types are mentioned as various cases in the `switch`. We need a `default` case which will be hit for any unsupported type. For the `default` case, we throw an `ArgumentException` with the message: `$"Type: {value.GetType()} is not supported. Only bool, byte, sbyte, short, ushort, int, uint, long, ulong, float, double, and string are the supported types for PrepopulatedFields values";` .

**Comment by xyq175com** [comment]
@utpilla if we remove the ConvertToJson Option then how to initialize "this.convertToJson" field?

**Comment by utpilla** [comment]
> @utpilla if we remove the ConvertToJson Option then how to initialize "this.convertToJson" field?

@xyq175com There is no way for a user to do a custom initialization of this field. This is not a `public` field.

**Comment by xyq175com** [comment]
> 

Ok thank you I will work on this and drop a PR later.
