### ISSUE TITLE
[Instrumentation.ElasticSearchClient] Fix broken unit tests

### ISSUE THREAD

**Issue by utpilla** [open-telemetry/opentelemetry-dotnet-contrib#406]
Fix the following unit tests:

-  `ElasticsearchClientTests.CanCaptureGetByIdNotFound`: This fails at: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/ElasticsearchClientTests.cs#L145
- `ElasticsearchClientTests.CanCaptureSearchCallWithParseAndFormatRequestOption`: This fails at https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/ElasticsearchClientTests.cs#L488

**Comment by utpilla** [comment]
@ejsmith Please fix these tests.

**Comment by ejsmith** [comment]
@utpilla fixed
