### ISSUE TITLE
MassTransit instrumentation is not tracking Riders

### ISSUE THREAD

**Issue by sergeyshaykhullin** [open-telemetry/opentelemetry-dotnet-contrib#41]
More info here https://github.com/MassTransit/MassTransit/issues/2082

TL;DR
Kafka rider produce traces is not created/reported in some cases

**Comment by eddynaka** [comment]
@sergeyshaykhullin , can you share an example?

@dbarbashov, if you have time, can you take a look?

**Comment by sergeyshaykhullin** [comment]
@eddynaka I posted fully reproducible demo and some assumptions in masstransit issue

Repo: https://github.com/sergeyshaykhullin/MassTransit.Riders.Diagnostics.Demo
Comment: https://github.com/MassTransit/MassTransit/issues/2082#issuecomment-707975601

**Comment by sergeyshaykhullin** [comment]
I guess bug was fixed on MassTransit side.

I will test it as new release created and reopen if instrumentation will not work with MT changes(i guess it will work) 

Thanks!

**Comment by sergeyshaykhullin** [comment]
Instrumentation is working well with fixed version of MassTransit for Kafka TopicProducer
