### ISSUE TITLE
Improve AWS SDK instrumentation for DynamoDB: add db.system attribute.

### ISSUE THREAD

**Issue by rypdal** [open-telemetry/opentelemetry-dotnet-contrib#415]
# Issue with OpenTelemetry.Contrib.Instrumentation.AWS

**Problem:**

The existing instrumentation for AWS SDK DynamoDB invocation does not set the
db.system attribute. The attribute is required according to the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.11.0/specification/trace/semantic_conventions/database.md#connection-level-attributes).

**Solution:**

Update code of the OpenTelemetry.Contrib.Instrumentation.AWS project and add the db.system attribute with value equal to "dynamodb".

**Comment by Kielek** [comment]
Closing per #418. @rypdal, please reopen/let me know if you still need this issue.
