### ISSUE TITLE
Export exception stack

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet-contrib#439]
# Issue with OpenTelemetry.Exporter.Geneva

**Is this a feature request or a bug?**

* [ ] Feature Request
* [ ] Bug

**What is the expected behavior?**

Export exception stack

**What is the actual behavior?**

only exception message and type is exported.

**Comment by imdiptanu** [comment]
@cijothomas Do you have any ETA for this feature support?

**Comment by aditdalvi** [comment]
We definitely need the exception stacktrace for debugging purposes as it contains important invocation information. In addition to this, we also need all information for all inner exceptions to be exported because that data contains important information for debugging as well.

It might be best to do exception.ToString() into a new column since that takes care of outputting all information for the exception and any and all inner exceptions.

**Comment by xyq175com** [comment]
@cijothomas I'm new to this but would like to try some contribution here, can you help to post the example to reproduce this?

**Comment by xyq175com** [comment]
I will work on this and try to drop a PR later.

**Comment by cijothomas** [comment]
@xyq175com I would not recommend picking this issue. This is an advanced feature, and is not recommended for a beginner to this project.

While Geneva exporter is a ETW exporter, the contents are binary serialized and usual ETW tools cannot decode the contents. Once the format is changed to TLD (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/525), it'll be more easily viewable using standard ETW tools like logman.

**Comment by xyq175com** [comment]
@cijothomas Thanks for reply, Do you mean this issue will be fix after the format changed to TLD? I have tried with some code in my local in this file andd it can log the stack trace now for exception.
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/c14c75dd47572c7c603c3fa7b123b7b76ea41d02/src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs#L325
`        // Part A - ex extension
        if (logRecord.Exception != null)
        {
            cursor = MessagePackSerializer.SerializeAsciiString(buffer, cursor, "env_ex_type");
            cursor = MessagePackSerializer.SerializeUnicodeString(buffer, cursor, logRecord.Exception.GetType().FullName);
            cntFields += 1;

            var exceptionMsg = string.IsNullOrWhiteSpace(logRecord.Exception.StackTrace) ?
                logRecord.Exception.Message :
                logRecord.Exception.Message + Environment.NewLine + logRecord.Exception.StackTrace;

            cursor = MessagePackSerializer.SerializeAsciiString(buffer, cursor, "env_ex_msg");
            cursor = MessagePackSerializer.SerializeUnicodeString(buffer, cursor, logRecord.Exception.Message);
            cntFields += 1;
        }
`

**Comment by cijothomas** [comment]
> Do you mean this issue will be easy fix after the format changed to TLD?

No. TLD switch will help any outside Microsoft to see the output using standard ETW tooling.

**Comment by xyq175com** [comment]
> > Do you mean this issue will be easy fix after the format changed to TLD?
> 
> No. TLD switch will help any outside Microsoft to see the output using standard ETW tooling.

Can you help check my fix make sense or not?

**Comment by cijothomas** [comment]
No. We dont want to modify env_ex_msg with the stacktrace. its meant for Message only, and stacktrace must be stored differently.

**Comment by cijothomas** [comment]
Will be sending a PR to add support for this next week, and plan is to have a preview release end of this month. Based on feedback, it'll be part of stable release by Nov.
