### ISSUE TITLE
Add a package for process related metrics 

### ISSUE THREAD

**Issue by xiang17** [open-telemetry/opentelemetry-dotnet-contrib#447]
# Issue with OpenTelemetry.Instrumentation.Runtime

Process related metrics were removed from the Runtime metrics package and they should be added in a separate package and with OpenTelemetry.Instrumentation.Process as a potential name. See the context here: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/404#discussion_r894123445

**Comment by xiang17** [comment]
@cijothomas Can you remove the runtime label? It doesn't belong to the runtime instrumentation library now.

**Comment by reyang** [comment]
@Yun-Ting FYI I've assigned this issue to you.

**Comment by Yun-Ting** [comment]
Alpha version was released: https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Process.
This issue will be closed after the stable release.

**Comment by Yun-Ting** [comment]
Dashboard built with Grafana for 0.5.0 (version number under discussion) release:
![image](https://user-images.githubusercontent.com/16979322/219503264-6226713d-e135-45cc-aebd-1f62545ed241.png)

**Comment by cijothomas** [comment]
Could you send a PR to the repo with the json file?

**Comment by Yun-Ting** [comment]
> Could you send a PR to the repo with the json file?

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1016

**Comment by Kielek** [comment]
0.5.0 version is out, json configuration for graphana included.

Closing.
