### ISSUE TITLE
[Question] Is there a straightforward way to see what is instrumented in each package?

### ISSUE THREAD

**Issue by julealgon** [open-telemetry/opentelemetry-dotnet-contrib#474]
# Issue that does not fit into other categories

I found out that there is a "Runtime" instrumentation extension and got curious about what exactly it exposed. When looking at that specific project's README or CHANGELOG files, I don't see direct mentions of all exposed metrics and traces.

While I'd want to know what that particular package exposes, the same question could also apply to all other instrumentation packages.

Is there a simple way of getting a full description of all instrumentations being done by one given library, or will the library authors (you guys) have to document each one of them at some point?

**Comment by cijothomas** [comment]
The best documentation is the respective readme.md files.

> Is there a simple way of getting a full description of all instrumentations being done by one given library

Could you elaborate what is "simply" ? Is readme.md not simple? For Metrics, the emitted metrics, has name and description, but its not something you can see until you actually use it to collect metrics! Nothing equivalent for traces, other than linking to the semantic conventions it follows.

**Comment by julealgon** [comment]
> Could you elaborate what is "simply" ? Is readme.md not simple? 

The readme is definitely simple, but requires manual maintenance by the maintainers. I see [you just updated the document for the Runtime instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/475), so that's pretty nice. I was wondering if there was a way to automatically "export" telemetry metadata from an instrumentation package so that one could see everything that is provided without the need to have to document it all by hand. I assume the answer here is "there is no such capability".

**Comment by cijothomas** [comment]
Yes. no such automatic discovery capability.
