### ISSUE TITLE
Update to OTel 1.0.0 RC1

### ISSUE THREAD

**Issue by ejsmith** [open-telemetry/opentelemetry-dotnet-contrib#49]
This project is completely broken when upgrading to OTel 0.8. `ActivitySourceAdapter`, `DiagnosticSourceSubscriber`, `ListenerHandler`, `PropertyFetcher` have all been made internal. Is the plan that we have to just copy the source into each of these instrumentations?

**Comment by ejsmith** [comment]
Just started attempting to update this project and it's become very difficult now. I copied a bunch of files over to attempt to make use of them how they are currently being used and ended up having to pull about 10 files over and things still didn't work because those files are accessing internal members. So it seems like all of these contrib projects will need to be updated pretty significantly in order to get them to work again.

**Comment by buvinghausen** [comment]
@ejsmith the whole make them internal thing is a dumpster fire.  It would be one thing if they provided guidance to work around it but all they did in their own instrumentations was make the internals visible to them in AssemblyInfo.cs

**Comment by ejsmith** [comment]
@buvinghausen yeah, agreed. I understand that they want to keep the public API that they are going to support minimal, but it has gotten massively harder to build instrumentations now and meanwhile the included ones are cheating using `InternalsVisibleTo`. Hopefully there will be some sort of compromise soon. Also, hoping they will remove the `InternalsVisibleTo` soon and see how hard and potentially impossible in some cases it has become to build instrumentations.

**Comment by sailorgallifrey** [comment]
I am curious if there is any forward momentum on this. I would like to include the EntityFrameworkCore instrumentation in my application, but it only appears to be working with earlier versions and I would rather stay on the more current version.

**Comment by ejsmith** [comment]
No progress. There is a good amount of work to be done to get these projects fixed and working with latest 1.0 release of OTel. Hoping now that 1.0 is released they will look at this.

**Comment by mikedoug** [comment]
They mentioned working on this immediately following the release, so I think we are all hopeful. :)

**Comment by Jaans** [comment]
Here's hoping! 
Would really like to use @CodeBlanch 's WCF bits now that the first release is out!

**Comment by CodeBlanch** [comment]
@jaans WCF instrumentation is now available on NuGet: https://www.nuget.org/packages/OpenTelemetry.Contrib.Instrumentation.Wcf/

Enjoy!

**Comment by Jaans** [comment]
'tis looking good! Thanks everyone.

**Comment by bravecobra** [comment]
Any progress on EFCore and Masstransit nupkg's compatible with 1.x?

**Comment by ejsmith** [comment]
Well, the code is compatible at this point at least for Elasticsearch, but I don't think they've published any new packages. Not sure why. Have to ask @cijothomas or @CodeBlanch

**Comment by cijothomas** [comment]
The publish part is manual. I'll do a release today/tomorrow. Thanks for the reminder!

**Comment by cijothomas** [comment]
My 1st attempt failed due to CI issues.

Fix: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/106 Need this merged before attemping ES release.

**Comment by cijothomas** [comment]
Also, this issue can be closed now, as the instrumentations are all updated to 1.0.0+
