### ISSUE TITLE
Add TCP transport support to OpenTelemetry.Exporter.Geneva

### ISSUE THREAD

**Issue by Microsoft-NiGoel** [open-telemetry/opentelemetry-dotnet-contrib#498]
OpenTelemetry.Exporter.Geneva contains placeholder plumbing for a TCP transport, but the functionality is not yet implemented. This would be useful in AKS clusters for being able to connect to MDSD over on a TCP port.

**Comment by utpilla** [comment]
We do not have plans to support TCP based exporter for this component. Please use the OTLP exporter if GenevaExporter over Unix Domain Sockets does not serve your purpose.
