### ISSUE TITLE
Implement TcpClient Instrumetnation package

### ISSUE THREAD

**Issue by julealgon** [open-telemetry/opentelemetry-dotnet-contrib#501]
# Issue that does not fit into other categories

**What are you trying to achieve?**

I have a project that relies on a low level TCP connection and uses the `TcpClient` class for communication. I'd like to have this interaction participate in traces alongside the rest of the application.

The question is if it would make sense to have instrumentation similar to that of `HttpClient` that properly propagates tracing information and starts spans at appropriate calls etc.

**What do you expect to see?**

A `OpenTelemetry.Instrumentation.Tcp` package that adds OTel instrumentation to raw `TcpClient`.

**Additional context.**

Add any other context about the problem here. If you followed an existing
documentation, please share the link to it.

**Comment by reyang** [comment]
It makes sense to me.

**Comment by bohdan-parkh** [comment]
Azure SDK for Cosmos Database uses TCP connections in its direct mode. It would be awesome to see instrumentation for these.

**Comment by martinjt** [comment]
It doesn't look like there's been any takers for writing this, so although it sounds great, it doesn't look like there will be maintainers for it.

For CosmosDB, that will work OOTB with the new Azure SDKs.
