### ISSUE TITLE
[MassTransit] two different traceids same flow when using BatchConsumer

### ISSUE THREAD

**Issue by shaykeren** [open-telemetry/opentelemetry-dotnet-contrib#511]
# Issue with OpenTelemetry.Instrumentation.MassTransit

```
List of [all OpenTelemetry NuGet]
<PackageReference Include="OpenTelemetry.Contrib.Instrumentation.MassTransit" Version="1.0.0-beta2" />
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.3.0" />
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.3.0" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.2" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.2" />
<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.2" />

List of [MassTransit NuGet]:
<PackageReference Include="MassTransit" Version="7.3.1" />
<PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
<PackageReference Include="MassTransit.RabbitMQ" Version="7.3.1" />
```

Runtime version:
net6.0

* [X] Bug

**What is the expected behavior?** 
TraceId should be preserved throughout the flow

What do you expect to see?
Span opened by OpenTelemetry.Contrib.Instrumentation.MassTransit should use the previous context and preserve the previous traceId.

**What is the actual behavior?**

### Flow Example:

**TraceId**: 12345
**MyService** /hello  (api route)
otel.library.name: OpenTelemetry.Instrumentation.AspNetCore
span.kind: server

- --> ... internal spans...
- --> **MyService** App.Contracts.EventBus:ErrorFlowReceivedEvent send
        otel.library.name: MassTransit
        span.kind: producer
- **MyOtherService** /error-flow-received consume
           otel.library.name: OpenTelemetry.Contrib.Instrumentation.MassTransit
           span.kind: consumer

- **MyOtherService** ...ConsumerFactories.BatchConsumer<Digma.Contracts.EventBus.ErrorFlowReceivedEvent> process
             otel.library.name: OpenTelemetry.Contrib.Instrumentation.MassTransit            
             span.kind: internal

**TraceId**: 22222 (new traceId)
**MyOtherService** Digma.Analytics.Consumers.ErrorFlowReceivedConsumer process
otel.library.name: OpenTelemetry.Contrib.Instrumentation.MassTransit            
span.kind: internal
- ... internal spans...

please note that a new trace was created for span:  Digma.Analytics.Consumers.ErrorFlowReceivedConsumer process

**Comment by Kielek** [comment]
@shaykeren, consider to upgrade MassTransit to 8.0.0+ which brings native support for Acitvities/OpenTelemetry.

OpenTelemetry.Instrumentation.MassTransit is deprecated. You can find instruction how to handle it under https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/4d7e692ecc50a01f6cef76ef9ea61ac738b000df/src/OpenTelemetry.Instrumentation.MassTransit#deprecated
