### ISSUE TITLE
OWIN Instrumentation

### ISSUE THREAD

**Issue by fjegear** [open-telemetry/opentelemetry-dotnet-contrib#56]
Is there any plan to support OWIN? Looks like it is supported Asp.Net and Asp.Net Core but I have a WebAPI with Asp.Net self hosted using OWIN and I'd like to start using OpenTelemetry.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/1472 There was an attempt, but its not finished.

**Comment by hotpothot** [comment]
@cijothomas, is there any rough ETA when OWIN will be supported?

**Comment by cijothomas** [comment]
No ETA. I am not aware of anyone who has committed to work on it.

**Comment by hotpothot** [comment]
Thanks @cijothomas. Does HttpClientInstrumentation depends on HttpModule? Can we add our owin server activity and use HttpClientInstrumentation?
eg.
builder
.SetResourceBuilder(ResourceBuilder
.CreateDefault()
.AddService("service name")
.AddHttpClientInstrumentation().AddSource("Microsoft.Payment.Web.Server")

**Comment by CodeBlanch** [comment]
@hotpothot 

> Does HttpClientInstrumentation depends on HttpModule?

It does not. On .NET Framework we hook into HttpWebRequest/HttpClient using reflection. On .NET Core we listen to the diagnostic events emitted by the runtime.

> Can we add our owin server activity (use ActivitySource and by starting/stopping an Activity from our middleware using an ActivitySource allows the OpenTelemetry SDK to directly listen to the ActivitySource as Alex suggested) and use HttpClientInstrumentation together?

Totally! If we built an official OWIN middleware that is exactly what we would do. Create an ActivitySource, start activity at the begging of the middleware, call the inner pipeline, stop activity at the end. Register your source using AddSource on the TraverProvider.
