### ISSUE TITLE
[Instrumentation.AWSLambda] HTTP Server semantic conventions for AWS Lambdas.

### ISSUE THREAD

**Issue by rypdal** [open-telemetry/opentelemetry-dotnet-contrib#583]
**Problem:**
According to the [HTTP Server semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions) the following minimal attributes list MUST be provided at span (Activity) creation time (when provided at all):
`http.method`
`http.scheme`
`http.target`
`net.host.name`
`net.host.port`

**Solution:**
Set required HTTP attributes for AWS Lambdas invoked via AWS API Gateway.

**Comment by Oberon00** [comment]
@rypdal Is there still something left to do or can this issue be closed?

**Comment by rypdal** [comment]
@Oberon00 : the issue can be closed.

**Comment by rypdal** [comment]
The corresponding PR has been merged: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/626
