### ISSUE TITLE
OpenTelemetry Exporter is mapping CategoryName to TableMapping

### ISSUE THREAD

**Issue by Jaxelr** [open-telemetry/opentelemetry-dotnet-contrib#611]
# Issue with OpenTelemetry.Exporter.Geneva

I am having a somewhat confusing behavior on the mapping of the event name to the geneva exporter, considering the behavior of other exporters (for example the console exporter). 

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* [OpenTelemetry.Exporter.Geneva.1.4.0-beta.1](https://www.nuget.org/packages/OpenTelemetry.Exporter.Geneva/1.4.0-beta.1)

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file): net6.0

**Is this a feature request or a bug?**

* [X] Feature Request
* [ ] Bug

**What is the expected behavior?**

Preamble, I'm using source generators for logging, but this is unrelated to that feature. Given the following definition for a logger message similar to this:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/5913008/186789477-e5891e5f-163f-4c0d-99c7-8baac04e7513.png">

I would expect the EventName to map into Geneva in a similar fashion to the EventId. But thats not the case. Currently the EventId maps like this:

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/54f22bb22607aa32f65c1349f605ae393381d5f3/src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs#L458-L464

But the event uses the following logic:

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/54f22bb22607aa32f65c1349f605ae393381d5f3/src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs#L245-L273

This implies that the TableMappings are somewhat related to the EventName, which in my opinion is an incorrect assumption, given that a table mapping can contain multiple custom events.

What do you expect to see?

I would expect the categoryName map in this a logic similar to this:

```c#
	var categoryName = logRecord.CategoryName;
	if (categoryName.Length > 0)
	{
		cursor = MessagePackSerializer.SerializeAsciiString(buffer, cursor, categoryName);
		cntFields += 1;
	}
```

**What is the actual behavior?**

The actual behavior is that the event defined is being mapped to the table mapping defined on the AddGenevaLogExporter bootstrap:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/5913008/186784623-020c07c1-2180-4a9f-8df8-11abea678be0.png">

What did you see instead? If you are reporting a bug, create a self-contained
project using the template of your choice and apply the minimum required code to
result in the issue you're observing. We will close this issue if: 

This is a sample repo that shows how the geneva console exporter exports correctly the Event Name as based on the initial partial attrbute definition:

https://github.com/Jaxelr/open-tel-geneva-exporter-repro

<img width="392" alt="image" src="https://user-images.githubusercontent.com/5913008/186789666-513ba39d-ad8b-4348-93d8-b5542afcf0ed.png">

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

Add any other context about the feature request here.

**Comment by rajkumar-rangaraj** [comment]
Duplicate of #584

**Comment by Jaxelr** [comment]
Thanks @rajkumar-rangaraj I will be closing this Issue and will post comments on the original request.
