### ISSUE TITLE
Exported span is showing route template as display name instead of actual path value.

### ISSUE THREAD

**Issue by rineshpk** [open-telemetry/opentelemetry-dotnet-contrib#621]
# Issue with OpenTelemetry.Instrumentation.AspNet

List of all OpenTelemetry NuGet
 `OpenTelemetry.Instrumentation.AspNet 1.0.0-rc9.5`
 `OpenTelemetry 1.3.0`
 `OpenTelemetry.Exporter.Jaeger 1.3.0`

Runtime versions: `net462`, `net48`

**Is this a feature request or a bug?**

* [ ] Feature Request
* [X] Bug

**What is the expected behaviour?**

The activity display name should be the actual path( like `api/values`)

**What is the actual behaviour?**

After the export, it is showing the activity display name as the route template `api/{controller}/{id}` as in the below screenshot,
![image](https://user-images.githubusercontent.com/52862975/188108764-b89eead9-ff7b-4564-a630-d5d53d0d184b.png)

While debugging, the Activity is showing the correct display name, but exported traces show the wrong display name. 
![image](https://user-images.githubusercontent.com/52862975/188109930-a8888902-b09c-4760-86b8-91a2307319bc.png)

**Comment by martinjt** [comment]
It is expected that the span name is the route and not the URL, this is because using the URL would mean high-cardinality data making it into the span name.
