### ISSUE TITLE
Distributed Traces: Add Support to split 'Span' table into multiple tables.

### ISSUE THREAD

**Issue by murthys** [open-telemetry/opentelemetry-dotnet-contrib#656]
# Issue with OpenTelemetry.Exporter.Geneva
Currently the Span table is one big table, we would like guidance\support on splitting this into multiple tables. We are micro services team and would like seprate table for each microsService

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* [OpenTelemetry.Exporter.Geneva
  1.2.6](https://www.nuget.org/packages/OpenTelemetry.Exporter.Geneva/1.2.6)

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* TBD

**Is this a feature request or a bug?**

* [ ] Feature Request

**What is the expected behavior?**
Suppoting  Distributed Span table for each Log Event

What do you expect to see?
Separate Span tables

**What is the actual behavior?**
All columns are in same table

What did you see instead? If you are reporting a bug, create a self-contained
project using the template of your choice and apply the minimum required code to
result in the issue you're observing. We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

## Additional Context

Add any other context about the feature request here.

**Comment by dpk83** [comment]
@reyang Currently TableNameMapping only support changing the default table name for Span, this is an ask to add the ability to redirect span events to multiple tables similar to how logs can be directed to multiple tables.

**Comment by reyang** [comment]
> Currently the Span table is one big table, we would like guidance\support on splitting this into multiple tables. We are micro services team and would like seprate table for each microsService

Would you help to explain what would you do with these separated tables? e.g. do you need to have fine granularity of access control? or it is about data retention? or something else?

**Comment by dpk83** [comment]
@murthys can provide more information. From the initial ask we got he mentioned that this is because the single table is getting very big, so they wanted to split it to multiple tables.

**Comment by murthys** [comment]
Yes its for Granularity, we our multi micro service team(12 micro services). Its getting too complicated to read as all the columns in the same table



________________________________

**Comment by reyang** [comment]
> Yes its for Granularity, we our multi micro service team(12 micro services). Its getting too complicated to read as all the columns in the same table

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Exporter.Geneva#tablenamemappings-optional allows you to change the table name for each service, does it work, and if not, why?

**Comment by utpilla** [comment]
Feel free to reopen the issue if you have more questions.

**Comment by et1975** [comment]
@utpilla the docs you are linking are saying the Span can only have one mapping, while the ask is to provide one-to-many.
Conceptually, I think the problem might be in differentiating the target at the emitting side, which is more about OTEL/Diagnostics interface than it is about OTEL/Geneva interface.

Side note: why does "Span" require explicit mapping instead of respecting "*"?

**Comment by utpilla** [comment]
@et1975

> while the ask is to provide one-to-many.

As asked by reyang earlier in the conversation, why is this needed? For multi service team, you can change the table name for each service as already [suggested](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/656#issuecomment-1258579035). If you are in a similar situation, does that not work?

> Side note: why does "Span" require explicit mapping instead of respecting "*"?

Do you mean using "*" as the key for mapping? It's not applicable to traces (spans) as we only have one entity to map to unlike logs where we usually have to map different log category names to different tables. Using an "*" as the key for mapping when using Logs would send logs from all the various categories into a single table (which is the value provided for the key "*" in the mapping).
