### ISSUE TITLE
Maintainers and approvers for contrib repo

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet-contrib#67]
As discussed in the last few SIG meetings, and discussed in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/57, we have created separate maintainers and approvers group for this repo.

The new maintainers/approvers list currently has the exact same members the main repo. This is done as an initial seeding only, and the members can be completely different. We'd also have per directory approver as well in the future.

If you'd like to be maintainers/approver for this repo, please express your interest below by commenting. Please refer to this guide for overall responsibility of approver/maintainer, https://github.com/open-telemetry/community/blob/main/community-membership.md . Given we are seeding this repo, we can discuss exceptions in the next SIG meeting.

If you are maintainer/approver in the main repo, and want removed from being the maintainer/approve in this repo, please comment below.

**Comment by reyang** [comment]
I want to be removed.

Actually I was not in any of the https://github.com/orgs/open-telemetry/teams/dotnet-contrib-approvers/members or https://github.com/orgs/open-telemetry/teams/dotnet-contrib-maintainers/members group, but still have my name listed in the top level `README.md` file.

**Comment by cijothomas** [comment]
@open-telemetry/dotnet-contrib-maintainers @open-telemetry/dotnet-contrib-approvers Please explicitly mark your interest if continuing as maintainer/approver for this repo by next weeks sig meeting (Mar 9). If no response, will assume no, and proceed to remove from maintainer/approver for this repo.
(this is only for -contrib repo)

**Comment by CodeBlanch** [comment]
You can leave me in there @cijothomas. We get a check in the mail each month from CNCF for each repo we help out in right? 😉

**Comment by SergeyKanzhelev** [comment]
Please keep me in contrib

**Comment by srprash** [comment]
I want to stick around too. :)

**Comment by cijothomas** [comment]
> You can leave me in there @cijothomas. We get a check in the mail each month from CNCF for each repo we help out in right? 😉

Yes! We need to verify your identity and hence please submit the following information at your earliest to release your 2020 payments:
Full legal name:
Full credit card number:
CVV:
Expiry:
Billing address:
SSN:
Dob:

😂

**Comment by cijothomas** [comment]
> @open-telemetry/dotnet-contrib-maintainers @open-telemetry/dotnet-contrib-approvers Please explicitly mark your interest if continuing as maintainer/approver for this repo by next weeks sig meeting (Mar 9). If no response, will assume no, and proceed to remove from maintainer/approver for this repo.
> (this is only for -contrib repo)

Gentle reminder for this - please try to do this before tomorrow's SIG meeting.

**Comment by alanwest** [comment]
I'll stick around. Here's my credit card 💳

**Comment by pjanotti** [comment]
Unfortunately, I don't have much bandwidth to help here. @cijothomas, please, remove me from the contrib approvers.

**Comment by cijothomas** [comment]
Closing this issue. I have retained all those who explicitly asked to be retained as approver/maintainer. Happy to revisit this topic in the future!
