### ISSUE TITLE
Using EventSource name as prefix in metrics to avoid conflict

### ISSUE THREAD

**Issue by xsoheilalizadeh** [open-telemetry/opentelemetry-dotnet-contrib#684]
# Issue with OpenTelemetry.Instrumentation.EventCounters

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry.Instrumentation.EventCounters (0.1.0-alpha.1)
* OpenTelemetry.Exporter.Prometheus.AspNetCore (1.4.0-beta.1)

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* net6.0

**Is this a feature request or a bug?**

* [x] Feature Request
* [x] Bug

**What is the expected behavior?**

Using event source name as a prefix in metrics that are going to be exported by Prometheus

For example in **System.Net.Http** and **Microsoft.AspNetCore.Hosting**  there is a counter named `current_requests` which makes a conflict between these two metrics. It has to be like following

```
system_net_http_current_requests

microsoft_aspnetcore_hosting_current_requests
```

**What is the actual behavior?**

Right now we have metrics that are named as current_requests

**Comment by mic-max** [comment]
Please update to the newest version of this package. The new instrument name is decided [here ](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/926386e68c9066e8032853e8309abdf4088d8dca/src/OpenTelemetry.Instrumentation.EventCounters/EventCountersMetrics.cs#L122) and is of the format `EventCounters.{event_source_name}.{counter_name}`

**Comment by utpilla** [comment]
@xsoheilalizadeh Please reopen the issue if you still face the issue after upgrading to the latest version of `OpenTelemetry.Instrumentation.EventCounters`.
