### ISSUE TITLE
Add auto-detection of container information to resource if cgroupv2 is used

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-dotnet-contrib#693]
# Issue with OpenTelemetry.Extensions.Docker

**Is this a feature request or a bug?**

Feature Request

**What is the expected behavior?**

When using a docker container with cgroupv2 turned on I would like to see a `container.id` being automatically detected.

**What is the actual behavior?**

When I use a docker container with cgroupv2 turned on I don't get the `container.id` detected automatically

## Additional Context

This is a known "issue", it has been fixed with the JavaScript implementation already ([ContainerDetector.ts](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/detectors/node/opentelemetry-resource-detector-container/src/detectors/ContainerDetector.ts)): 

Detection of the `container.id` in `ContainerResource.java` currently works by reading from `/proc/self/cgroup`. That does not work when cgroupv2 is turned on. However, based on these two sources there's another place to read from:

- [How to get docker container ID from within the container with cgroup v2](https://stackoverflow.com/questions/68816329/how-to-get-docker-container-id-from-within-the-container-with-cgroup-v2)
- [Python NullResource error when running torizoncore-builder build](https://community.toradex.com/t/python-nullresource-error-when-running-torizoncore-builder-build/15240/4)

In short, the `container.id` could be read from /proc/self/mountinfo as well. This also works for `containerd` and not only docker.

Eventually it would be good to have a standard for that, but unfortunately this is a long-standing non-moving [OCI issue](https://github.com/opencontainers/runtime-spec/issues/1105), until then a combination of both approaches seems to be reliable enough.

### Related
We wanted to use the `container.id` as an example for resource detection at the OTel docs: https://github.com/open-telemetry/opentelemetry.io/issues/1835
Same ticket for Java Instrumentation: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6694

cc @cartermp, @swetharavichandrancisco 

### Containerd

The Node.JS implementation also works with other container runtime implementations, namely contaienrd, probably others as well.

**Comment by iskiselev** [comment]
Fixed with #839

**Comment by Kielek** [comment]
Closing: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/693#issuecomment-1379630573
