### ISSUE TITLE
ConsoleExporter/SimpleActivityExportProcessor runs "too early", thus resulting in missing HTTP status code and incorrect Activity Names

### ISSUE THREAD

**Issue by ajkonkol** [open-telemetry/opentelemetry-dotnet-contrib#701]
# Issue with OpenTelemetry.Instrumentation.AspNet

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.2.0`):

OpenTelemetry version="1.4.0-beta.1"
OpenTelemetry.Api version="1.4.0-beta.1"
OpenTelemetry.Exporter.Console version="1.4.0-beta.1" 
OpenTelemetry.Instrumentation.AspNet version="1.0.0-rc9.6"
OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule version="1.0.0-rc9.6" 
OpenTelemetry.Instrumentation.Http version="1.0.0-rc9.7"

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

net472

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

I expect to see an Activity.DisplayName of something like "test/something/{id}" (since my action method has a Route attribute of `[Route("test/something/{id}")]`), and the presence of a http.status_code in the Activity.Tags

**What is the actual behavior?**

The Activity.DisplayName is "test/something/123", and there is no http.status_code in the Activity.Tags.

This can be easily reproduced within the Examples.AspNet project here: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/examples/AspNet.  Simply run the Example project, ensuring that you are using the setting UseExporter = "console".  Then, hit the URL /about_attr_route/123.  This _should_ result in an Activity.DisplayName of "about_attr_route/{customerId}", but instead it's "about_attr_route/123", and there is no http.status_code tag.

If I instead manually register a ConsoleExporter as follows, the problem goes away, presumably since the Batch processor waits until "later" to invoke the ConsoleExporter to write the results, after the code inside HttpInListener.OnStopActivity has had a chance to modify the Activity.DisplayName and add the http.status_code tag.

`
.AddProcessor(new BatchActivityExportProcessor(
                    new ConsoleActivityExporter(
                        new ConsoleExporterOptions { 
                            Targets = ConsoleExporterOutputTargets.Debug 
                        })
                    )
                );
`

This seems to indicate that there is an out-of-order processing going on here, where the OnStopActivity gets executed _after_ the SimpleActivityExportProcessor invokes the configured ConsoleExporter.  Thus, the telemetry is exported in an "unfinished" state.

The same is true if I register a custom processor that inherits from BaseProcessor<Activity>.  In that case, my OnEnd method gets called _before_ the Activity.DisplayName is correct and the http.status_code has been set.  So this isn't just a problem with the ConsoleExporter, but rather seems more fundamental to the ordering of processing between the HttpInListener and any Processors that are registered.

**Comment by qhris** [comment]
I believe this should be fixed by #1388.

The activity was stopped before the `HttpInListener` was run.
This triggered all processors (including simple/console exporters) to run before `OnStopActivity` which is what sets the status code tag.

**Comment by Kielek** [comment]
@ajkonkol, closing per @qhris comment. Please upgrade to the latest release of this package. If it no help, reopen/create new issue so we can help you.
