### ISSUE TITLE
Latest NuGet package does not include span duration bug fix.

### ISSUE THREAD

**Issue by TravisTroyer** [open-telemetry/opentelemetry-dotnet-contrib#745]
# Issue with OpenTelemetry.Exporter.Instana

The following bug fix was committed back in May, but does not seem to be included in the latest OpenTelemetry.Exporter.Instana NuGet package (1.0.0):

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/commit/21f73d394a9877a58944dc11257a2792c4f13260

**Comment by Kielek** [comment]
@TravisTroyer https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/749#issuecomment-1300730137
