### ISSUE TITLE
Unable to use Kestrel event counters with this package

### ISSUE THREAD

**Issue by davidfowl** [open-telemetry/opentelemetry-dotnet-contrib#758]
# Issue with OpenTelemetry.Instrumentation.EventCounters

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

```
OpenTelemetry.Extensions.Hosting 1.0.0-rc9.8
OpenTelemetry.Instrumentation.EventCounters  1.0.0-alpha.1
OpenTelemetry.Exporter.Prometheus.AspNetCore 1.4.0-beta.2
```

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

net60, net70

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

I expected to see Kestrel's event counters on the prometheus endpoint.

**What is the actual behavior?**

They don't show up because of errors with the counter naming scheme. Here's the error:

```
Measurements from Instrument 'EventCounters.Microsoft-AspNetCore-Server-Kestrel.current-connections', Meter 'OpenTelemetry.Instrumentation.EventCounters' will be ignored. Reason: 'Instrument name is invalid.'. Suggested action: 'The name must comply with the OpenTelemetry specification'
```

**Repro steps**

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.8" />
        <PackageReference Include="OpenTelemetry.Instrumentation.EventCounters" Version="1.0.0-alpha.1" />
        <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.4.0-beta.2" />
    </ItemGroup>
</Project>
```

```C#
using OpenTelemetry.Metrics;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddOpenTelemetryMetrics(metrics =>
{
    metrics.AddPrometheusExporter();
    metrics.AddEventCountersInstrumentation(c =>
    {
        c.AddEventSources("Microsoft-AspNetCore-Server-Kestrel");
    });
});

var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.MapPrometheusScrapingEndpoint();

app.Run();
```

## Additional Context

Add any other context about the feature request here.

**Comment by mic-max** [comment]
[This PR](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/740) should resolve this issue once merged

**Comment by mic-max** [comment]
@utpilla #740 fixes this, you can close.

**Comment by davidfowl** [comment]
Is there a new package release or release planned that would have this fix?

**Comment by Kielek** [comment]
@davidfowl, I think all changes in this package was released together with https://www.nuget.org/packages/OpenTelemetry.Instrumentation.EventCounters/1.0.0-alpha.2

**Comment by Kielek** [comment]
@davidfowl, if you are able to confirm that it is working correctly, please close the issue :)

**Comment by davidfowl** [comment]
Confirmed it works! Thanks everyone!
