### ISSUE TITLE
Deprecate This Package, MassTransit v8.0.0 and later has built-in OTEL support

### ISSUE THREAD

**Issue by phatboyg** [open-telemetry/opentelemetry-dotnet-contrib#778]
# Issue with OpenTelemetry.Instrumentation.MassTransit

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

OpenTelemetry.Instrumentation.MassTransit

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

ANY

**Is this a feature request or a bug?**

* [X] Feature Request
* [ ] Bug

**What is the expected behavior?**

That the readme is updated to indicate this is only usable with MassTransit v7.

**What is the actual behavior?**

Causes significant confusion for users.

## Additional Context

Add any other context about the feature request here.

**Comment by Kielek** [comment]
Done in scope of #788.
Documentation how to handle newer packages under https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/4d7e692ecc50a01f6cef76ef9ea61ac738b000df/src/OpenTelemetry.Instrumentation.MassTransit#deprecated

Closing.
