### ISSUE TITLE
Update Google.* nugets

### ISSUE THREAD

**Issue by EricStG** [open-telemetry/opentelemetry-dotnet-contrib#783]
# Issue with OpenTelemetry.Exporter.Stackdriver

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

OpenTelemetry.Exporter.Stackdriver 1.0.0-beta.3 
OpenTelemetry.Extensions.Hosting 1.0.0-rc9.9 
OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc9.9 
OpenTelemetry.Instrumentation.GrpcNetClient 1.0.0-rc9.9 
OpenTelemetry.Instrumentation.Http 1.0.0-rc9.9 

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file): 

net6.0

**Is this a feature request or a bug?**

* [X] Feature Request
* [ ] Bug

**What is the expected behavior?**

The Stackdriver exporter is using older version of Google packages

**What is the actual behavior?**

The Stackdriver exporter should be using updated version of Google packages

## Additional Context

This is causing us issues that is forcing us to downgrade other, unrelated, Google cloud packages, so we can't use newer features.

This is caused due to version restrictions on the packages.

For example, the used version of Google.Cloud.Monitoring.V3 (2.6.0) has:
```
Google.Api.Gax.Grpc.GrpcCore (>= 3.7.0 && < 4.0.0)
Google.LongRunning (>= 2.3.0 && < 3.0.0)
Grpc.Core (>= 2.41.0 && < 3.0.0)
```
But the latest (3.1.0) has:
```
Google.Api.Gax.Grpc (>= 4.0.0 && < 5.0.0)
Google.LongRunning (>= 3.0.0 && < 4.0.0)
```

**Comment by Kielek** [comment]
@EricStG, could you please create PR and test library with newly referenced verion?
I think it will be good idea to 
update references to 
```
    <PackageReference Include="Google.Cloud.Monitoring.V3" Version="3.0.0" />
    <PackageReference Include="Google.Cloud.Trace.V2" Version="3.0.0" />
    <PackageReference Include="OpenTelemetry" Version="$(OpenTelemetryCoreLatestVersion)" />
```

`3.0.0` should allow to resolve Google dependencies to higher versions and brings wider supported range than `3.1.0`.
OpenTelemetryCoreLatestVersion will be resolved to 1.3.1.
