### ISSUE TITLE
Redis instrumentation shouldn't throw exception when there isn't a redis connection

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry-dotnet-contrib#784]
This is the relevant line of code: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.StackExchangeRedis/TracerProviderBuilderExtensions.cs#L65

If you have this package installed and added, but you're not actually using redis, it will throw an exception and prevent other instrumentation from getting initialized. This can happen if you have convenience metapackage that pulls in several instrumentation packages and initializes the whole set.

Instead, maybe a diagnostic log can be emitted, and/or a message output to the console. Thoughts? Happy to contribute.

**Comment by Kielek** [comment]
@cartermp, it should be fixed right now.

The exception is only thrown when you explicitly pass null value to `public static TracerProviderBuilder AddRedisInstrumentation(this TracerProviderBuilder builder, IConnectionMultiplexer connection, Action<StackExchangeRedisInstrumentationOptions> configure)`. Other overloads are accepting null value.

Released as 1.0.0-rc9.9


Ref: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/4d7e692ecc50a01f6cef76ef9ea61ac738b000df/src/OpenTelemetry.Instrumentation.StackExchangeRedis/TracerProviderBuilderExtensions.cs#L65
