### ISSUE TITLE
remove NetCoreApp3.1 from CI

### ISSUE THREAD

**Issue by TimothyMothra** [open-telemetry/opentelemetry-dotnet-contrib#791]
Follow up from https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/759#discussion_r1026765172

## .NET Core 3.1 is officially scheduled to reach end of life on December 3, 2022

- Official Statement: https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by Kielek** [comment]
Effort handled in scope of #1031
