### ISSUE TITLE
AWS Instrumentation Breaks AmazonAutoScalingClient

### ISSUE THREAD

**Issue by Bob343** [open-telemetry/opentelemetry-dotnet-contrib#799]
# Issue with OpenTelemetry.Contrib.Instrumentation.AWS

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

OpenTelemetry - 1.4.0-beta.2
OpenTelemetry.Api - 1.4.0-beta.2
OpenTelemetry.Contrib.Instrumentation - 1.0.1
OpenTelemtry.Exporter.Console - 1.4.0-beta.2

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

net6.0

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

OTEL instrumentation of an AmazonAutoScalingClient, traces generated as calls are made.

**What is the actual behavior?**

An exception is thrown as soon as the constructor for the client is called.

## Additional Context

I've instrumented several other AWS APIs without issue, we recently added ASG's into the mix and they immediately break when AWS instrumentation is enabled. I'll attach this as a zip as well, but this is the full extent of the source code:
![image](https://user-images.githubusercontent.com/15220647/204346795-1bfe76ed-a485-4518-94be-dc74ed1fbaa0.png)

With line 15 uncommented, line 24 throws an exception "Cannot find a handler of type EndpointResolver". Comment out line 15 and the calls work as expected (AWS credentials are needed on line 24 if not running under an IAM role).

[AWSSDKTest - minimal repro.zip](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/files/10106324/AWSSDKTest.-.minimal.repro.zip)

Please let me know if this would be better to upload into a new repo and I can link that here instead. We also have an enterprise support case opened with AWS, but we thought this might be better placed here since it's directly caused by introducing otel instrumentation.

**Comment by Kielek** [comment]
@srprash, could you please check?

**Comment by Bob343** [comment]
I see this was actually resolved under #726 - going to close this issue. Thanks!
