### ISSUE TITLE
WCF client instrumentation on aspnet: Sequential WCF calls are incorrectly nested when async

### ISSUE THREAD

**Issue by regaleagle** [open-telemetry/opentelemetry-dotnet-contrib#812]
# Issue with OpenTelemetry.Instrumentation.Wcf

Sequential async WCF call spans are nested inside the previous WCF call spans (their `Activity.ParentSpanId` is that of the activity for the previous WCF call) instead of the actual parent.

When running client instrumentation using OpenTelemetry.Instrumentation.Wcf, the `TelemetryClientMessageInspector` implementation of `AfterReceiveReply` is using the `correlationState` variable to work on the activity that was started in `BeforeSendRequest` and should encapsulate the WCF call. Unfortunately when the WCF call is async, `AfterReceiveReply` can run on an unrelated thread. The result is that when the activity has a parent (in my case due to the AspNet instrumentation but any activity parent will do), `activity.Stop()` will be operating on a different `Activity.Current` (in `System.Diagnostics`) when resetting to the previous Activity (the parent), this is because `Activity.Current` is an `AsyncLocal` static variable. This means that when you have a subsequent WCF call on the same thread as the first, `Activity.Current` will actually be the first WCF call and will be considered the parent of the new WCF call. 

I'm not really sure how this might be dealt with as its a combo of WCF behavior and `System.Diagnostics` use of `AsyncLocal` in the `Activity` class, maybe a check on whether the activity is stopped (that information is preserved)? 

The workaround is to wrap the WCF calls in another async task which ensures they share the static AsyncLocal Activity.Current variable as per this comment in a similar issue https://github.com/dotnet/extensions/issues/3412#issuecomment-676004005 but it's not lovely.

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

OpenTelemetry.Instrumentation.Wcf v1.0.0.rc9.4 (but is persistent in latest version from source)
OpenTelemetry v1.3.1
OpenTelemetry.Api v1.3.1

Runtime version:

net472

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**

That activity spans for sequential WCF calls wrapped in the same parent Activity will have the same `Activity.ParentSpanId` (Namely that of the parent Activity

**What is the actual behavior?**

The activity span for the second WCF call will reference the spanId of the first WCF call as `Activity.ParentSpanId` instead of the parent activity.

Here's a minimal example using a parent activity wrapping two consecutive WCF calls based on the aspnet WCF client example in the repo:

```csharp
using System;
using System.Diagnostics;
using System.ServiceModel;
using System.Threading.Tasks;
using OpenTelemetry;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;

namespace Examples.Wcf.Client;

internal static class Program
{
    private static readonly ActivitySource MyActivitySource = new ActivitySource(
        "MySource");

    public static async Task Main()
    {
        using var openTelemetry = Sdk.CreateTracerProviderBuilder()
            .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("Wcf-Client"))
            .AddSource("MySource")
            .AddAspNetInstrumentation()
            .AddWcfInstrumentation(x => x.SuppressDownstreamInstrumentation = false)
            .AddConsoleExporter()
            .Build();
        using (var activity = MyActivitySource.StartActivity("SayHello"))
        {
            activity?.SetTag("foo", 1);
            activity?.SetTag("bar", "Hello, World!");
            activity?.SetTag("baz", new int[] { 1, 2, 3 });
            activity?.SetStatus(ActivityStatusCode.Ok);
            await CallService("StatusService_Http").ConfigureAwait(false);
            //await CallService("StatusService_Tcp").ConfigureAwait(false);
        }

        Console.WriteLine("Press enter to exit.");
        Console.ReadLine();
    }


    private static async Task CallService(string name)
    {
        StatusServiceClient client = new StatusServiceClient(name);
        try
        {
            await client.OpenAsync().ConfigureAwait(false);

            var response = await client.PingAsync(
                new StatusRequest
                {
                    Status = Guid.NewGuid().ToString("N"),
                }).ConfigureAwait(false);
            var response2 = await client.PingAsync(
                new StatusRequest
                {
                    Status = Guid.NewGuid().ToString("N"),
                }).ConfigureAwait(false);
            Console.WriteLine($"Server returned: {response?.ServerTime}");
            Console.WriteLine($"Server returned next: {response2?.ServerTime}");
        }
        finally
        {
            try
            {
                if (client.State == CommunicationState.Faulted)
                {
                    client.Abort();
                }
                else
                {
                    await client.CloseAsync().ConfigureAwait(false);
                }
            }
            catch
            {
            }
        }
    }
}
```

**Comment by mconnew** [comment]
In the WCF Client we had a bug in duplex transport implementation which caused things to deadlock when executing a sync client call after an async call. The underlying problem was that the continuation that executed the line of code after `await client.DoWorksAsync()` was ran synchronously after completion of the receive code had matched up a reply message with the request. This prevented the code in the receive loop which calls `TaskCompletionSource.SetResult(...)` from returning as the thread was effectively hijacked by the main calling thread. If you then made a synchronous call, it never completed as the receive loop was blocked.  
I suspect this bug was contributing to this behavior as we would run a second request effectively as a child Task of the completion of the first request. Can you check if the latest 6.0 GA release fixes your problem?

**Comment by repl-chris** [comment]
I can confirm this issue still exists using the latest GA release (6.0.23.25304)
