### ISSUE TITLE
[OpenTelemetry.Instrumentation.Process] Multiple provider dispose issue

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet-contrib#831]
# Issue with OpenTelemetry.Instrumentation.Process

`process.cpu.utilization` requires tracking of the last collection time. When multiple providers are used, it needs to track it based on the provider. There isn't a really good way to do this. What we're doing is creating a `Meter` instance for each provider. But each instance has the same name for `Meter` & `Instrument`s so SDK is probably just treating everything as one data stream. To compound that problem, when a provider is disposed it should dispose its instrumentation. Due to the same name issue this leads to all providers being unsubscribed if one provider is disposed.

Update: [There is a failing test which demonstrates the disposal problem](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/73486c705ea4cf55dec78c9271fe380ab236e0ad/test/OpenTelemetry.Instrumentation.Process.Tests/ProcessMetricsTests.cs#L128).

**Comment by alanwest** [comment]
> process.cpu.utilization requires tracking of the last collection time. When multiple providers are used, it needs to track it based on the provider. There isn't a really good way to do this.

Agreed, this seems like a spec limitation.

The [semantics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/process-metrics.md#process) define `process.cpu.utilization` as:

> Difference in process.cpu.time since the last measurement, divided by the elapsed time and number of CPUs available to the process.

I don't think instrumentation can maintain state like this without violating the spec in some way. This definition seems be be geared toward an out-of-proc implementation like the collector's host metrics receiver.

I haven't found other languages that have implemented `process.cpu.utilization`. Java appears to to have introduced their own utilization [metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#jvm-metrics) with different semantics.

For example, `process.runtime.jvm.cpu.utilization` is defined as:

> Recent CPU utilization for the process

with a footnote

> These utilizations are not defined as being for the specific interval since last measurement

Should we consider doing something similar? That is, just compute utilization based on some fixed recent interval?

**Comment by alanwest** [comment]
Commented here as well https://github.com/open-telemetry/opentelemetry-specification/issues/2439#issuecomment-1353938369
