### ISSUE TITLE
Metrics: Add support to emit metrics to multiple namespaces

### ISSUE THREAD

**Issue by dpk83** [open-telemetry/opentelemetry-dotnet-contrib#832]
# Issue with OpenTelemetry.Exporter.Geneva

**Is this a feature request or a bug?**

* [ x] Feature Request
* [ ] Bug

**What is the expected behavior?**
User should be configure their application to send metrics to more than one namespace i.e. different set of metrics to different namespace.

What do you expect to see?

Developer should be able to specify the following
- Metrics with names starting with XYZ should be sent to monitoring namespace A
- Metrics with names starting with ABC should be sent to monitoring namespace B

It should also pick the best match from the configuration e.g. if there are 2 entries
- Metrics with names X.Y goes to namespace A1
- Metrics with name X goes to namespace A2

then for any metrics with names X.Y.* should pick A1 as namespace, any other metrics with X.* should pick to A2

**What is the actual behavior?**

Currently only one namespace is supported. All metrics are emitted to a single namespace with no capability to send it to different namespaces.

## Additional Context

Add any other context about the feature request here.

**Comment by dpk83** [comment]
@reyang

**Comment by reyang** [comment]
I think it's very likely that such feature will be implemented by allowing a convention - the namespace will be provided as a dimension (or maybe even better, modeled as a Resource), which doesn't require any change on the SDK/Exporter. The downstream processing would be able to understand the special dimension/resource and route the metrics stream to the desired destination (and of course remove the dimension if intended).

We can keep this open for tracking purpose (most likely no code change needed in this repo, we might need some doc updates to explain how to use it).

**Comment by utpilla** [comment]
@dpk83 Starting `1.5.0-alpha.2` version of `OpenTelemetry.Exporter.Geneva`, you can now send metrics to any custom combination of account and namespace by adding the respective reserved dimensions to your desired metrics. Please look at this PR description for more information: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1111

Does this solve your problem?

**Comment by dpk83** [comment]
> Does this solve your problem?

Thanks @utpilla. It does solve the issue partially and atleast unblocks our users. The other support needs to come from .NET Meter APIs first https://github.com/dotnet/runtime/issues/84321
