### ISSUE TITLE
Deprecate OpenTelemetry.Instrumentation.ElasticsearchClient

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-contrib#865]
# Issue with OpenTelemetry.Instrumentation.ElasticsearchClient

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

N/A

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* All of them.

**Is this a feature request or a bug?**

* [ ] Feature Request
* [ ] Bug
* [x] Deprecation request

**What is the expected behavior?**

Package is deprecated, 
Code is removed from the repository.
Information how to instrument package is added  `.AddSource("Elastic.Clients.Elasticsearch.ElasticsearchClient")`.

**What is the actual behavior?**

N/A

## Additional Context

Consider to make the last release including changes. It should probably be released as `1.0.0-beta.4`.
Similar PR for MassTransit #788.

**Comment by Kielek** [comment]
@ejsmith what is your opinion on this?

**Comment by ejsmith** [comment]
I think that the 8.0 elasticsearch client just came out recently and it has extensive breaking changes that are going to force many people to stay on the older client for a long time. This package will be needed for a long while still IMO.
