### ISSUE TITLE
Support for .NET 7.0

### ISSUE THREAD

**Issue by tsvetelintsonev** [open-telemetry/opentelemetry-dotnet-contrib#899]
# Issue with OpenTelemetry.Instrumentation.AWSLambda

`OpenTelemetry 1.1.0`

Runtime version `net7.0`

**Is this a feature request or a bug?**

* [x] Feature Request
* [ ] Bug

**What is the expected behavior?**
Support .NET 7.0

What do you expect to see?
Update `OpenTelemetry` to `1.3.2`

**What is the actual behavior?**
Doens't support .NET 7.0

**Comment by cijothomas** [comment]
You can add OpenTelemetry 1.3.2 version to your project to unblock. AWSLambda package has a >=1.1.0 for OpenTelemetry package.

**Comment by tsvetelintsonev** [comment]
Ok, thanks. I will give it a try in the coming days.

**Comment by Kielek** [comment]
@tsvetelintsonev were you able to handle the issue? Can we close this task?

**Comment by Kielek** [comment]
Closing. This package was released with indirect reference to OTel SDK 1.5.1 https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/Instrumentation.AWSLambda-1.2.0-beta.1/src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md#120-beta1
