### ISSUE TITLE
Consistent readme for all components

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet-contrib#906]
Only some has links to nuget in main readme:
Eg: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Exporter.Instana#readme

Some do not have link to nuget:
Eg:
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Extensions.Docker#readme
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.AWSLambda

Opening to track making all readme files consistent.

**Comment by Kielek** [comment]
@cijothomas, closing. All README headers was synced already.
