### ISSUE TITLE
Add exception type as a tag to process.runtime.dotnet.exceptions.count metric

### ISSUE THREAD

**Issue by pcwiese** [open-telemetry/opentelemetry-dotnet-contrib#922]
Can we include the exception type as a tag on the total exceptions counter? I see the counter is driven by this code which probably has the exception type available. Its very useful to be able to see spikes in certain types of exceptions.

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/193940d49992fd758ffb19f4756e7ce802b88e02/src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs#L203

List of [all OpenTelemetry NuGet
OpenTelemetry.Instrumentation.Runtime  Version="1.1.0-beta.3"

Platform
net6.0

**Is this a feature request or a bug?**
* [x] Feature Request
* [ ] Bug

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/562
