### ISSUE TITLE
Geneva Exporter on Linux drops all logs from short-lived processes

### ISSUE THREAD

**Issue by maxgolov** [open-telemetry/opentelemetry-dotnet-contrib#923]
# Issue with OpenTelemetry.Exporter.Geneva

List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using (e.g. `OpenTelemetry 1.0.2`):

```
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.3.2" />
    <PackageReference Include="OpenTelemetry.Exporter.Geneva" Version="1.3.1" />
```

It's happening with latest code built from tip of the `main` branch of contrib.

**Is this a feature request or a bug?**

It's a Feature Request to address a Bug..

* [X] Feature Request
* [X] Bug

**What is the expected behavior?**

I'm implementing a process restart monitor. No Logs should lost for short-lived processes, no matter how short-lived the process is - even if it lives for 1 second, all logs should be emitted and flushed to monitoring agent. You can compare the current behavior with Console Exporter that uses `SimpleLogRecordExportProcessor`, and that one doesn't drop any logs.

**What do you expect to see?**

All logs emitted by the process get passed to Geneva Monitoring Agent on Linux.

**What is the actual behavior?**

Exporter `Export` function is not getting called. No logs sent to Geneva. The issue is specifically affecting Unix Domain Socket, because Windows implementation uses different batching processor.

## Additional Context

I'd like to propose a patch to allow customizations of the batching parameters, by adding an additional delegate for creation of a batching processor with custom parameters:
```
    public static OpenTelemetryLoggerOptions AddGenevaLogExporter(
        this OpenTelemetryLoggerOptions options,
        Action<GenevaExporterOptions> configure,
        Func<BaseExporter<LogRecord>, BaseProcessor<LogRecord>> newProcessorDelegate = null)
    {
        Guard.ThrowIfNull(options);

        var genevaOptions = new GenevaExporterOptions();
        configure?.Invoke(genevaOptions);
        var exporter = new GenevaLogExporter(genevaOptions);

        if (newProcessorDelegate != null)
        {
            return options.AddProcessor(newProcessorDelegate(exporter));
        }

        if (exporter.IsUsingUnixDomainSocket)
        {
            return options.AddProcessor(new BatchLogRecordExportProcessor(exporter));
        }
        else
        {
            return options.AddProcessor(new ReentrantExportProcessor<LogRecord>(exporter));
        }
    }
```

That way the batching parameters can be configured irrespective of what OS the code is running on:

```
    builder.AddOpenTelemetry(options =>
    {
        options.AddGenevaLogExporter(exporterOptions =>
        {
             exporterOptions.ConnectionString = OpenTelemetryGenevaEndpoint;
             exporterOptions.CustomFields = new List<string> { "traceId", "eventName", "eventId", "componentId", "roleName" };
        },
        // Configure custom export processor: SimpleLogRecordExportProcessor or BatchLogRecordExportProcessor
        (exporter) => new BatchLogRecordExportProcessor(exporter,
                maxQueueSize : 2048,
                scheduledDelayMilliseconds : 100,
                exporterTimeoutMilliseconds : 1000,
                maxExportBatchSize : 1)
        ).
        SetResourceBuilder(ResourceBuilder.CreateDefault().AddService(serviceName: "MyService", serviceVersion: "1.0.0"));
    });
```

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Logs/OpenTelemetryLoggerProvider.cs#L254-L262 Dispose() in provider should be good enough, is that not working?

**Comment by maxgolov** [comment]
> Dispose() in provider should be good enough, is that not working?

Nope. It doesn't.

**Comment by maxgolov** [comment]
Manual call to `Dispose()` flushes only 1 pending record, discarding the rest. It appears to be prematurely closing the socket. Should `Dispose()` be added to finalizer in the Logging Provider? I think the console logger example app doesn't mention it. Console Exporter immediately flushes as well. Ultimately I still have event loss, even with a call to `Dispose()`. Whereas if I have access to adjust the batching timer, then my events show-up at the sink in realtime. It also helps with debugging: if I set a breakpoint in my service code, I can observe my log events on `fluent-bit` or Geneva in realtime, and/or in near-realtime without waiting for the default batching timer.

**Comment by CodeBlanch** [comment]
@cijothomas This is kind of a guess, but I think the problem might be here: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/b1eb56a07f2bc76b704150517a8c10913631e50e/src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/Transport/UnixDomainSocketDataTransport.cs#L75

Sockets always write to a buffer.

The docs for [Close](https://learn.microsoft.com/dotnet/api/system.net.sockets.socket.close#system-net-sockets-socket-close) say...

> For connection-oriented protocols, it is recommended that you call Shutdown before calling the Close method. This ensures that all data is sent and received on the connected socket before it is closed.

I'm thinking maybe the missing records are sitting in the send buffer and we should add a call to `Shutdown` before `Dispose` to make sure they are sent?

PS: [Close is just a call to Dispose](https://github.com/dotnet/runtime/blob/3d616586d7aa9b49226e28f353a9b20ce0b6e6b8/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L939-L943).

**Comment by maxgolov** [comment]
I posted the "workaround" that allows more frequent calls to `public override ExportResult Export(in Batch<LogRecord> batch)` method. Ideally it would be great if we have more "realtime"'ish flushes to Unix Domain Socket, similar to how it works over ETW on Windows. There's little sense to batch when it's essentially a localhost superfast high-speed pipe. It would've made more sense if Geneva Exporter had support for TCP, but the patch to add it wasn't accepted before.

**Comment by maxgolov** [comment]
> I'm thinking maybe the missing records are sitting in the send buffer and we should add a call to Shutdown before Dispose to make sure they are sent?

That's likely the case. I can instrument my sample to verify how many times the `Export` was called, and with what number of log records.

**Comment by CodeBlanch** [comment]
@maxgolov I spent some time today testing the unix socket code, everything seems fine to me. If you can provide any more detail or a small project which reproduces the issue that would be super helpful.

**Comment by maxgolov** [comment]
@CodeBlanch - you can close this. I figured out how to implement the immediate batching in my code with one function. It solved the issues I had with containers. I could repro this only if agent experiences a restart or closes the socket at about the same time when the app is shutdown, OR if there's more events than can fit in one batch. In that case some pending events won't be flushed. This could happen if:

- UDS from one container get forwarded to another container over TCP
- TCP connection is flaky/times out/reconnects
- In that case UDS closes the socket, reopening it later.
- App still has a batch of events pending/unsent
- ...but since socket connection got disconnected once - exporter won't try to reconnect and just shuts down with some events pending (even if the agent is available again)

I could largely avoid the loss in this case with more aggressive/immediate timers.
