### ISSUE TITLE
Full DI support for GenevaTraceExporter

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet-contrib#938]
**Is this a feature request or a bug?**

* [x] Feature Request
* [ ] Bug

**What is the expected behavior?**
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/925 allowed additional configuration options for AddGenevaTraceExporter, however it still does not allow reading exporteroptions from the app's `IConfiguration`, if any.
The ask is to follow the recommendation from the OTel SDK : https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#registration-extension-method-guidance-for-library-authors

**Comment by vishweshbankwar** [comment]
This was addressed in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1218
