### ISSUE TITLE
[OpenTelemetry.Instrumentation.EntityFrameworkCore] Add support to enable logging of parameter values

### ISSUE THREAD

**Issue by paul-french-ev** [open-telemetry/opentelemetry-dotnet-contrib#947]
# Issue with OpenTelemetry.Instrumentation.EntityFrameworkCore

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.0.2`):

* OpenTelemetry 1.4.0-rc.3
* OpenTelemetry.Exporter.Jaeger 1.4.0-rc.3
* OpenTelemetry.Extensions.Hosting 1.4.0-rc.3
* OpenTelemetry.Extensions.Propagators 1.4.0-rc.3
* OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc9.12
* OpenTelemetry.Instrumentation.EntityFrameworkCore 1.0.0-beta.4
* OpenTelemetry.Instrumentation.GrpcNetClient 1.0.0-rc9.12
* OpenTelemetry.Instrumentation.Http 1.0.0-rc9.12
* OpenTelemetry.Exporter.Prometheus 1.3.0-rc.2
* OpenTelemetry.Instrumentation.GrpcCore 1.0.0-beta.5

Runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can
find this information from the `*.csproj` file):

* net6.0

**Is this a feature request or a bug?**

* [x] Feature Request
* [ ] Bug

**What is the expected behavior?**

I've enabled the adding of command text:
```
.AddEntityFrameworkCoreInstrumentation(options =>
{
    options.SetDbStatementForText = true;
})
```
This then adds `db.statement` tags as expected into the traces.

However, I've also enabled the logging of sensitive data via the DbContextOptionsBuilder:
`.EnableSensitiveDataLogging()`

I was hoping that this would also add the parameter values into the `db.statement` text, but there's no change.

**What is the actual behavior?**

Would it be possible to add an option that would enable this behaviour?

**Comment by Kielek** [comment]
@paul-french-ev, I am not sure that it is good practice to log sensitive data in any way. IMO it is not good candidate for official solution.

Please check https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/d835d5d43be73874fb6ae29b57bfdbfa09127c1d/src/OpenTelemetry.Instrumentation.EntityFrameworkCore/EntityFrameworkInstrumentationOptions.cs#L39-L46
released in https://www.nuget.org/packages/OpenTelemetry.Instrumentation.EntityFrameworkCore/1.0.0-beta.4 gives you a possibility to extend activity by any data from IDBCommand.

Is it fine for you?

**Comment by paul-french-ev** [comment]
@Kielek that's perfect - thanks for pointing it out to me.

**Comment by Kielek** [comment]
I am closing the issue. Feel free to create the new one if needed :)

**Comment by joegoldman2** [comment]
There doesn't seem to be a standard attribute for parameter values in the spec. What attribute can be used to add the parameter values?

**Comment by Kielek** [comment]
@joegoldman2 , parameter values should be treated by default as senstive data. There is not, and probably there will be no default recommendation for these attributes. If you need, you should create something custom.
